"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {useLanguage} from "../ui/language-context";
import {useSession} from "../ui/session-context";

const apiBase=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api/v1";
type LiveProjection={projectionHash:string;organizationId:string;source:string;evidence:Record<string,number>;decisionJobs:Record<string,number>;treasuryWorkflows:Record<string,number>;treasuries:Array<{treasuryId:string;displayName:string;state:string;chainId:number;version:number}>;latestActivity:Array<{eventId:string;eventType:string;objectId:string;payloadHash:string;createdAt:string}>;latestImmutableEventAt:string|null;advisoryOnly:true;assetExecutionAuthorized:false};

const candles=[42,47,44,51,55,53,61,59,67,64,70,66,73,77,72,69,75,81,78,84,80,88,85,91,87,83,79,82,76,72,74,68,70,65,69,73,71,77,80,78,83,86,84,89,92,90,94,91];
const agents=[
  ["Governor","SYNTHESIZING","Governance"],["Research","READY","Protocol"],["Strategy","CHALLENGED","Protocol"],["Quant","READY","Liquidity"],
  ["Risk","REVIEWING","Liquidity"],["Compliance","READY","Governance"],["Portfolio","READY","Treasury"],["Treasury","READ ONLY","Treasury"],
];
const activity=[
  ["09:08:41","USC proof generated","proof_7d1f","VERIFIED"],["09:08:38","Source receipt confirmed","ev_01J8...A91C","VERIFIED"],
  ["09:08:34","Evidence normalized","sha256:93bd...c144","FROZEN"],["09:08:31","Classification routed","route_4f92","COMPLETE"],
  ["09:08:26","Risk challenged Strategy","a2a_0192","OPEN"],["09:08:19","RAG manifest frozen","rag_7a31","IMMUTABLE"],
];
const tabs=["Market Flow","Evidence","Agent A2A","Governance Queue","Alerts","Audit","RAG Retrieval","Skill Audit","Attestcoin Actions"];
const demoStages=["Evidence request created","Attestcoin proof verified","Evidence snapshot frozen","Eight Agents deliberating","PID recommendation bounded","DAO authorization required","Execution safely withheld","Treasury feedback observed"];
const controlActions=[
  ["EVIDENCE","Request cross-chain liquidity proof","READ"],
  ["RAG","Retrieve reserve policy + 2025 depeg incident","READ"],
  ["AI COMMITTEE","Propose defensive stablecoin allocation +6.8%","ADVISE"],
  ["PID","Clamp proposal to +2.4% max control step","BOUND"],
  ["DAO GATE","Require quorum and Timelock authorization","WITHHELD"],
  ["TREASURY","Observe counterfactual impact only","NO EXECUTION"],
];
const ragInfluences=[
  ["policy_reserve_v4","Minimum liquid reserve 35%","Hard constraint"],
  ["incident_depeg_2025","Reduce step size during liquidity stress","Risk precedent"],
  ["mandate_execution_v2","AI may advise; DAO alone authorizes","Authority rule"],
];

function MarketChart({tick=0,nav="1.0842",running=false}:{tick?:number;nav?:string;running?:boolean}){const wave=[0,2,-1,3,-2,1,4,-1][tick%8],series=candles.map((value,index)=>index<38?value:value+wave*((index-37)/11));return <figure className="market-chart"><figcaption className="sr-only">Deterministic simulated real-time candlestick chart. This is not live market data.</figcaption><svg viewBox="0 0 960 330" role="img" aria-label="Treasury NAV simulated real-time demo chart"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#39e5cc" stopOpacity=".18"/><stop offset="1" stopColor="#39e5cc" stopOpacity="0"/></linearGradient></defs>{[40,90,140,190,240,290].map(y=><line key={y} x1="34" x2="930" y1={y} y2={y} className="chart-grid"/>)}{series.map((value,index)=>{const x=42+index*18.2,up=index===0||value>=series[index-1],body=Math.max(5,Math.abs(value-(series[index-1]??value-3))*2.1),y=270-value*2.25;return <g key={x} className={up?"candle-up":"candle-down"}><line x1={x} x2={x} y1={y-8} y2={y+body+10}/><rect x={x-4} y={y} width="8" height={body}/><rect className="volume" x={x-4} y={315-(value%23)*1.2} width="8" height={(value%23)*1.2}/></g>})}<polyline className="chart-average" points={series.map((v,i)=>`${42+i*18.2},${275-v*2.15}`).join(" ")}/><line x1="34" x2="930" y1="104" y2="104" className="evidence-line"/><text x="38" y="96" className="chart-label">VERIFIED EVIDENCE / ev_demo_frozen</text><text x="842" y="28" className="chart-price">NAV {nav}</text><text x="842" y="48" className="chart-muted">{running?`SIMULATED TICK ${String(tick).padStart(2,"0")}`:"DEMO FIXTURE"}</text></svg></figure>}

export default function Dashboard(){const[activeTab,setActiveTab]=useState(tabs[0]);const[demoStep,setDemoStep]=useState(0);const[demoTick,setDemoTick]=useState(0);const[demoRunning,setDemoRunning]=useState(false);const[liveProjection,setLiveProjection]=useState<LiveProjection|null>(null);const[streamState,setStreamState]=useState<"OFFLINE"|"CONNECTING"|"LIVE"|"RECONNECTING">("OFFLINE");const{tr}=useLanguage();const auth=useSession();useEffect(()=>{if(auth.phase!=="connected"||!auth.session?.activeOrganizationId){setStreamState("OFFLINE");setLiveProjection(null);return}setStreamState("CONNECTING");const stream=new EventSource(`${apiBase}/cockpit/stream`,{withCredentials:true});const validTenant=(value:{organizationId?:string;assetExecutionAuthorized?:boolean})=>value.organizationId===auth.session?.activeOrganizationId&&value.assetExecutionAuthorized===false;const onProjection=(event:MessageEvent<string>)=>{try{const projection=JSON.parse(event.data) as LiveProjection;if(!validTenant(projection)){stream.close();setStreamState("OFFLINE");return}setLiveProjection(projection);setStreamState("LIVE")}catch{setStreamState("RECONNECTING")}};const onHeartbeat=(event:MessageEvent<string>)=>{try{const heartbeat=JSON.parse(event.data) as {organizationId:string;assetExecutionAuthorized:false};if(!validTenant(heartbeat)){stream.close();setStreamState("OFFLINE");return}setStreamState("LIVE")}catch{setStreamState("RECONNECTING")}};stream.addEventListener("projection",onProjection as EventListener);stream.addEventListener("heartbeat",onHeartbeat as EventListener);stream.onerror=()=>setStreamState("RECONNECTING");return()=>{stream.removeEventListener("projection",onProjection as EventListener);stream.removeEventListener("heartbeat",onHeartbeat as EventListener);stream.close()}},[auth.phase,auth.session?.activeOrganizationId]);useEffect(()=>{if(!demoRunning)return;const timer=window.setInterval(()=>setDemoStep(current=>{if(current>=demoStages.length-1){window.clearInterval(timer);setDemoRunning(false);return current}return current+1}),700);return()=>window.clearInterval(timer)},[demoRunning]);useEffect(()=>{if(!demoRunning)return;const ticker=window.setInterval(()=>setDemoTick(current=>current+1),250);return()=>window.clearInterval(ticker)},[demoRunning]);const runDemo=()=>{setDemoStep(0);setDemoTick(0);setDemoRunning(true)};const fluctuation=[0,.0004,-.0002,.0007,-.0003,.0002,.0006,-.0001][demoTick%8],navValue=1.0842+demoStep*.0013+fluctuation,flowPulse=[0,860,-420,1320,-610,540,1080,-260][demoTick%8];const projectedActivity=liveProjection?.latestActivity.map(item=>[new Date(item.createdAt).toLocaleTimeString("en-GB",{hour12:false}),item.eventType,item.payloadHash,`IMMUTABLE / ${item.objectId}`])??activity;return <div className={demoRunning?"terminal-dashboard demo-running":"terminal-dashboard"}>
  <section className="demo-control" aria-label="Deterministic MVP demonstration"><div><span className="demo-badge">MVP DEMO</span><span className={demoRunning?"realtime-badge active":"realtime-badge"}><i/> {demoRunning?"SIMULATED REAL-TIME · 250ms":"SIMULATED DATA"}</span><strong>{demoRunning?"Enterprise treasury cycle running":demoStep===demoStages.length-1?"Demonstration cycle complete":"Run the enterprise treasury cycle"}</strong><small>Deterministic replay / no API write / no signer / no broadcast</small></div><ol>{demoStages.map((stage,index)=><li key={stage} className={index<demoStep?"complete":index===demoStep?"active":"pending"}><i/>{stage}</li>)}</ol><button type="button" onClick={runDemo} disabled={demoRunning}>{demoRunning?`RUNNING ${demoStep+1} / ${demoStages.length}`:demoStep?"RUN DEMO AGAIN":"RUN ONE-CLICK DEMO"}</button></section>
  <section className="terminal-banner" aria-label="Data and authority status"><div><span className="pulse-dot"/> {liveProjection?"ORGANIZATION LIVE PROJECTION":tr("DETERMINISTIC DEMO FIXTURE")}</div><strong>{tr("Evidence First")}</strong><span>{tr("Attestcoin provides facts, not decisions")}</span><em>{tr("ADVISORY ONLY / EXECUTION WITHHELD")}</em></section>
  <section className="live-projection" aria-live="polite"><span className={`stream-state ${streamState.toLowerCase()}`}><i/>{streamState}</span><div><small>SERVER-SCOPED TENANT STREAM</small><b>{liveProjection?`${liveProjection.treasuries.length} TREASURIES / ${liveProjection.evidence.VERIFIED??0} VERIFIED EVIDENCE`:auth.phase==="connected"?"SELECT AN ORGANIZATION":"SIGN-IN OPTIONAL / DEMO AVAILABLE"}</b></div><div><small>DECISION JOBS</small><b>{liveProjection?Object.values(liveProjection.decisionJobs).reduce((sum,value)=>sum+value,0):"—"}</b></div><div><small>TREASURY WORKFLOWS</small><b>{liveProjection?Object.values(liveProjection.treasuryWorkflows).reduce((sum,value)=>sum+value,0):"—"}</b></div><div><small>PROJECTION HASH</small><b>{liveProjection?`${liveProjection.projectionHash.slice(0,12)}…${liveProjection.projectionHash.slice(-8)}`:"NO LIVE SESSION"}</b></div><em>READ ONLY / SSE / AUTO-RECONNECT / NO EXECUTION</em></section>
  <nav className="terminal-tabs" aria-label="Cockpit analysis functions"><a href="#market-overview">{tr("Overview")}</a><a href="#market-overview">{tr("Market Analysis")}</a><Link href="/attestcoin">{tr("Attestcoin Flow")}</Link><Link href="/evidence">{tr("Evidence")}</Link><Link href="/decisions">{tr("Decision Committee")}</Link><Link href="/strategies">{tr("Strategy & PID")}</Link><Link href="/knowledge">{tr("RAG Knowledge")}</Link><Link href="/skills">{tr("Skills Center")}</Link><Link href="/governance">{tr("Governance")}</Link><Link href="/audit">{tr("Audit")}</Link></nav>
  <section id="market-overview" className="terminal-layout">
    <div className="terminal-main">
      <article className="terminal-panel chart-panel"><header><div><span className="terminal-kicker">{tr("CORE TREASURY / CREDITCOIN TESTNET")}</span><h1>{tr("Treasury NAV / USDC")}</h1></div><div className="quote-strip"><span><small>NAV</small><b>{navValue.toFixed(4)}</b></span><span><small>24H</small><b className="positive">+{(1.72+demoStep*.08+fluctuation*70).toFixed(2)}%</b></span><span><small>{tr("TURNOVER")}</small><b>{(3.18+demoStep*.04+Math.abs(fluctuation)*18).toFixed(2)}%</b></span><span><small>{tr("BUY / SELL")}</small><b>{(1.42+demoStep*.03+fluctuation*24).toFixed(2)}x</b></span></div></header><div className="chart-tools"><button type="button">1H</button><button className="selected" type="button">4H</button><button type="button">1D</button><span>MA 20</span><span>VOL</span><span className="mock-tag">{demoRunning?"SIMULATED REAL-TIME":tr("NOT LIVE")}</span></div><MarketChart tick={demoTick} nav={navValue.toFixed(4)} running={demoRunning}/><div className="market-metrics"><span><small>{tr("BUY FLOW")}</small><b className="positive">${(284120+demoStep*3200+flowPulse).toLocaleString("en-US")}</b></span><span><small>{tr("SELL FLOW")}</small><b className="negative">${(200440-demoStep*900-flowPulse/2).toLocaleString("en-US")}</b></span><span><small>{tr("NET FLOW")}</small><b>+${(83680+demoStep*4100+flowPulse*1.5).toLocaleString("en-US")}</b></span><span><small>{tr("VOLUME")}</small><b>${(484560+demoStep*2300+Math.abs(flowPulse)*2).toLocaleString("en-US")}</b></span><span><small>{tr("SLIPPAGE EST.")}</small><b>{Math.max(8,14-demoStep+(demoTick%3-1))} bps</b></span></div></article>

      <article id="attestcoin-flow" className="terminal-panel evidence-flow"><header><div><span className="terminal-kicker">{tr("TRUST EVIDENCE LAYER")}</span><h2>{tr("Attestcoin Verification and Classification Flow")}</h2></div><span className="verified-chip">{tr("VERIFIED PIPELINE / MOCK ADAPTER")}</span></header><div className="flow-grid"><div className="flow-node sources"><small>{tr("CROSS-CHAIN SOURCES")}</small><strong>Ethereum / Base</strong><strong>Arbitrum / Creditcoin</strong></div><i>--&gt;</i><div className="flow-node attest"><small>{tr("ATTESTCOIN USC")}</small><strong>{tr("Proof Job")}</strong><span>confirmations 12 / 12</span></div><i>--&gt;</i><div className="flow-node"><small>{tr("NORMALIZE")}</small><strong>{tr("Quality 96 / 100")}</strong><span>{tr("Evidence ID frozen")}</span></div><i>--&gt;</i><div className="flow-node routing"><small>{tr("CLASSIFICATION ROUTING")}</small><strong>{tr("Liquidity / Governance")}</strong><strong>{tr("Protocol / Treasury")}</strong></div></div><div className="flow-branches"><div><span>{tr("LIQUIDITY")}</span><b>Quant / Risk / Treasury</b></div><div><span>{tr("GOVERNANCE")}</span><b>Governor / Compliance</b></div><div><span>{tr("PROTOCOL")}</span><b>Research / Strategy</b></div><div><span>{tr("TREASURY")}</span><b>Portfolio / Treasury</b></div><div className="branch-rag"><span>{tr("FROZEN RAG MANIFEST")}</span><b>{tr("Verified Evidence + governed memory")}</b></div></div><footer>Every Decision freezes Evidence IDs, source hashes, classifications and retrieval manifests. Classification never promotes proof truth or execution authority.</footer></article>

      <section className="control-row"><article id="pid-console" className="terminal-panel pid-panel"><header><div><span className="terminal-kicker">{tr("CLOSED-LOOP CONTROL")}</span><h2>{tr("PID Advisory Console")}</h2></div><span className="advisory-chip">{tr("ADVISORY ONLY")}</span></header><div className="pid-gauge"><div><small>{tr("TARGET")}</small><b>40.0%</b></div><div className="pid-track"><i style={{width:"80%"}}/><span>Observed 32.0% / error +8.0pp</span></div><div><small>{tr("OUTPUT")}</small><b>+2.40%</b></div></div><div className="pid-terms"><span>P <b>+2.08</b></span><span>I <b>+0.32</b></span><span>D <b>OFF</b></span><span>Deadband <b>1.0pp</b></span><span>Anti-windup <b>ACTIVE</b></span></div><p>Recommendation: review a bounded stablecoin allocation increase. No trade, signature or broadcast is generated.</p></article><article id="rag-knowledge" className="terminal-panel compact-panel"><span className="terminal-kicker">{tr("RAG KNOWLEDGE")}</span><h2>{tr("Frozen Retrieval")}</h2><strong>{tr("8 role-scoped manifests")}</strong><p>Organization ACL / immutable citations / injection-isolated content.</p><span className="verified-chip">5 / 5 EVAL PASS</span></article><article id="skills-center" className="terminal-panel compact-panel"><span className="terminal-kicker">{tr("SKILLS CENTER")}</span><h2>{tr("Governed Loading")}</h2><strong>{tr("6 skills available")}</strong><p>Schema-bound tools / frozen input / immutable Skill Audit.</p><span className="advisory-chip">{tr("NO SIGNER / NO BROADCAST")}</span></article></section>

      <section className="control-impact-grid">
        <article className="terminal-panel counterfactual-panel"><header><div><span className="terminal-kicker">CONTROL EFFECT / COUNTERFACTUAL SIMULATION</span><h2>Same Market Shock, Different Treasury Outcome</h2></div><span className="mock-tag">SIMULATION ONLY</span></header><div className="outcome-compare"><div className="uncontrolled"><small>UNCONTROLLED BASELINE</small><strong>{(-4.8+demoStep*.08-fluctuation*180).toFixed(2)}%</strong><span>Projected drawdown</span><b>Volatility {(6.4+Math.abs(fluctuation)*140).toFixed(2)}%</b></div><i>VS</i><div className="controlled"><small>AEOS CONTROLLED</small><strong>{(-2.1+demoStep*.12-fluctuation*45).toFixed(2)}%</strong><span>Projected drawdown</span><b>Volatility {(3.2+Math.abs(fluctuation)*45).toFixed(2)}%</b></div><div className="benefit"><small>SIMULATED BENEFIT</small><strong>+{(2.7+demoStep*.04).toFixed(2)}pp</strong><span>Drawdown avoided</span><b>{Math.round(44+demoStep*2)}% lower risk</b></div></div><footer>AEOS does not control market price. It bounds Treasury exposure and action size; comparison uses the same deterministic shock path.</footer></article>
        <article className="terminal-panel rag-impact-panel"><header><div><span className="terminal-kicker">RAG INFLUENCE TRACE</span><h2>Governed Memory Changed the Advice</h2></div><span className="verified-chip">3 CITATIONS FROZEN</span></header><div className="rag-citations">{ragInfluences.map(([id,claim,effect],index)=><div key={id} className={demoStep>=2+index?"applied":"queued"}><span>{id}</span><p>{claim}</p><b>{effect}</b></div>)}</div><div className="rag-delta"><small>WITHOUT RAG</small><span>AI proposal +6.8% / missing incident constraint</span><i>→</i><small>WITH RAG + PID</small><strong>Bounded proposal +2.4% / DAO review</strong></div></article>
      </section>
      <article className="terminal-panel action-ledger"><header><div><span className="terminal-kicker">AI / PID / DAO ACTION LEDGER</span><h2>Visible Operations and Authority State</h2></div><span className="advisory-chip">NO ASSET EXECUTION</span></header><div className="action-rows">{controlActions.map(([actor,action,state],index)=><div key={actor} className={demoStep>=Math.min(index+1,7)?"complete":demoStep===index?"active":"pending"}><span>{String(index+1).padStart(2,"0")}</span><b>{actor}</b><p>{action}</p><em>{state}</em><small>{demoStep>=Math.min(index+1,7)?"IMMUTABLE DEMO EVENT":"AWAITING STAGE"}</small></div>)}</div></article>
      <article className="terminal-panel event-panel"><div className="event-tabs" role="tablist" aria-label="Operational event views">{tabs.map(tab=><button key={tab} role="tab" aria-selected={activeTab===tab} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</div><div className="event-summary"><span>ACTIVE VIEW</span><strong>{activeTab}</strong><small>{liveProjection?"Organization-scoped immutable database events":"Deterministic demonstration records / immutable identifiers"}</small></div><table><thead><tr><th>TIME</th><th>EVENT</th><th>IMMUTABLE REFERENCE</th><th>STATE</th></tr></thead><tbody>{projectedActivity.map(row=><tr key={`${row[0]}-${row[2]}`}>{row.map((cell,index)=><td key={`${index}-${cell}`} data-label={["Time","Event","Reference","State"][index]}>{cell}</td>)}</tr>)}</tbody></table></article>
    </div>

    <aside className="terminal-right" aria-label="Operational intelligence panels">
      <article className="terminal-panel live-actions"><header><div><span className="terminal-kicker">{tr("ATTESTCOIN ACTIONS")}</span><h2>{tr("Oracle Data Flow")}</h2></div><span className="mock-tag">DEMO</span></header><ol>{["Query received","Source receipt confirmed","USC proof generated","CC3 verification observed","Evidence normalized","Routed to RAG and Agents"].map((item,index)=><li key={item}><i className={index<5?"done":"active"}/><span>{tr(item)}<small>{index<5?"immutable receipt":"classification dispatch"}</small></span><time>09:08:{31+index*2}</time></li>)}</ol><div className="oracle-stats"><span><b>24</b> verified</span><span><b>1</b> quarantined</span><span><b>2</b> stale</span><span><b>186ms</b> latency</span></div></article>
      <article className="terminal-panel"><header><div><span className="terminal-kicker">DECISION COMMITTEE</span><h2>Eight-Agent Matrix</h2></div><Link href="/decisions">OPEN</Link></header><div className="agent-matrix">{agents.map(([name,state,route])=><div key={name}><span>{name}</span><b>{state}</b><small>{route} evidence</small></div>)}</div></article>
      <article className="terminal-panel a2a-panel"><span className="terminal-kicker">DEPARTMENT A2A</span><h2>Challenge Network</h2><div><span>Research</span><i>&lt;--&gt;</i><span>Risk</span></div><div><span>Strategy</span><i>&lt;--&gt;</i><span>Compliance</span></div><div><span>Quant</span><i>&lt;--&gt;</i><span>Portfolio</span></div><div><span>Treasury</span><i>--&gt;</i><span>Governor</span></div><small>Evidence IDs + Challenge IDs required</small></article>
      <article className="terminal-panel broker-panel"><span className="terminal-kicker">REVERSE EVIDENCE REQUEST BROKER</span><h2>Agent Demand Loop</h2><ol><li>Agent detects Evidence gap</li><li>Server derives requester role</li><li>Bounded request reaches Attestcoin</li><li>New immutable snapshot is verified</li><li>Child Decision reruns all eight roles</li></ol><div className="broker-states"><span>REQUESTED</span><span>FETCHING</span><span>VERIFIED</span><span>SATISFIED</span></div></article>
      <article className="terminal-panel authority-lock"><strong>{tr("DAO IN CONTROL")}</strong><p>{tr("AI, Attestcoin, RAG, PID and Skills have zero asset execution authority.")}</p><span>{tr("EXECUTION WITHHELD")}</span></article>
    </aside>
  </section>
</div>}


