"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./page.module.css";
import {ApiError,useSession} from "../ui/session-context";

export type Evidence={id:string;predicate:string;value:unknown;chain:{id:number;blockNumber:number};source:{provider?:string;reference?:string};verification:{status:string};freshness:string;freshnessExpiresAt:string;qualityScore:number;qualityComponents?:Record<string,number>;observedAt:string;contentHash:string;conflictGroupId?:string|null};
type Filters={status:string;freshness:string;chainId:string;predicate:string;minQuality:string};
const emptyFilters:Filters={status:"",freshness:"",chainId:"",predicate:"",minQuality:""};
const ingestRoles=new Set(["ADMIN","REVIEWER","OPERATOR"]),snapshotRoles=new Set(["ADMIN","TREASURY_COMMITTEE","REVIEWER"]);
const errorMessage=(cause:unknown)=>cause instanceof ApiError?`${cause.message}${cause.requestId?` / Request ${cause.requestId}`:""}`:cause instanceof Error?cause.message:"Request failed.";
function displayValue(value:unknown){if(!value||typeof value!=="object")return "—";const item=value as{amount?:string;decimals?:number;symbol?:string};if(!item.amount||!Number.isInteger(item.decimals))return item.symbol??"Structured value";const decimals=item.decimals??0,padded=item.amount.padStart(decimals+1,"0"),whole=decimals?padded.slice(0,-decimals):padded,fraction=decimals?padded.slice(-decimals).replace(/0+$/ ,""):"";return `${item.symbol??""} ${Number(whole).toLocaleString()}${fraction?`.${fraction}`:""}`.trim()}

export default function EvidencePage(){
 const auth=useSession();const[items,setItems]=useState<Evidence[]>([]),[selected,setSelected]=useState<string[]>([]),[draft,setDraft]=useState<Filters>(emptyFilters),[filters,setFilters]=useState<Filters>(emptyFilters),[nextCursor,setNextCursor]=useState<string|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);const activeOrganizationId=auth.session?.activeOrganizationId,role=auth.session?.role??"";
 const query=useMemo(()=>{const params=new URLSearchParams({limit:"20"});for(const[key,value]of Object.entries(filters))if(value)params.set(key,value);return params.toString()},[filters]);
 const load=useCallback(async(cursor?:string)=>{if(!activeOrganizationId)return;setLoading(true);setError("");try{const result=await auth.request<{items:Evidence[];nextCursor:string|null}>(`/evidence?${query}${cursor?`&cursor=${encodeURIComponent(cursor)}`:""}`);setItems(current=>cursor?[...current,...result.items]:result.items);setNextCursor(result.nextCursor);if(!cursor)setSelected([])}catch(cause){setError(errorMessage(cause))}finally{setLoading(false)}},[activeOrganizationId,auth,query]);
 useEffect(()=>{void load()},[load]);
 const ingest=async(chainId:number)=>{setBusy(true);setError("");setNotice("");try{await auth.request("/evidence/mock-ingest",{method:"POST",csrf:true,headers:{"idempotency-key":`web-evidence-${chainId}-${crypto.randomUUID()}`},body:JSON.stringify({chainId})});setNotice(`Mock Attestcoin sample for chain ${chainId} was ingested and server-verified.`);await load()}catch(cause){setError(errorMessage(cause))}finally{setBusy(false)}};
 const createSnapshot=async()=>{setBusy(true);setError("");setNotice("");try{const snapshot=await auth.request<{manifest_hash:string}>("/evidence/snapshots/create",{method:"POST",csrf:true,headers:{"idempotency-key":`web-snapshot-${crypto.randomUUID()}`},body:JSON.stringify({evidenceIds:selected})});setNotice(`Immutable Evidence Snapshot frozen / ${snapshot.manifest_hash}`)}catch(cause){setError(errorMessage(cause))}finally{setBusy(false)}};
 if(auth.phase==="checking")return <section className={styles.gate} aria-live="polite"><span className="section-kicker">SESSION CHECK</span><h1>Verifying organization session</h1><p>Evidence is read only within the server-resolved organization_id boundary.</p></section>;
 if(!auth.session)return <section className={styles.gate}><span className="section-kicker">PHASE 1 / AUTH REQUIRED</span><h1>Evidence Explorer</h1><p>Sign the server-generated SIWE message first. It proves identity only and grants no transaction, vote or asset authority.</p><button className="primary-action" type="button" onClick={()=>void auth.connectWallet()}>Connect wallet and sign in</button>{auth.error&&<p role="alert" className="inline-error">{auth.error}</p>}</section>;
 if(!activeOrganizationId)return <section className={styles.gate}><span className="section-kicker">ORGANIZATION REQUIRED</span><h1>Select a DAO workspace</h1><p>Evidence queries require a server-session organization_id. Select or create an organization in the workspace panel.</p><p className={styles.boundary}>No x-organization-id / cross-tenant objects return 404 / missing context fails closed</p></section>;
 return <div className={styles.page}><header className={styles.hero}><div><span className="section-kicker">PHASE 1 / EVIDENCE INTELLIGENCE</span><h1>Evidence Explorer</h1><p>Query verified facts, inspect freshness and conflicts, and freeze a traceable immutable Evidence Snapshot.</p></div><div className={styles.authority}><span>READ / REVIEW</span><strong>Organization isolation active</strong><small>{role} / execution withheld</small></div></header>
 <section className={styles.filters} aria-label="Evidence filters"><label>Verification<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}><option value="">All</option><option value="VERIFIED">Verified</option><option value="REJECTED">Rejected</option><option value="UNVERIFIED">Unverified</option></select></label><label>Freshness<select value={draft.freshness} onChange={event=>setDraft({...draft,freshness:event.target.value})}><option value="">All</option><option value="FRESH">Fresh</option><option value="STALE">Stale</option><option value="ARCHIVED">Archived</option></select></label><label>Network<select value={draft.chainId} onChange={event=>setDraft({...draft,chainId:event.target.value})}><option value="">All chains</option><option value="11155111">Sepolia / 11155111</option><option value="80002">Polygon Amoy / 80002</option></select></label><label>Predicate<input value={draft.predicate} placeholder="asset.balance" onChange={event=>setDraft({...draft,predicate:event.target.value.trim()})}/></label><label>Minimum quality<input type="number" min="0" max="100" value={draft.minQuality} placeholder="0-100" onChange={event=>setDraft({...draft,minQuality:event.target.value})}/></label><div className={styles.filterActions}><button type="button" onClick={()=>setFilters(draft)}>Apply filters</button><button type="button" onClick={()=>{setDraft(emptyFilters);setFilters(emptyFilters)}}>Reset</button></div></section>
 <section className={styles.commandBar} aria-label="Evidence actions"><div><strong>{items.length}</strong><span>results</span><strong>{selected.length}</strong><span>selected</span></div><div><span className={styles.mockLabel}>ATTESTCOIN / MOCK ONLY</span>{ingestRoles.has(role)&&<><button type="button" disabled={busy||!auth.canMutate} onClick={()=>void ingest(11155111)}>Ingest Sepolia</button><button type="button" disabled={busy||!auth.canMutate} onClick={()=>void ingest(80002)}>Ingest Polygon</button></>}{snapshotRoles.has(role)&&<button className={styles.snapshotAction} type="button" disabled={busy||!auth.canMutate||!selected.length} onClick={()=>void createSnapshot()}>Freeze snapshot ({selected.length})</button>}</div></section>
 {!auth.canMutate&&<p className={styles.warning}>The HttpOnly session remains safe for reads. Re-authenticate with SIWE to restore the in-memory CSRF token before writes.</p>}{error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
 {loading&&!items.length?<div className={styles.empty}>Reading the organization-isolated Evidence view...</div>:!items.length?<div className={styles.empty}><strong>No matching Evidence</strong><p>Adjust the filters or let an authorized role ingest an explicitly labeled Mock sample.</p></div>:<section className={styles.list} aria-label="Evidence results">{items.map(item=>{const selectable=item.verification.status==="VERIFIED";return <article key={item.id} className={item.freshness==="STALE"?styles.stale:""}><div className={styles.cardHead}><label><input type="checkbox" disabled={!selectable} checked={selected.includes(item.id)} onChange={event=>setSelected(event.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><span className={styles.status} data-status={item.verification.status}>{item.verification.status}</span></label><span className={styles.freshness} data-freshness={item.freshness}>{item.freshness}</span></div><Link href={`/evidence/${item.id}`} className={styles.value}>{displayValue(item.value)}</Link><p>{item.predicate}</p><dl><div><dt>CHAIN</dt><dd>{item.chain.id}</dd></div><div><dt>BLOCK</dt><dd>{item.chain.blockNumber}</dd></div><div><dt>QUALITY</dt><dd>{item.qualityScore}/100</dd></div></dl>{item.conflictGroupId&&<p className={styles.conflict}>Conflict group / {item.conflictGroupId}</p>}<code title={item.contentHash}>{item.contentHash}</code><footer><span>{item.source.provider??"unknown source"}</span><time dateTime={item.observedAt}>{new Date(item.observedAt).toLocaleString("en-US")}</time></footer></article>})}</section>}{nextCursor&&<button className={styles.loadMore} type="button" disabled={loading} onClick={()=>void load(nextCursor)}>{loading?"Loading...":"Load more Evidence"}</button>}</div>}
