"use client";

import {useCallback,useEffect,useState} from "react";
import {MvpDemoPage} from "../ui/mvp-demo-page";
import {ApiError,useSession} from "../ui/session-context";
import "./page.module.css";

type AdapterConfiguration={mode?:string;provider?:string;realUscEnabled?:boolean;sourceChainId?:number;sourceChainKey?:number;targetChainId?:number;blockProver?:string;note?:string;signerCustody?:boolean;assetExecutionAuthorized?:boolean};
type ReliabilityHealth={circuitState?:string;consecutiveFailures?:number;recentSummary?:{calls:number;successes:number;failures:number;successRate:number|null;averageDurationMilliseconds:number|null};healthVerifiedByExternalProbe?:boolean;networkProbePerformed?:boolean;assetExecutionAuthorized?:boolean};
type Health={adapter?:Record<string,unknown>;reliability?:ReliabilityHealth;assetExecutionAuthorized?:boolean};
type SourceChainStatus={observedOnChain:boolean;targetChainId:number;chainInfoPrecompile:string;expectedSourceChainId:number;expectedSourceChainKey:number;sourceSupported:boolean;supportedChains:Array<{chainKey:number;chainId:number;chainName:string;chainEncoding:number}>;selected?:{chainKey:number;chainId:number;chainName:string;latestAttestedHeight:number;latestAttestedHash:string;latestAttestationExists:boolean}|null;observedAt?:string|null;assetExecutionAuthorized:false};
type ProofJob={id:string;adapter:string;sourceChainId:number;sourceChainKey:number;sourceTransactionHash:string;requesterWallet:string;status:string;sourceSnapshotHash?:string|null;proofSnapshotHash?:string|null;verificationRequestHash?:string|null;verificationTransactionHash?:string|null;verificationReceiptHash?:string|null;evidenceId?:string|null;lastErrorCode?:string|null;createdAt?:string;updatedAt?:string};
const short=(value?:string|null)=>value?`${value.slice(0,10)}…${value.slice(-8)}`:"—";
const message=(cause:unknown)=>cause instanceof ApiError?`${cause.message}${cause.requestId?` / Request ${cause.requestId}`:""}`:cause instanceof Error?cause.message:"Unable to read Attestcoin state.";

export default function AttestcoinPage(){
 const auth=useSession();const organizationId=auth.session?.activeOrganizationId;const[configuration,setConfiguration]=useState<AdapterConfiguration|null>(null),[health,setHealth]=useState<Health|null>(null),[sourceChains,setSourceChains]=useState<SourceChainStatus|null>(null),[jobs,setJobs]=useState<ProofJob[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{if(!organizationId)return;setLoading(true);setError("");try{const[config,nextHealth,nextSourceChains,nextJobs]=await Promise.all([auth.request<AdapterConfiguration>("/attestcoin/configuration"),auth.request<Health>("/attestcoin/health"),auth.request<SourceChainStatus>("/attestcoin/source-chains"),auth.request<{items:ProofJob[]}>("/attestcoin/proof-jobs")]);setConfiguration(config);setHealth(nextHealth);setSourceChains(nextSourceChains);setJobs(nextJobs.items)}catch(cause){setError(message(cause))}finally{setLoading(false)}},[auth,organizationId]);
 useEffect(()=>{void load()},[load]);
 const reliability=health?.reliability,calls=reliability?.recentSummary;
 return <MvpDemoPage kicker="DECENTRALIZED TRUST EVIDENCE INFRASTRUCTURE" title="Attestcoin Oracle Operations" summary="Trace cross-chain source receipts, USC proof construction, Creditcoin verification and deterministic routing into the eight-Agent committee and governed RAG." mode={configuration?.mode==="usc"?"USC ADAPTER / READ ONLY":"MOCK ADAPTER / READ ONLY"} primaryHref="/evidence" primaryLabel="Open Evidence Explorer" flow={["Source query frozen","Receipt confirmed","USC proof verified","Evidence normalized","Classified and routed","Committee revision available"]} panels={[{title:"Oracle Action Stream",status:"PIPELINE READY",body:"Every external action is visible as a bounded read/proof operation with immutable correlation and no signer capability.",facts:["Ethereum source receipt / confirmation bound","Creditcoin testnet observation / chain 102031","Provider timeout and circuit state recorded"]},{title:"Eight-Agent Routing",status:"8 ROLES",body:"Navigation labels route verified facts without changing proof truth.",facts:["Liquidity → Quant, Risk, Treasury","Governance → Governor, Compliance","Protocol → Research, Strategy","Treasury → Portfolio, Treasury"]},{title:"Reverse Evidence Requests",status:"FAIL CLOSED",body:"Agents can ask the Evidence Broker for missing facts; they cannot directly call arbitrary networks.",facts:["Server-derived requester role","Bounded chain/address/block fields","Child Decision reruns all eight roles"]},{title:"RAG Dispatch",status:"IMMUTABLE",body:"Verified Evidence and approved knowledge are frozen into role-scoped retrieval manifests.",facts:["organization_id ACL enforced","Stable citation and content hashes","Injection content remains untrusted data"]}]}>
  <section className="attestcoin-live" aria-labelledby="attestcoin-live-title">
   <header><div><span className="terminal-kicker">AUTHENTICATED ORGANIZATION READ MODEL</span><h2 id="attestcoin-live-title">Observed Attestcoin State</h2></div><button type="button" onClick={()=>void load()} disabled={!organizationId||loading}>{loading?"REFRESHING":"REFRESH READ MODEL"}</button></header>
   {auth.phase==="checking"?<p className="attestcoin-state">Checking the HttpOnly organization session…</p>:!auth.session?<p className="attestcoin-state"><strong>SIWE SESSION REQUIRED</strong><span>Use the enterprise security panel to authenticate. No wallet signature is requested by this read panel.</span></p>:!organizationId?<p className="attestcoin-state"><strong>DAO WORKSPACE REQUIRED</strong><span>Select an organization. Tenant scope remains server-session controlled and is never supplied by this page.</span></p>:error?<p className="attestcoin-state attestcoin-error" role="alert"><strong>READ MODEL UNAVAILABLE</strong><span>{error}</span></p>:<>
    <div className="attestcoin-live-metrics"><div><small>ADAPTER</small><b>{configuration?.provider??"READING"}</b><span>{configuration?.mode==="usc"?"USC CONFIGURED":"MOCK ONLY"}</span></div><div><small>CIRCUIT</small><b>{reliability?.circuitState??"UNKNOWN"}</b><span>{reliability?.networkProbePerformed?"NETWORK PROBED":"NO EXTERNAL PROBE"}</span></div><div><small>RECENT CALLS</small><b>{calls?.calls??0}</b><span>{calls?.successRate==null?"NO SAMPLE":`${Math.round(calls.successRate*100)}% SUCCESS`}</span></div><div><small>PROOF JOBS</small><b>{jobs.length}</b><span>ACTIVE ORGANIZATION ONLY</span></div><div><small>AUTHORITY</small><b>WITHHELD</b><span>NO SIGNER / NO BROADCAST</span></div></div>
    <div className="attestcoin-source-line"><span>SOURCE CHAIN <b>{configuration?.sourceChainId??"NOT CONFIGURED"}</b></span><i>→</i><span>CHAIN KEY <b>{configuration?.sourceChainKey??"—"}</b></span><i>→</i><span>TARGET CHAIN <b>{configuration?.targetChainId??"NOT CONFIGURED"}</b></span><i>→</i><span>BLOCK PROVER <b title={configuration?.blockProver}>{short(configuration?.blockProver)}</b></span></div>
    <div className="attestcoin-chain-readback"><div><small>CHAININFO READBACK</small><b>{sourceChains?.observedOnChain?"OBSERVED ON CREDITCOIN":"NOT OBSERVED / MOCK"}</b><span>{sourceChains?.sourceSupported?"CONFIGURED SOURCE SUPPORTED":"LIVE SUPPORT NOT ESTABLISHED"}</span></div><div><small>SELECTED SOURCE</small><b>{sourceChains?.selected?`${sourceChains.selected.chainName} / ${sourceChains.selected.chainId}`:"—"}</b><span>KEY {sourceChains?.selected?.chainKey??configuration?.sourceChainKey??"—"}</span></div><div><small>LATEST ATTESTED HEIGHT</small><b>{sourceChains?.selected?.latestAttestedHeight?.toLocaleString("en-US")??"—"}</b><span title={sourceChains?.selected?.latestAttestedHash}>{short(sourceChains?.selected?.latestAttestedHash)}</span></div><div><small>SUPPORTED SOURCES</small><b>{sourceChains?.supportedChains.length??0}</b><span>{sourceChains?.supportedChains.map(chain=>`${chain.chainName} [${chain.chainKey}]`).join(" · ")||"NO LIVE LIST"}</span></div></div>
    {configuration?.note&&<p className="attestcoin-note">MOCK ADAPTER NOTICE / {configuration.note}</p>}
    {!jobs.length?<p className="attestcoin-state"><strong>NO PROOF JOBS FOR THIS ORGANIZATION</strong><span>The read model is connected. Create/advance operations remain separate authenticated human commands and are not exposed here.</span></p>:<div className="attestcoin-job-list" role="table" aria-label="Organization Attestcoin proof jobs"><div role="row" className="attestcoin-job-head"><span role="columnheader">STATUS</span><span role="columnheader">SOURCE TRANSACTION</span><span role="columnheader">PROOF</span><span role="columnheader">VERIFICATION</span><span role="columnheader">EVIDENCE</span><span role="columnheader">UPDATED</span></div>{jobs.map(job=><div role="row" key={job.id}><span role="cell" data-status={job.status}><b>{job.status}</b>{job.lastErrorCode&&<small>{job.lastErrorCode}</small>}</span><code role="cell" title={job.sourceTransactionHash}>{short(job.sourceTransactionHash)}</code><code role="cell" title={job.proofSnapshotHash??undefined}>{short(job.proofSnapshotHash)}</code><code role="cell" title={job.verificationReceiptHash??undefined}>{short(job.verificationReceiptHash)}</code><code role="cell" title={job.evidenceId??undefined}>{short(job.evidenceId)}</code><time role="cell" dateTime={job.updatedAt}>{job.updatedAt?new Date(job.updatedAt).toLocaleString("en-US"):"—"}</time></div>)}</div>}
   </>}
   <footer>Server session resolves organization_id · ChainInfo support is read from Creditcoin, never inferred from labels · configuration/health/source chains/jobs are read only · assetExecutionAuthorized=false</footer>
  </section>
 </MvpDemoPage>
}
