import Link from "next/link";

type VerificationItem={id:string;layer:string;title:string;status:"PUBLIC CHAIN"|"PUBLIC ARTIFACT"|"TENANT RECORD"|"LOCAL E2E";reference:string;href:string;external?:boolean;proves:string;limit:string};

const items:readonly VerificationItem[]=[
 {id:"01",layer:"SOURCE",title:"Sepolia observation",status:"PUBLIC CHAIN",reference:"0xf035fdf437b434629087abf81bdf4100997c45e95f97ce8b945985f33291abab",href:"https://sepolia.etherscan.io/tx/0xf035fdf437b434629087abf81bdf4100997c45e95f97ce8b945985f33291abab",external:true,proves:"Canonical inclusion of the project-owned source observation.",limit:"Does not prove economic accuracy, liquidity or authority."},
 {id:"02",layer:"ATTESTCOIN",title:"Frozen USC proof",status:"PUBLIC ARTIFACT",reference:"step-4-usc-proof-retry-1.json",href:"https://github.com/vivayang911/AEOS/blob/main/reports/live-demo/step-4-usc-proof-retry-1.json",external:true,proves:"The exact Merkle/continuity proof bundle and hashes are inspectable.",limit:"A local artifact alone is not Creditcoin finality."},
 {id:"03",layer:"CREDITCOIN",title:"TransactionVerified",status:"PUBLIC CHAIN",reference:"0x1011f237c21733a59472b82c7a14c01e79d99e23ffb3fba1ce4905655a4fb860",href:"https://creditcoin-testnet.blockscout.com/tx/0x1011f237c21733a59472b82c7a14c01e79d99e23ffb3fba1ce4905655a4fb860",external:true,proves:"BlockProver accepted the frozen source-transaction inclusion proof.",limit:"Transaction inclusion is not independent economic truth."},
 {id:"04",layer:"EVIDENCE",title:"Immutable tenant Evidence",status:"TENANT RECORD",reference:"ev_aa0b5dbc6fdf431aa6d9f20789c160bf",href:"/evidence/ev_aa0b5dbc6fdf431aa6d9f20789c160bf",proves:"Normalized Evidence is bound to the server-selected organization under RLS.",limit:"A verified but stale record cannot silently authorize action."},
 {id:"05",layer:"DECISION",title:"Eight-role cited Decision",status:"TENANT RECORD",reference:"decision_a9a37c5bd3ff43c68f5b0af32a13b8ed",href:"/decisions?decision=decision_a9a37c5bd3ff43c68f5b0af32a13b8ed",proves:"Exactly eight formal roles froze Evidence/RAG citations and returned HOLD.",limit:"AI advice is not a vote, signature, broadcast or asset authority."},
 {id:"06",layer:"ASC",title:"EvidenceAnchorASC",status:"PUBLIC CHAIN",reference:"0x5DE85313c5622e3707C3fED8932F51e5991e62C2",href:"https://creditcoin-testnet.blockscout.com/address/0x5DE85313c5622e3707C3fED8932F51e5991e62C2",external:true,proves:"The project-owned ASC deployment and runtime are publicly inspectable.",limit:"Deployment does not prove a Decision was anchored."},
 {id:"07",layer:"ASC",title:"EvidenceAnchored",status:"PUBLIC CHAIN",reference:"0x181ab1d51085f845b76cdc5c4971622f550dafd33ed2e501dcc6c284c8bb9731",href:"https://creditcoin-testnet.blockscout.com/tx/0x181ab1d51085f845b76cdc5c4971622f550dafd33ed2e501dcc6c284c8bb9731",external:true,proves:"The exact Decision/Snapshot commitment reached canonical finality.",limit:"An anchored recommendation is not economically correct or executable."},
 {id:"08",layer:"GOVERNANCE",title:"Decision-bound Proposal",status:"PUBLIC CHAIN",reference:"0x60ae201fd9deefac70931f6968cc02bb2e6196572c4c24fefaaef592c096211e",href:"https://creditcoin-testnet.blockscout.com/tx/0x60ae201fd9deefac70931f6968cc02bb2e6196572c4c24fefaaef592c096211e",external:true,proves:"Attempt 3 created the frozen HOLD Proposal identity.",limit:"Proposal creation is not quorum or execution."},
 {id:"09",layer:"GOVERNANCE",title:"For vote and quorum",status:"PUBLIC CHAIN",reference:"0x82428c71a329ccf18951d4b11d7db0ee2bbf7ad5ba36fe328626d1d2c543a8c9",href:"https://creditcoin-testnet.blockscout.com/tx/0x82428c71a329ccf18951d4b11d7db0ee2bbf7ad5ba36fe328626d1d2c543a8c9",external:true,proves:"One million For votes exceeded the forty-thousand quorum.",limit:"AI did not cast or control the vote."},
 {id:"10",layer:"TIMELOCK",title:"Queue",status:"PUBLIC CHAIN",reference:"0x3ce62447b836bec8ed450f77964cfa6b54b4a9255f09fa86bf260094e6e1bfc5",href:"https://creditcoin-testnet.blockscout.com/tx/0x3ce62447b836bec8ed450f77964cfa6b54b4a9255f09fa86bf260094e6e1bfc5",external:true,proves:"The successful Proposal entered the configured Timelock path.",limit:"Queued calldata is not yet executed."},
 {id:"11",layer:"GUARD",title:"Zero-value Execute",status:"PUBLIC CHAIN",reference:"0xeecd79baabd81d23000ef36791384c1919615d8c4a609fc8215819c970c01160",href:"https://creditcoin-testnet.blockscout.com/tx/0xeecd79baabd81d23000ef36791384c1919615d8c4a609fc8215819c970c01160",external:true,proves:"Governor/Timelock executed deterministic withholding and kept the Guard paused.",limit:"No asset moved and no economic benefit or causality is established."},
 {id:"12",layer:"OUTCOME",title:"Outcome Evidence",status:"PUBLIC ARTIFACT",reference:"govout_ef291722a8cb069e4fe75fe1abe2936e",href:"https://github.com/vivayang911/AEOS/blob/main/reports/live-demo/p0-1-governance-hold-attempt-3-outcome-evidence-import.json",external:true,proves:"The withholding result is linked back to Decision, Snapshot and Evidence.",limit:"It is not automatic learning or approval for future actions."},
 {id:"13",layer:"BROWSER",title:"P0-3 continuous E2E",status:"LOCAL E2E",reference:"77.356s / 114.719s / 15.485s",href:"https://github.com/vivayang911/AEOS/blob/main/reports/testing/p0-3-real-browser-acceptance-2026-08-27.md",external:true,proves:"Three Chrome runs traversed the normal route with API and refresh recovery.",limit:"Local E2E is not staging or production availability."},
 {id:"14",layer:"PROJECTION",title:"Tenant chain-finality Proposal",status:"TENANT RECORD",reference:"govproposal_373660b9f448b74b8d852ba7e82b706a",href:"/governance",proves:"The accepted HOLD sample projects its canonical Decision, Snapshot, Outcome and four governance transactions into one immutable organization-scoped Proposal row.",limit:"One accepted projection does not prove generic indexing, reorg recovery or production availability."},
] as const;

const statusSummary=[["14","INDEXED CHECKS"],["8","FORMAL AGENTS"],["3","BROWSER RUNS"],["0","ASSET ACTIONS"]] as const;

export default function VerificationIndex(){return <section className="verification-index"><header className="verification-hero"><div><span>JUDGE VERIFICATION INDEX / EVIDENCE FIRST</span><h1>Verify the claims. Inspect the limits.</h1><p>A compact index of the accepted testnet lineage, immutable AEOS records and bounded local browser acceptance. This page performs no API write, RPC request, wallet request, signature or broadcast.</p></div><Link href="/dashboard">OPEN ONE-CLICK REPLAY →</Link></header><section className="verification-summary" aria-label="Verification summary">{statusSummary.map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><aside className="verification-boundary"><strong>AUTHORITY BOUNDARY</strong><span>AI + PID + RAG + Skills may advise. Human/DAO governance remains the only transaction authority.</span><b>ASSET EXECUTION AUTHORIZED / false</b></aside><div className="verification-table" role="table" aria-label="Judge-verifiable evidence index"><div className="verification-head" role="row"><span role="columnheader"># / LAYER</span><span role="columnheader">CLAIM / REFERENCE</span><span role="columnheader">PROVES</span><span role="columnheader">DOES NOT PROVE</span><span role="columnheader">SOURCE</span></div>{items.map(item=><article role="row" key={item.id}><span role="cell"><b>{item.id}</b><small>{item.layer}</small><i data-status={item.status}>{item.status}</i></span><span role="cell"><strong>{item.title}</strong><code title={item.reference}>{item.reference}</code></span><span role="cell" className="verification-proves">{item.proves}</span><span role="cell" className="verification-limit">{item.limit}</span><span role="cell">{item.external?<a href={item.href} target="_blank" rel="noreferrer">VERIFY ↗</a>:<Link href={item.href}>OPEN →</Link>}</span></article>)}</div><footer className="verification-footer"><p><strong>Honest scope:</strong> P0-3 and the accepted sample's tenant Proposal projection are locally accepted. The whole PRD remains partial. Current price/liquidity/authorization Evidence, generic indexing and reorg recovery, a genuinely second source chain, staging/production E2E, independent audit and economic-performance proof remain open.</p><Link href="/governance">VIEW ACCEPTED OUTCOME →</Link></footer></section>}
