"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import styles from "./page.module.css";
import {ApiError,useSession} from "../ui/session-context";

type Evidence={id:string;predicate:string;freshness:string;qualityScore:number};
type Position={role:string;position:string;citations:string[];knowledgeCitations?:string[];retrievalManifestHash?:string;retrievalStatus?:string;toolPermissions:string[];runState:string;attempts:number};
type Claim={text:string;materiality:string;evidenceIds:string[];confidence:number};
type Challenge={code:string;raisedBy:string;targetRole:string;challenge:string;response:string;status:"RESOLVED"|"UNRESOLVED"};
type Recommendation={recommendation:"HOLD"|"INSUFFICIENT_EVIDENCE";claims:Claim[];risks:{severity:string;code:string;description:string}[];actions:unknown[];citationCoverage:{materialClaims:number;citedMaterialClaims:number;coverage:number};unresolvedDisagreements:number;challenges:Challenge[];agentPositions:Position[];orchestration:{budget:{agentRunsUsed:number;maxAgentRuns:number;toolCallsUsed:number;maxToolCalls:number}};humanApprovalRequired:boolean;assetExecutionAuthorized:boolean};
type RetrievalItem={citation:string;partition:string;heading:string;contentHash:string;score:number};
type RetrievalManifest={id:string;role:string;query:string;query_hash:string;status:string;reason_code:string|null;items:RetrievalItem[];manifest_hash:string};
type Decision={id:string;status:string;evidenceManifestHash:string;policyVersionId:string;outputHash:string;retrievalBundleHash:string;retrievalManifests:RetrievalManifest[];recommendation:Recommendation};
type DecisionSummary={id:string;status:string;objective:string;recommendation:string;actionCount:number;evidenceSnapshotId:string;evidenceManifestHash:string;outputHash:string;createdAt:string;reviewedAt:string|null;assetExecutionAuthorized:false};
type Job={jobId:string;status:"QUEUED"|"RUNNING"|"COMPLETED"|"FAILED"|"TIMED_OUT";currentStage:string;progress:number;attempts:number;maxAttempts:number;lastErrorCode:string|null;decision?:Decision};
type Provider={providerId:string;modelVersion:string;kind:string;credentialsRequired:boolean;allowedTools:string[];assetExecutionTools:string[]};
const commandRoles=new Set(["ADMIN","TREASURY_COMMITTEE","REVIEWER"]);
const message=(cause:unknown)=>cause instanceof ApiError?`${cause.message}${cause.requestId?` / Request ${cause.requestId}`:""}`:cause instanceof Error?cause.message:"Request failed.";

export default function DecisionRoom(){
 const auth=useSession(),org=auth.session?.activeOrganizationId,role=auth.session?.role??"",canCommand=commandRoles.has(role);
 const[evidence,setEvidence]=useState<Evidence[]>([]),[history,setHistory]=useState<DecisionSummary[]>([]),[provider,setProvider]=useState<Provider>(),[selected,setSelected]=useState<string[]>([]),[objective,setObjective]=useState("Using the current verified asset Evidence, assess whether treasury assets should remain unchanged and be submitted for DAO human review."),[job,setJob]=useState<Job>(),[decision,setDecision]=useState<Decision>(),[rationale,setRationale]=useState("I reviewed the frozen Evidence, material-claim citations, Agent dissent and deterministic guardrails."),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const active=job?.status==="QUEUED"||job?.status==="RUNNING";
 const loadDecision=useCallback(async(id:string)=>{setBusy(true);setError("");try{const detail=await auth.request<Decision>(`/decisions/${encodeURIComponent(id)}`);setDecision(detail);setJob(undefined);setNotice("");window.history.replaceState(null,"",`/decisions?decision=${encodeURIComponent(id)}`)}catch(cause){setError(message(cause))}finally{setBusy(false)}},[auth]);
 const load=useCallback(async()=>{if(!org)return;setError("");try{const[e,p,h]=await Promise.all([auth.request<{items:Evidence[]}>('/evidence?status=VERIFIED&limit=100'),auth.request<Provider>('/advisory-provider'),auth.request<{items:DecisionSummary[];nextCursor:string|null}>('/decisions?limit=50')]);setEvidence(e.items);setProvider(p);setHistory(h.items);setSelected([]);const requested=new URLSearchParams(window.location.search).get("decision"),target=requested??h.items[0]?.id;if(target){const detail=await auth.request<Decision>(`/decisions/${encodeURIComponent(target)}`);setDecision(detail)}}catch(cause){setError(message(cause))}},[auth,org]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!active||!job)return;let cancelled=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await auth.request<Job>(`/decision-jobs/${job.jobId}`);if(cancelled)return;setJob(next);if(next.decision)setDecision(next.decision);if(next.status==="FAILED"||next.status==="TIMED_OUT")setError(`Analysis stopped: ${next.lastErrorCode??next.status}`);else if(next.status!=="COMPLETED")timer=setTimeout(poll,650)}catch(cause){if(!cancelled){setError(message(cause));timer=setTimeout(poll,1600)}}};timer=setTimeout(poll,250);return()=>{cancelled=true;clearTimeout(timer)}},[active,auth,job?.jobId]);
 const run=async()=>{setBusy(true);setError("");setNotice("");setDecision(undefined);try{const next=await auth.request<Job>('/decisions',{method:'POST',csrf:true,headers:{'idempotency-key':`web-decision-${crypto.randomUUID()}`},body:JSON.stringify({objective:objective.trim(),evidenceIds:selected})});setJob(next);setNotice('Analysis inputs are frozen and the persisted Agent committee job is queued.')}catch(cause){setError(message(cause))}finally{setBusy(false)}};
 const retry=async()=>{if(!job)return;setBusy(true);setError("");try{setJob(await auth.request<Job>(`/decision-jobs/${job.jobId}/retry`,{method:'POST',csrf:true,headers:{'idempotency-key':`web-retry-${crypto.randomUUID()}`},body:'{}'}))}catch(cause){setError(message(cause))}finally{setBusy(false)}};
 const review=async(outcome:"APPROVED"|"REJECTED")=>{if(!decision)return;setBusy(true);setError("");try{const result=await auth.request<{status:string;assetExecutionAuthorized:boolean}>(`/decisions/${decision.id}/review`,{method:'POST',csrf:true,headers:{'idempotency-key':`web-review-${crypto.randomUUID()}`},body:JSON.stringify({rationale:rationale.trim(),outcome})});setDecision({...decision,status:result.status});setHistory(items=>items.map(item=>item.id===decision.id?{...item,status:result.status,reviewedAt:new Date().toISOString()}:item));setNotice(`Human review recorded. Asset execution authority remains ${String(result.assetExecutionAuthorized)}.`)}catch(cause){setError(message(cause))}finally{setBusy(false)}};
 if(auth.phase==="checking")return <section className={styles.gate}><span className="section-kicker">SESSION CHECK</span><h1>Verifying organization session</h1><p>Decision Room resolves organization_id only from the server session.</p></section>;
 if(!auth.session)return <section className={styles.gate}><span className="section-kicker">PHASE 2 / AUTH REQUIRED</span><h1>Agent Decision Room</h1><p>SIWE authenticates identity only. It grants no transaction, governance vote or asset authority.</p><button className="primary-action" onClick={()=>void auth.connectWallet()}>Connect wallet and sign in</button>{auth.error&&<p role="alert">{auth.error}</p>}</section>;
 if(!org)return <section className={styles.gate}><span className="section-kicker">ORGANIZATION REQUIRED</span><h1>Select a DAO workspace</h1><p>Evidence, Decisions and human reviews must share one server-resolved tenant boundary.</p><p className={styles.warning}>No x-organization-id / no client-trusted actor / cross-tenant objects return 404</p></section>;
 return <div className={styles.page}>
  <header className={styles.hero}><div><span className="section-kicker">PHASE 2 / AGENT DECISION ROOM</span><h1>Evidence before conclusions</h1><p>Freeze verified Evidence and let eight professional Agents produce cited, challengeable advice. Final authority remains with the DAO.</p></div><aside><span>ADVISORY BOUNDARY</span><strong>AI generates advice only</strong><small>human review required / execution withheld</small></aside></header>
  <section className={styles.provider}><div><b>MOCK ADAPTER</b><strong>{provider?.providerId??"Loading"}</strong><small>{provider?.modelVersion??"-"} / {provider?.kind??"-"}</small></div><dl><div><dt>Credentials</dt><dd>{provider?.credentialsRequired?"Required":"Not required"}</dd></div><div><dt>Allowed tools</dt><dd>{provider?.allowedTools.join(" / ")||"Read only"}</dd></div><div><dt>Asset tools</dt><dd>{provider?.assetExecutionTools.length?provider.assetExecutionTools.join(" / "):"NONE"}</dd></div></dl></section>
  <section className={styles.panel}><div className={styles.head}><div><span className="section-kicker">00 / IMMUTABLE DECISION HISTORY</span><h2>Open an existing Decision</h2></div><em>{history.length} tenant-scoped records</em></div><p className={styles.historyNote}>Select a frozen Decision to inspect its Evidence, eight-Agent output and append-only review state. Historical records are read from the active server-side organization session.</p><div className={styles.history}>{history.map(item=><button type="button" key={item.id} data-active={decision?.id===item.id} onClick={()=>void loadDecision(item.id)} disabled={busy}><span><b>{item.recommendation}</b><em>{item.status}</em></span><strong>{item.objective}</strong><code>{item.id}</code><small>{new Date(item.createdAt).toLocaleString()} / actions {item.actionCount} / execution authority false</small></button>)}</div>{!history.length&&<p className={styles.empty}>No Decisions exist in this organization. A new analysis requires VERIFIED Evidence.</p>}</section>
  <section className={styles.panel}><div className={styles.head}><div><span className="section-kicker">01 / FREEZE INPUT</span><h2>Start analysis job</h2></div><em>{selected.length} Evidence records</em></div><label className={styles.objective}>Analysis objective<textarea rows={4} minLength={3} maxLength={2000} value={objective} onChange={e=>setObjective(e.target.value)}/></label><div className={styles.evidence}>{evidence.map(item=><label key={item.id} data-selected={selected.includes(item.id)}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><span><strong>{item.predicate}</strong><small>{item.id}</small></span><em>{item.freshness} / Q{item.qualityScore}</em></label>)}</div>{!evidence.length&&<p className={styles.empty}>This organization has no VERIFIED Evidence. Ingest and verify Evidence in Evidence Explorer first.</p>}<footer className={styles.command}><span>{canCommand?`${role} may submit analysis`:`${role} is read only`}</span><button className="primary-action" disabled={!canCommand||!auth.canMutate||busy||active||!selected.length||objective.trim().length<3} onClick={()=>void run()}>{active?"Agent committee running...":"Freeze Evidence and run committee"}</button></footer></section>
  {!auth.canMutate&&<p className={styles.warning}>Writes require SIWE re-authentication to restore the in-memory CSRF token.</p>}{error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
  {job&&<section className={styles.panel} aria-live="polite"><div className={styles.head}><div><span className="section-kicker">02 / PERSISTED ORCHESTRATION</span><h2>{job.status}</h2></div><strong>{job.progress}%</strong></div><progress max={100} value={job.progress}/><p>{job.currentStage} / attempt {job.attempts}/{job.maxAttempts} / {job.jobId}</p>{(job.status==="FAILED"||job.status==="TIMED_OUT")&&job.attempts<job.maxAttempts&&canCommand&&<button disabled={busy||!auth.canMutate} onClick={()=>void retry()}>Retry within budget</button>}</section>}
  {decision&&<section className={styles.panel}><div className={styles.resultHead}><div><span className="section-kicker">03 / DETERMINISTIC REVIEW GATE</span><h2>{decision.recommendation.recommendation==="HOLD"?"Hold treasury assets":"Insufficient Evidence for high-impact advice"}</h2></div><b>{decision.status}</b></div><div className={styles.hashes}><span>Snapshot <code>{decision.evidenceManifestHash}</code></span><span>RAG bundle <code>{decision.retrievalBundleHash}</code></span><span>Policy <code>{decision.policyVersionId}</code></span><span>Output <code>{decision.outputHash}</code></span></div><div className={styles.metrics}><article><span>Citation coverage</span><strong>{Math.round(decision.recommendation.citationCoverage.coverage*100)}%</strong><small>{decision.recommendation.citationCoverage.citedMaterialClaims}/{decision.recommendation.citationCoverage.materialClaims} material claims</small></article><article><span>Unresolved dissent</span><strong>{decision.recommendation.unresolvedDisagreements}</strong><small>Unresolved items force refusal</small></article><article><span>Agent budget</span><strong>{decision.recommendation.orchestration.budget.agentRunsUsed}/{decision.recommendation.orchestration.budget.maxAgentRuns}</strong><small>{decision.recommendation.orchestration.budget.toolCallsUsed}/{decision.recommendation.orchestration.budget.maxToolCalls} tool calls</small></article></div>
   <div className={styles.columns}><section><h3>Material claims and Evidence citations</h3>{decision.recommendation.claims.map((claim,i)=><article className={styles.item} key={i}><span>{claim.materiality} / confidence {Math.round(claim.confidence*100)}%</span><p>{claim.text}</p><div>{claim.evidenceIds.map(id=><Link key={id} href={`/evidence/${id}`}>{id}</Link>)}</div></article>)}</section><section><h3>Challenges, risks and dissent</h3>{decision.recommendation.challenges.map(c=><article className={styles.item} key={c.code}><span>{c.status}</span><strong>{c.raisedBy} to {c.targetRole}</strong><p>{c.challenge}</p><small>{c.response}</small></article>)}{decision.recommendation.risks.map(r=><p className={styles.risk} key={r.code}>{r.severity} / {r.code} / {r.description}</p>)}</section></div>
   <h3>Agent positions</h3><div className={styles.agents}>{decision.recommendation.agentPositions.map(p=><article key={p.role}><div><strong>{p.role}</strong><span>{p.runState} / attempt {p.attempts}</span></div><p>{p.position}</p><div>{p.citations.map(id=><Link key={id} href={`/evidence/${id}`}>{id}</Link>)}</div>{p.knowledgeCitations?.length?<div className={styles.ragCitations}>{p.knowledgeCitations.map(citation=><code key={citation}>{citation}</code>)}</div>:<em className={styles.noContext}>INSUFFICIENT_CONTEXT</em>}<small>RAG / {p.retrievalStatus??"UNAVAILABLE"} / {p.retrievalManifestHash??"no manifest"}</small><small>TOOLS / {p.toolPermissions.join(" / ")}</small></article>)}</div>
   <h3>Frozen role-scoped Retrieval Manifests</h3><div className={styles.manifests}>{decision.retrievalManifests.map(manifest=><article key={manifest.id}><header><strong>{manifest.role}</strong><span>{manifest.status} / {manifest.items.length} citations</span></header><p>{manifest.query}</p><code>{manifest.manifest_hash}</code><ul>{manifest.items.map(item=><li key={item.citation}><b>{item.partition}</b><span>{item.heading}</span><code>{item.citation}</code></li>)}</ul></article>)}</div>
   {decision.status==="REVIEW_REQUIRED"&&<aside className={styles.review}><div><span className="section-kicker">DAO IN CONTROL</span><h3>Human review grants no asset authority</h3><p>It records approval or rejection of an immutable Decision only. It never signs or broadcasts a transaction.</p></div><div><label>Review rationale<textarea rows={3} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><p><button disabled={!canCommand||!auth.canMutate||busy||rationale.trim().length<3||decision.recommendation.recommendation!=="HOLD"} onClick={()=>void review("APPROVED")}>Approve advice record</button><button disabled={!canCommand||!auth.canMutate||busy||rationale.trim().length<3} onClick={()=>void review("REJECTED")}>Reject</button></p></div></aside>}
   <footer className={styles.execution}><span>HUMAN APPROVAL REQUIRED / {String(decision.recommendation.humanApprovalRequired)}</span><strong>ASSET EXECUTION AUTHORIZED / {String(decision.recommendation.assetExecutionAuthorized)}</strong><small>Actions: {decision.recommendation.actions.length} / no signature / no broadcast</small></footer>
  </section>}
 </div>
}
