"use client";
import {useCallback,useEffect,useState} from "react";
import {useSession} from "../ui/session-context";
type Proposal={id:string;decisionId:string;effectiveState:string;title:string;contentHash:string;calldataHash:string;recordSource:"DRAFT"|"CHAIN_FINALITY";onchainFinalityVerified:boolean;assetExecutionAuthorized:false};
const short=(value:string)=>value.length>22?`${value.slice(0,12)}…${value.slice(-8)}`:value;
export default function GovernancePage(){
 const auth=useSession();const[proposals,setProposals]=useState<Proposal[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const organizationId=auth.session?.activeOrganizationId;
 const load=useCallback(async()=>{if(!organizationId)return;setLoading(true);setError("");try{const result=await auth.request<{items:Proposal[]}>("/proposals");setProposals(result.items)}catch(cause){setError(cause instanceof Error?cause.message:"Governance read failed")}finally{setLoading(false)}},[auth.request,organizationId]);
 useEffect(()=>{void load()},[load]);
 return <div className="governance-e2e"><header><span className="section-kicker">US-06 / DAO AUTHORIZATION / READ ONLY</span><h1>Governance Command Center</h1><p>Observe the accepted Decision-bound HOLD lifecycle. AEOS exposes finality and lineage but provides no vote, Queue, Execute, signer or broadcast control.</p><button type="button" onClick={()=>void load()} disabled={!organizationId||loading}>{loading?"REFRESHING":"REFRESH TENANT RECORDS"}</button></header>
 {!auth.session?<p className="e2e-gate"><strong>SIWE SESSION REQUIRED</strong><span>Return to Landing and verify the governance signer.</span></p>:!organizationId?<p className="e2e-gate"><strong>ORGANIZATION REQUIRED</strong><span>Select the DAO workspace before reading governance records.</span></p>:error?<p className="e2e-gate error" role="alert"><strong>GOVERNANCE READ UNAVAILABLE</strong><span>{error}</span></p>:<><section className="governance-timeline" aria-label="Accepted governance lifecycle">{["Decision approved","Proposal created","1,000,000 For","Quorum 40,000","Queue confirmed","Timelock 60s","Guard HOLD","Outcome frozen"].map((label,index)=><article key={label}><span>{String(index+1).padStart(2,"0")}</span><strong>{label}</strong><small>VERIFIED</small></article>)}</section><section className="governance-records"><header><h2>Organization-scoped Proposal records</h2><span>{proposals.length} visible / RLS</span></header>{proposals.slice(0,6).map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{item.effectiveState}</span></div><code>{short(item.id)}</code><small>{item.recordSource==="CHAIN_FINALITY"&&item.onchainFinalityVerified?"CANONICAL CHAIN FINALITY · ":"DRAFT READ MODEL · "}Decision {short(item.decisionId)} · content {short(item.contentHash)} · calldata {short(item.calldataHash)}</small></article>)}{!proposals.length&&<p>No organization-scoped Proposal record is available. A public replay is not substituted for a tenant query result.</p>}</section></>}
 <section id="verified-outcome" className="verified-outcome" tabIndex={-1}><div><span className="section-kicker">P0-1 / IMMUTABLE OUTCOME EVIDENCE</span><h2>Deterministic withholding executed</h2><p>Attempt 3 reached quorum, was queued, waited through the Timelock and executed the zero-value Guard HOLD. TreasuryGuard remained paused and no PolicyRegistry mutation or asset movement occurred.</p></div><dl><div><dt>Outcome lineage</dt><dd>govout_ef2917…2936</dd></div><div><dt>Outcome Evidence</dt><dd>ev_govout_fd6c…b8d6</dd></div><div><dt>Execute transaction</dt><dd>0xeecd79ba…01160</dd></div><div><dt>Authority</dt><dd>DAO + Timelock</dd></div></dl><footer><strong>ASSET EXECUTION AUTHORIZED / false</strong><span>Proves governed withholding, not economic benefit, autonomous trading or causal AI performance.</span></footer></section></div>
}
