import { AdaptivePidEnvelope, runAdaptivePid } from "./adaptive-pid-engine";
import { TreasuryPolicyConfig } from "./policy-engine";

const policy:TreasuryPolicyConfig={minimumEvidenceQuality:80,targetAllocationBps:4000,pid:{kpBps:5000,kiBps:1000,kdBps:1000,deadbandBps:25,maxAdjustmentBps:500,integralLimitBps:2000},riskLimits:{maxSingleAdjustmentBps:500,maxSlippageBps:100,minLiquidityUsd:"100000",maxDailyTurnoverUsd:"50000",allowedTargetContracts:["0x1111111111111111111111111111111111111111"],allowedFunctionSelectors:["0x12345678"]}};
const envelope:AdaptivePidEnvelope={enabled:true,kpMinBps:1000,kpMaxBps:6000,kiMinBps:0,kiMaxBps:1500,kdMinBps:0,kdMaxBps:2000,maxGainStepBps:500,derivativeFilterBps:9000,maxOutputBps:400,maxOutputRateBps:100,minimumEvidenceConfidenceBps:8500,volatileThresholdBps:300,liquidityStressThresholdBps:3000,blackSwanDeviationBps:100};
const input={observedAllocationBps:3200,previousErrorBps:750,integralErrorBps:100,previousFilteredDerivativeBpsPerDay:0,previousOutputBps:0,previousGains:{kpBps:5000,kiBps:1000,kdBps:1000},deltaTimeMs:100,evidenceEligible:true,evidenceConfidenceBps:9200,volatilityBps:100,liquidityDropBps:100,pegDeviationBps:5,criticalIncident:false};

describe("adaptive PID engine",()=>{
  it("is deterministic, bounded, advisory-only and supports millisecond samples",()=>{const first=runAdaptivePid(policy,envelope,input),second=runAdaptivePid(structuredClone(policy),structuredClone(envelope),structuredClone(input));expect(first).toEqual(second);expect(first.deltaTimeMs).toBe(100);expect(Math.abs(first.boundedOutputBps)).toBeLessThanOrEqual(100);expect(first.governedEnvelopeApplied).toBe(true);expect(first.assetExecutionAuthorized).toBe(false)});
  it("uses a defensive liquidity profile and rate-limits governed gain changes",()=>{const result=runAdaptivePid(policy,envelope,{...input,liquidityDropBps:3500});expect(result.riskRegime).toBe("LIQUIDITY_STRESS");expect(result.safetyState).toBe("DEFENSIVE");expect(result.gains.kpBps).toBe(4500);expect(result.gains.kiBps).toBe(500);expect(result.gains.kdBps).toBe(1500);expect(result.gains.desired.kiBps).toBe(0)});
  it("fails closed and freezes integral state for black swans",()=>{const result=runAdaptivePid(policy,envelope,{...input,pegDeviationBps:120,integralErrorBps:777});expect(result.safetyState).toBe("EMERGENCY_HOLD");expect(result.suggestedAdjustmentBps).toBe(0);expect(result.controllerState.integralErrorBps).toBe(777);expect(result.controllerState.integralFrozen).toBe(true);expect(result.blockers).toContain("BLACK_SWAN_HOLD")});
  it("holds when Evidence confidence is insufficient",()=>{const result=runAdaptivePid(policy,envelope,{...input,evidenceConfidenceBps:8400});expect(result.riskRegime).toBe("EVIDENCE_UNCERTAIN");expect(result.suggestedAdjustmentBps).toBe(0);expect(result.blockers).toContain("EVIDENCE_CONFIDENCE_INSUFFICIENT")});
  it("rejects envelopes outside the DAO policy hard limits",()=>{expect(()=>runAdaptivePid(policy,{...envelope,maxOutputBps:501},input)).toThrow("ADAPTIVE_OUTPUT_EXCEEDS_HARD_LIMIT");expect(()=>runAdaptivePid(policy,{...envelope,kpMaxBps:4000},input)).toThrow("BASE_PID_OUTSIDE_GOVERNED_ENVELOPE")});
});
