import { AdvisoryProviderReliabilityService } from "./advisory-provider-reliability.service";
import { AdvisoryProviderRequestError, AdvisoryProviderTimeoutError } from "./advisory-provider";

const db=()=>({query:jest.fn().mockResolvedValue({rowCount:1,rows:[]})}) as any;

describe("AdvisoryProviderReliabilityService",()=>{
  it("persists only sanitized immutable metadata on success",async()=>{const database=db();const service=new AdvisoryProviderReliabilityService(database);const output={recommendation:"HOLD",assetExecutionAuthorized:false};await expect(service.execute("org_a","agnes-ai","agnes-v1","0xinput",1000,async()=>output)).resolves.toBe(output);const [sql,values]=database.query.mock.calls[0];expect(sql).toContain("advisory_provider_observations");expect(values).toEqual(expect.arrayContaining(["org_a","agnes-ai","agnes-v1","SUCCESS","0xinput",1000]));expect(JSON.stringify(values)).not.toContain("recommendation");expect(service.configuration()).toEqual(expect.objectContaining({recommendedTimeoutMilliseconds:15000,promptOrResponseStored:false,assetExecutionAuthorized:false}))});
  it("records timeout and opens the tenant-provider circuit after three retryable failures",async()=>{const database=db();const service=new AdvisoryProviderReliabilityService(database);for(let attempt=0;attempt<3;attempt++)await expect(service.execute("org_a","agnes-ai","agnes-v1","0xinput",1000,async()=>{throw new AdvisoryProviderTimeoutError()})).rejects.toBeInstanceOf(AdvisoryProviderTimeoutError);await expect(service.execute("org_a","agnes-ai","agnes-v1","0xinput",1000,async()=>({}))).rejects.toMatchObject({response:expect.objectContaining({code:"ADVISORY_CIRCUIT_OPEN"})});expect(database.query).toHaveBeenCalledTimes(4)});
  it("does not count deterministic validation failures toward the circuit threshold",async()=>{const database=db();const service=new AdvisoryProviderReliabilityService(database);for(let attempt=0;attempt<4;attempt++)await expect(service.execute("org_a","agnes-ai","agnes-v1","0xinput",1000,async()=>{throw new Error("INVALID_OUTPUT")})).rejects.toThrow("INVALID_OUTPUT");expect(database.query.mock.calls.every((call:any)=>call[1].includes("REQUEST_FAILED"))).toBe(true)});
  it("rejects an out-of-policy timeout before any provider call",async()=>{const database=db();const work=jest.fn();await expect(new AdvisoryProviderReliabilityService(database).execute("org_a","agnes-ai","agnes-v1","0xinput",30001,work)).rejects.toThrow("ADVISORY_TIMEOUT_OUT_OF_RANGE");expect(work).not.toHaveBeenCalled();expect(database.query).not.toHaveBeenCalled()});
  it("treats bounded provider request failures as retryable circuit signals",async()=>{const database=db();const service=new AdvisoryProviderReliabilityService(database);await expect(service.execute("org_b","agnes-ai","agnes-v1","0xinput",1000,async()=>{throw new AdvisoryProviderRequestError()})).rejects.toBeInstanceOf(AdvisoryProviderRequestError);expect(database.query.mock.calls[0][1]).toEqual(expect.arrayContaining(["REQUEST_FAILED","PROVIDER_REQUEST_FAILED"]))});
});
