import { AlertService } from "./alert.service";
import { ALERT_CONSUMER } from "./alert-engine";

const source={id:"evt_audit_1",organization_id:"org_1",type:"evidence.rejected",occurred_at:"2026-08-06T00:00:00Z",actor:{type:"adapter"},object_ref:{type:"quarantine",id:"q_1"},data:{reasonCode:"INVALID_PROOF"},schema_version:"1.0",request_id:"req_1",content_hash:"0xsource"};
describe("alert lifecycle service",()=>{
  it("claims an Outbox event and atomically writes an immutable alert and receipt",async()=>{const delivery={event_id:source.id,organization_id:source.organization_id,consumer:ALERT_CONSUMER};const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[delivery]}).mockResolvedValueOnce({rowCount:1,rows:[source]}).mockResolvedValue({rowCount:1,rows:[]})};const db={runAsSystem:(work:any)=>work(),transaction:(work:any)=>work(client)} as any;const result=await new AlertService(db).processOnce();expect(result).toEqual(expect.objectContaining({status:"DELIVERED",eventId:source.id,alertId:`alert_${source.id}`,assetExecutionAuthorized:false}));expect(client.query.mock.calls[2][0]).toContain("INSERT INTO alerts");expect(client.query.mock.calls[3][0]).toContain("outbox_consumer_receipts");expect(client.query.mock.calls[4][0]).toContain("status='DELIVERED'")});
  it("consumes non-alert events without creating false positives",async()=>{const delivery={event_id:"evt_ok",organization_id:"org_1",consumer:ALERT_CONSUMER};const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[delivery]}).mockResolvedValueOnce({rowCount:1,rows:[{...source,id:"evt_ok",type:"evidence.verified"}]}).mockResolvedValue({rowCount:1,rows:[]})};const db={runAsSystem:(work:any)=>work(),transaction:(work:any)=>work(client)} as any;await expect(new AlertService(db).processOnce()).resolves.toEqual(expect.objectContaining({status:"DELIVERED",alertId:null}));expect(client.query.mock.calls.some(([sql])=>String(sql).includes("INSERT INTO alerts"))).toBe(false)});
  it("uses the active tenant and actor for append-only acknowledgement and audit",async()=>{const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{...source,id:"alert_1",content_hash:"0xalert"}]}).mockResolvedValue({rowCount:1,rows:[]})};const db={transaction:(work:any)=>work(client)} as any;const result=await new AlertService(db).acknowledge("org_1","alert_1","user_1"," reviewed ");expect(result).toEqual(expect.objectContaining({alertId:"alert_1",organizationId:"org_1",acknowledgedBy:"user_1",note:"reviewed",assetExecutionAuthorized:false}));expect(client.query.mock.calls[0][1]).toEqual(["org_1","alert_1"]);expect(client.query.mock.calls[1][0]).toContain("alert_acknowledgements");expect(client.query.mock.calls[2][0]).toContain("alert.acknowledged")});
});
