import { hashValue } from "./decision-engine";

export const ANOMALY_PRODUCER_VERSION = "aeos-anomaly-producers.v1";
export const GOVERNANCE_UNKNOWN_AFTER_SECONDS = 900;
export type AnomalyCandidate = { organizationId: string; eventType: "evidence.stale" | "proposal.state_unknown" | "organization.permission_changed" | "treasury_guard.paused"; objectType: "evidence" | "proposal" | "organization_configuration"; objectId: string; sourceFingerprint: string; details: Record<string, unknown> };
type EvidenceRow = { organization_id: string; id: string; content_hash: string; freshness_expires_at: Date | string };
type GovernanceRow = { organization_id: string; proposal_id: string; id: string; state: string; observed_at: Date | string; payload_hash: string };
type ConfigurationRow = { organization_id: string; id: string; version: number; config: Record<string, unknown>; inspection: Record<string, unknown>; content_hash: string };

export function staleEvidenceCandidate(row: EvidenceRow): AnomalyCandidate { return { organizationId: row.organization_id, eventType: "evidence.stale", objectType: "evidence", objectId: row.id, sourceFingerprint: hashValue({ rule: "EVIDENCE_EXPIRED", evidenceId: row.id, contentHash: row.content_hash, freshnessExpiresAt: new Date(row.freshness_expires_at).toISOString() }), details: { evidenceContentHash: row.content_hash, freshnessExpiresAt: new Date(row.freshness_expires_at).toISOString() } }; }
export function governanceUnknownCandidate(row: GovernanceRow): AnomalyCandidate { return { organizationId: row.organization_id, eventType: "proposal.state_unknown", objectType: "proposal", objectId: row.proposal_id, sourceFingerprint: hashValue({ rule: "GOVERNANCE_OBSERVATION_OVERDUE", proposalId: row.proposal_id, observationId: row.id, observationHash: row.payload_hash, thresholdSeconds: GOVERNANCE_UNKNOWN_AFTER_SECONDS }), details: { latestObservationId: row.id, latestObservationHash: row.payload_hash, latestState: row.state, lastObservedAt: new Date(row.observed_at).toISOString(), thresholdSeconds: GOVERNANCE_UNKNOWN_AFTER_SECONDS } }; }
const controlFields = ["governorAddress", "timelockAddress", "safeAddress", "treasuryGuardAddress"] as const;
export function permissionChangeCandidate(current: ConfigurationRow, previous: ConfigurationRow): AnomalyCandidate | null { const changedFields = controlFields.filter((field) => current.config?.[field] !== previous.config?.[field]); if (!changedFields.length) return null; return { organizationId: current.organization_id, eventType: "organization.permission_changed", objectType: "organization_configuration", objectId: current.id, sourceFingerprint: hashValue({ rule: "CONTROL_CONFIGURATION_CHANGED", currentContentHash: current.content_hash, previousContentHash: previous.content_hash, changedFields }), details: { currentVersion: current.version, previousVersion: previous.version, currentContentHash: current.content_hash, previousContentHash: previous.content_hash, changedFields } }; }
export function pausedGuardCandidate(row: ConfigurationRow): AnomalyCandidate | null { const contracts = row.inspection?.contracts; const guard = contracts && typeof contracts === "object" ? (contracts as Record<string, unknown>).treasuryGuardAddress : null; if (!guard || typeof guard !== "object" || (guard as Record<string, unknown>).paused !== true) return null; return { organizationId: row.organization_id, eventType: "treasury_guard.paused", objectType: "organization_configuration", objectId: row.id, sourceFingerprint: hashValue({ rule: "TREASURY_GUARD_PAUSED", configurationContentHash: row.content_hash, inspectionBlockHash: row.inspection.blockHash ?? null }), details: { configurationVersion: row.version, configurationContentHash: row.content_hash, inspectionBlockNumber: row.inspection.blockNumber ?? null, inspectionBlockHash: row.inspection.blockHash ?? null } }; }
export function anomalyAudit(candidate: AnomalyCandidate) { const data = { producerVersion: ANOMALY_PRODUCER_VERSION, detectedFrom: "IMMUTABLE_STORED_STATE", sourceFingerprint: candidate.sourceFingerprint, ...candidate.details, advisoryOnly: true, assetExecutionAuthorized: false }; const payload = { eventType: candidate.eventType, organizationId: candidate.organizationId, objectType: candidate.objectType, objectId: candidate.objectId, data }; const payloadHash = hashValue(payload); return { id: `audit_anomaly_${candidate.sourceFingerprint.slice(2)}`, ...payload, payloadHash, actor: { type: "system", id: "anomaly-scanner-v1" }, action: candidate.eventType }; }
