import { MiddlewareConsumer, Module, NestModule, RequestMethod } from "@nestjs/common";
import { HealthController } from "./health.controller";
import { DatabaseService } from "./database.service";
import { EvidenceController } from "./evidence.controller";
import { EvidenceService } from "./evidence.service";
import { AuditController } from "./audit.controller";
import { DecisionController, DecisionJobController } from "./decision.controller";
import { DecisionService } from "./decision.service";
import { ADVISORY_PROVIDER, createAdvisoryProviderFromEnvironment } from "./advisory-provider";
import { AdvisoryProviderController } from "./advisory-provider.controller";
import { ATTESTCOIN_ADAPTER, createAttestcoinAdapterFromEnvironment } from "./attestcoin-adapter";
import { AttestcoinController } from "./attestcoin.controller";
import { AttestcoinService } from "./attestcoin.service";
import { PolicyController, PolicyScenarioComparisonController } from "./policy.controller";
import { PolicyService } from "./policy.service";
import { ProposalController } from "./proposal.controller";
import { ProposalService } from "./proposal.service";
import { GOVERNANCE_ADAPTER, createGovernanceAdapterFromEnvironment } from "./governance-adapter";
import { GovernanceController } from "./governance.controller";
import { GovernanceService } from "./governance.service";
import { ExecutionController } from "./execution.controller";
import { ExecutionService } from "./execution.service";
import { TREASURY_GUARD_ADAPTER, createTreasuryGuardAdapterFromEnvironment } from "./treasury-guard-adapter";
import { SAFE_TRANSACTION_ADAPTER, createSafeTransactionAdapterFromEnvironment } from "./safe-transaction-adapter";
import { SafeTransactionController } from "./safe-transaction.controller";
import { SafeTransactionService } from "./safe-transaction.service";
import { OperationalHealthService } from "./operational-health.service";
import { AuthController } from "./auth.controller";
import { AuthService } from "./auth.service";
import { SessionGuard } from "./session.guard";
import { OrganizationController } from "./organization.controller";
import { OrganizationService } from "./organization.service";
import { OrganizationConfigurationController } from "./organization-configuration.controller";
import { OrganizationConfigurationService } from "./organization-configuration.service";
import { ORGANIZATION_CONFIGURATION_ADAPTER, createOrganizationConfigurationAdapterFromEnvironment } from "./organization-configuration-adapter";
import { APP_INTERCEPTOR } from "@nestjs/core";
import { IdempotencyInterceptor } from "./idempotency.interceptor";
import { RequestTraceMiddleware } from "./request-trace";
import { createOutboxPublisherFromEnvironment, OUTBOX_PUBLISHER, OutboxDispatcherService } from "./outbox-publisher";
import { OutboxPublisherController } from "./outbox-publisher.controller";
import { AlertController } from "./alert.controller";
import { AlertService } from "./alert.service";
import { AuditExportController } from "./audit-export.controller";
import { AuditExportService } from "./audit-export.service";
import { ExplorerLinkService } from "./explorer-link.service";
import { AnomalyScannerService } from "./anomaly-scanner.service";
import { AttestcoinReliabilityService } from "./attestcoin-reliability.service";
import { KnowledgeController } from "./knowledge.controller";
import { KnowledgeService } from "./knowledge.service";
import { EvidenceRequestController } from "./evidence-request.controller";
import { EvidenceRequestService } from "./evidence-request.service";
import { createEvidenceAnchorReceiptAdapterFromEnvironment, EVIDENCE_ANCHOR_RECEIPT_ADAPTER } from "./evidence-anchor-adapter";
import { TreasuryWorkflowController } from "./treasury-workflow.controller";
import { TreasuryWorkflowService } from "./treasury-workflow.service";
import { TreasuryRegistryController } from "./treasury-registry.controller";
import { TreasuryRegistryService } from "./treasury-registry.service";
import { CockpitProjectionController } from "./cockpit-projection.controller";
import { CockpitProjectionService } from "./cockpit-projection.service";
import { CockpitStreamAdmissionService } from "./cockpit-stream-admission.service";
import { CockpitProjectionNotificationService } from "./cockpit-projection-notification.service";
import { TenantContextInterceptor } from "./tenant-context.interceptor";
import { GovernedSkillController } from "./governed-skill.controller";
import { GovernedSkillService } from "./governed-skill.service";
import { TreasuryOutcomeController } from "./treasury-outcome.controller";
import { TreasuryOutcomeService } from "./treasury-outcome.service";
import { TreasuryTransactionCostController } from "./treasury-transaction-cost.controller";
import { TreasuryTransactionCostService } from "./treasury-transaction-cost.service";
import { CounterfactualMethodologyController } from "./counterfactual-methodology.controller";
import { CounterfactualMethodologyService } from "./counterfactual-methodology.service";
import { CounterfactualAssessmentController } from "./counterfactual-assessment.controller";
import { CounterfactualAssessmentService } from "./counterfactual-assessment.service";
import { AdaptivePidWorkflowProcessorService } from "./adaptive-pid-workflow-processor.service";
import { OutcomeMemoryCandidateController } from "./outcome-memory-candidate.controller";
import { OutcomeMemoryCandidateService } from "./outcome-memory-candidate.service";

@Module({ controllers: [HealthController,CockpitProjectionController,TreasuryRegistryController,TreasuryWorkflowController,EvidenceRequestController, AuthController, OrganizationController, OrganizationConfigurationController, EvidenceController,KnowledgeController,OutcomeMemoryCandidateController,GovernedSkillController,TreasuryOutcomeController,TreasuryTransactionCostController,CounterfactualMethodologyController,CounterfactualAssessmentController, AuditController, AuditExportController, AlertController, DecisionController, DecisionJobController, AdvisoryProviderController, OutboxPublisherController, AttestcoinController, PolicyController, PolicyScenarioComparisonController, ProposalController, GovernanceController, ExecutionController,SafeTransactionController], providers: [DatabaseService,CockpitProjectionNotificationService,CockpitStreamAdmissionService,CockpitProjectionService,TreasuryRegistryService,TreasuryWorkflowService,AdaptivePidWorkflowProcessorService,OperationalHealthService,EvidenceRequestService, AuthService,SessionGuard,RequestTraceMiddleware,OutboxDispatcherService,AlertService,AnomalyScannerService,AuditExportService,ExplorerLinkService,OrganizationService,OrganizationConfigurationService,EvidenceService,KnowledgeService,OutcomeMemoryCandidateService,GovernedSkillService,TreasuryOutcomeService,TreasuryTransactionCostService,CounterfactualMethodologyService,CounterfactualAssessmentService, DecisionService, AttestcoinReliabilityService,AttestcoinService,PolicyService,ProposalService,GovernanceService,ExecutionService,SafeTransactionService,{provide:APP_INTERCEPTOR,useClass:TenantContextInterceptor},{provide:APP_INTERCEPTOR,useClass:IdempotencyInterceptor},{provide:OUTBOX_PUBLISHER,useFactory:createOutboxPublisherFromEnvironment},{provide:ORGANIZATION_CONFIGURATION_ADAPTER,useFactory:createOrganizationConfigurationAdapterFromEnvironment},{provide:ADVISORY_PROVIDER,useFactory:createAdvisoryProviderFromEnvironment},{provide:ATTESTCOIN_ADAPTER,useFactory:createAttestcoinAdapterFromEnvironment},{provide:EVIDENCE_ANCHOR_RECEIPT_ADAPTER,useFactory:createEvidenceAnchorReceiptAdapterFromEnvironment},{provide:GOVERNANCE_ADAPTER,useFactory:createGovernanceAdapterFromEnvironment},{provide:TREASURY_GUARD_ADAPTER,useFactory:createTreasuryGuardAdapterFromEnvironment},{provide:SAFE_TRANSACTION_ADAPTER,useFactory:createSafeTransactionAdapterFromEnvironment}] })
export class AppModule implements NestModule {configure(consumer:MiddlewareConsumer){consumer.apply(RequestTraceMiddleware).forRoutes({path:"{*path}",method:RequestMethod.ALL})}}

