import { BadRequestException,NotFoundException } from "@nestjs/common";
import { AuditExportService } from "./audit-export.service";
import { auditExportManifestHash,buildAuditExportManifest,normalizeAuditExportFilters } from "./audit-export-engine";

const event={id:"audit_1",event_type:"policy.activated",actor:{type:"human",id:"user_1"},object_type:"policy",object_id:"policy_1",data:{version:1},payload_hash:"0xaudit",schema_version:"1.0",request_id:"req_1",created_at:"2026-08-07T00:00:01Z"};
const filters=normalizeAuditExportFilters({eventType:"policy.activated"});const manifest=buildAuditExportManifest("org_1",filters,[event]);const exportRow={id:"auditexport_1",organization_id:"org_1",requested_by:"user_1",filters,manifest,manifest_hash:auditExportManifestHash(manifest),event_count:1,first_event_id:"audit_1",last_event_id:"audit_1",created_at:"2026-08-07T00:00:02Z"};
describe("AuditExportService",()=>{
  it("creates an immutable manifest and audits only a newly persisted export",async()=>{const client={query:jest.fn().mockResolvedValueOnce({rows:[event]}).mockResolvedValueOnce({rows:[exportRow]}).mockResolvedValueOnce({rows:[]})};const db={transaction:(work:any)=>work(client)} as any;const result=await new AuditExportService(db).create("org_1","user_1",{eventType:"policy.activated"});expect(result).toEqual(expect.objectContaining({id:"auditexport_1",organizationId:"org_1",eventCount:1,manifestHash:exportRow.manifest_hash,assetExecutionAuthorized:false}));expect(client.query.mock.calls[0][1].slice(0,4)).toEqual(["org_1","policy.activated",null,null]);expect(client.query.mock.calls[2][0]).toContain("audit.export_created")});
  it("reuses an identical manifest without emitting a second audit event",async()=>{const client={query:jest.fn().mockResolvedValueOnce({rows:[event]}).mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[exportRow]})};const db={transaction:(work:any)=>work(client)} as any;await expect(new AuditExportService(db).create("org_1","user_1",{eventType:"policy.activated"})).resolves.toEqual(expect.objectContaining({id:"auditexport_1"}));expect(client.query).toHaveBeenCalledTimes(3)});
  it("verifies both the stored manifest and immutable source events",async()=>{const db={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[exportRow]}).mockResolvedValueOnce({rows:[event]})} as any;await expect(new AuditExportService(db).verify("org_1","auditexport_1")).resolves.toEqual(expect.objectContaining({storedManifestValid:true,sourceEventsMatch:true,verified:true,assetExecutionAuthorized:false}));expect(db.query.mock.calls[0][1]).toEqual(["org_1","auditexport_1"]);expect(db.query.mock.calls[1][1]).toEqual(["org_1",["audit_1"]])});
  it("rejects inverted ranges and conceals missing exports",async()=>{const service=new AuditExportService({transaction:jest.fn(),query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})} as any);await expect(service.create("org_1","user_1",{from:"2026-08-08T00:00:00Z",to:"2026-08-07T00:00:00Z"})).rejects.toBeInstanceOf(BadRequestException);await expect(service.get("org_1","missing")).rejects.toBeInstanceOf(NotFoundException)});
});
