import { decisionRoles } from "./decision-engine";
import { buildContentfulEightAgentDecisionArtifact } from "./contentful-eight-agent-decision";

const expected:any={Governor:["GOVERNANCE","PROTOCOL","DECISION_MEMORY"],Research:["GOVERNANCE","PROTOCOL"],Strategy:["GOVERNANCE","PROTOCOL","DECISION_MEMORY"],Quant:["PROTOCOL"],Risk:["PROTOCOL","DECISION_MEMORY"],Compliance:["GOVERNANCE","PROTOCOL"],Portfolio:["DECISION_MEMORY"],Treasury:["GOVERNANCE","DECISION_MEMORY"]};
const source=(partition:string)=>({id:`source_${partition}`,sourceKey:`key_${partition}`,partition,contentHash:`0x${partition.toLowerCase().padEnd(64,"0").slice(0,64)}`});
const sources=[source("GOVERNANCE"),source("PROTOCOL"),source("DECISION_MEMORY"),{...source("GOVERNANCE"),id:"source_GOVERNANCE_2",sourceKey:"key_GOVERNANCE_2"},{...source("PROTOCOL"),id:"source_PROTOCOL_2",sourceKey:"key_PROTOCOL_2"}];
const manifests=decisionRoles.map((role,index)=>{const items=expected[role].map((partition:string,itemIndex:number)=>{const selected=sources.find(value=>value.partition===partition)!;const chunkId=`chunk_${index}_${itemIndex}`,contentHash=`0x${String(index+itemIndex+1).repeat(64).slice(0,64)}`;return{sourceId:selected.id,sourceVersion:1,chunkId,partition,heading:partition,contentHash,citation:`rag:${selected.id}:v1:${chunkId}:${contentHash}`,score:.9}});return{id:`manifest_${index}`,role,query:"query",query_hash:`0x${"1".repeat(64)}`,manifest_hash:`0x${String(index+1).repeat(64).slice(0,64)}`,status:"SUPPORTED",reason_code:null,items}});
const historical={id:"decision_old",outputHash:"0xold",retrievalBundleHash:"0xoldbundle",retrievalManifests:decisionRoles.map(role=>({role,status:"INSUFFICIENT_CONTEXT",items:[]}))};
const current:any={id:"decision_new",status:"REVIEW_REQUIRED",provider:"mock-deterministic",evidenceSnapshotId:"snap",evidenceManifestHash:"0xsnap",retrievalBundleHash:"0xnewbundle",inputHash:"0xinput",outputHash:"0xoutput",retrievalManifests:manifests,agentRuns:decisionRoles.map(role=>({role,run_state:"SUCCEEDED",model_version:"mock-deterministic-v4-eight-agent"})),agentMessages:[{}]};
current.recommendation={recommendation:"HOLD",actions:[],humanApprovalRequired:true,assetExecutionAuthorized:false,citationCoverage:{coverage:1},agentPositions:manifests.map(manifest=>({role:manifest.role,position:`${manifest.role} position`,retrievalManifestHash:manifest.manifest_hash,retrievalStatus:"SUPPORTED",knowledgeCitations:manifest.items.map((item:{citation:string})=>item.citation),assetExecutionAuthorized:false})),challenges:[{raisedBy:"Risk",code:"RISK_MARKET_EVIDENCE_REQUIRED"},{raisedBy:"Compliance",code:"COMPLIANCE_AUTHORITY_EVIDENCE_REQUIRED"}]};
const input=()=>({recordedAt:"2026-08-25T00:00:00.000Z",approvalReceiptHash:`0x${"a".repeat(64)}`,approvedSources:sources,historical:structuredClone(historical),current:structuredClone(current),job:{jobId:"job_new",status:"COMPLETED",decisionId:"decision_new"},snapshot:{id:"snap",manifestHash:"0xsnap"},evidence:{id:"evidence",contentHash:"0xevidence"}});

describe("contentful eight-Agent Decision artifact",()=>{
  it("accepts eight supported role-scoped Manifests and preserves zero authority",()=>{const artifact=buildContentfulEightAgentDecisionArtifact(input());expect(artifact.current.manifests).toHaveLength(8);expect(artifact.current.manifests.every(manifest=>manifest.status==="SUPPORTED"&&manifest.itemCount>0)).toBe(true);expect(artifact.controls).toMatchObject({manifestFrozen:true,agentRun:true,proposalCreated:false,signature:false,broadcast:false,assetExecutionAuthorized:false})});
  it("rejects historical mutation or a missing role-scoped citation",()=>{const changed=input();changed.historical.retrievalManifests[0].status="SUPPORTED";expect(()=>buildContentfulEightAgentDecisionArtifact(changed)).toThrow("HISTORICAL_NO_CONTEXT_DECISION_MUTATED");const missing=input();missing.current.retrievalManifests.find((manifest:any)=>manifest.role==="Portfolio").items=[];expect(()=>buildContentfulEightAgentDecisionArtifact(missing)).toThrow("CONTENTFUL_MANIFEST_UNSUPPORTED_Portfolio")});
});
