import { generateKeyPairSync, sign } from "node:crypto";
import { buildAEOSEvidenceSourceDeploymentPlan,buildEvidenceAnchorDeploymentPlan,buildPolicyRegistryDeploymentPlan,buildTreasuryGuardDeploymentManifest,buildTreasuryGuardDeploymentPlan,verifyAEOSEvidenceSourceReadback,verifyEvidenceAnchorReadback,verifyPolicyRegistryReadback,verifyTreasuryGuardDeploymentManifestSignature,verifyTreasuryGuardReadback } from "./deployment-engine";

const governance="0x1111111111111111111111111111111111111111";const guardian="0x2222222222222222222222222222222222222222";const policyRegistry="0x4444444444444444444444444444444444444444";
describe("AEOSTreasuryEvidenceSource deployment artifacts",()=>{
  const base={chainId:11155111,reporter:governance,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"contracts/src/AEOSTreasuryEvidenceSource.sol"};
  it("builds deterministic zero-value unsigned Sepolia init code",()=>{const first=buildAEOSEvidenceSourceDeploymentPlan(base),second=buildAEOSEvidenceSourceDeploymentPlan(base);expect(first).toEqual(second);expect(first.constructor).toEqual({reporter:governance});expect(first.unsignedTransaction).toEqual(expect.objectContaining({to:null,value:"0"}));expect(first).toEqual(expect.objectContaining({chainId:11155111,signed:false,submitted:false,containsPrivateKey:false,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false}))});
  it("rejects the wrong chain, zero reporter, and malformed artifacts",()=>{expect(()=>buildAEOSEvidenceSourceDeploymentPlan({...base,chainId:1})).toThrow("CHAIN_INVALID");expect(()=>buildAEOSEvidenceSourceDeploymentPlan({...base,reporter:"0x0000000000000000000000000000000000000000"})).toThrow("REPORTER_INVALID");expect(()=>buildAEOSEvidenceSourceDeploymentPlan({...base,runtimeBytecode:"0x"})).toThrow("BYTECODE_INVALID")});
  it("fails deployment readback closed on chain, reporter, init code, value, receipt, or finality mismatch",()=>{const plan=buildAEOSEvidenceSourceDeploymentPlan(base);const readback={expectedChainId:11155111,actualChainId:11155111,expectedReporter:governance,actualReporter:governance,expectedInitCodeHash:plan.unsignedTransaction.initCodeHash,deploymentTransactionData:plan.unsignedTransaction.data,deploymentTransactionTo:null,deploymentTransactionValue:"0",address:"0x3333333333333333333333333333333333333333",code:"0x6000",deploymentTransactionHash:`0x${"44".repeat(32)}`,receiptStatus:1,receiptTo:null,receiptContractAddress:"0x3333333333333333333333333333333333333333",receiptBlockNumber:10,latestBlockNumber:11,minimumConfirmations:2};expect(verifyAEOSEvidenceSourceReadback(readback).status).toBe("VERIFIED");for(const changed of[{actualChainId:1},{actualReporter:guardian},{deploymentTransactionData:"0x6000"},{deploymentTransactionValue:"1"},{receiptStatus:0},{latestBlockNumber:10}])expect(verifyAEOSEvidenceSourceReadback({...readback,...changed} as any).status).toBe("REJECTED")});
});
describe("PolicyRegistry deployment artifacts",()=>{
  const base={chainId:102031,governance,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"contracts/src/PolicyRegistry.sol"};
  it("builds deterministic zero-value unsigned init code bound to DAO governance",()=>{const first=buildPolicyRegistryDeploymentPlan(base),second=buildPolicyRegistryDeploymentPlan(base);expect(first).toEqual(second);expect(first.constructor).toEqual({governance});expect(first.unsignedTransaction).toEqual(expect.objectContaining({to:null,value:"0"}));expect(first.expectedReadback).toEqual(expect.objectContaining({governance,latestVersion:0}));expect(first).toEqual(expect.objectContaining({signed:false,submitted:false,containsPrivateKey:false,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false}))});
  it("rejects the wrong chain, zero governance, and malformed artifacts",()=>{expect(()=>buildPolicyRegistryDeploymentPlan({...base,chainId:1})).toThrow("CHAIN_INVALID");expect(()=>buildPolicyRegistryDeploymentPlan({...base,governance:"0x0000000000000000000000000000000000000000"})).toThrow();expect(()=>buildPolicyRegistryDeploymentPlan({...base,runtimeBytecode:"0x"})).toThrow("BYTECODE_INVALID")});
  it("fails readback closed on runtime, governance, dirty state, transaction, receipt, or finality mismatch",()=>{const plan=buildPolicyRegistryDeploymentPlan(base);const readback={expectedChainId:102031,actualChainId:102031,expectedGovernance:governance,actualGovernance:governance,expectedLatestVersion:0,actualLatestVersion:0,expectedRuntimeBytecodeHash:plan.artifact.runtimeBytecodeHash,expectedInitCodeHash:plan.unsignedTransaction.initCodeHash,deploymentTransactionData:plan.unsignedTransaction.data,deploymentTransactionTo:null,deploymentTransactionValue:"0",address:"0x3333333333333333333333333333333333333333",code:base.runtimeBytecode,deploymentTransactionHash:`0x${"44".repeat(32)}`,receiptStatus:1,receiptTo:null,receiptContractAddress:"0x3333333333333333333333333333333333333333",receiptBlockNumber:10,latestBlockNumber:11,minimumConfirmations:2};expect(verifyPolicyRegistryReadback(readback).status).toBe("VERIFIED");for(const changed of[{code:"0x60026000"},{actualGovernance:guardian},{actualLatestVersion:1},{deploymentTransactionData:"0x6000"},{deploymentTransactionTo:governance},{deploymentTransactionValue:"1"},{receiptStatus:0},{latestBlockNumber:10}])expect(verifyPolicyRegistryReadback({...readback,...changed} as any).status).toBe("REJECTED")});
});
describe("TreasuryGuard deployment artifacts",()=>{
  it("builds a deterministic unsigned constructor payload bound to PolicyRegistry",()=>{const input={chainId:102031,governance,guardian,policyRegistry,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"};const first=buildTreasuryGuardDeploymentPlan(input);const second=buildTreasuryGuardDeploymentPlan(input);expect(first).toEqual(second);expect(first.constructor).toEqual({governance,guardian,policyRegistry,rolesSeparated:true});expect(first).toEqual(expect.objectContaining({chainId:102031,requiresUserWalletConfirmation:true,signed:false,submitted:false,containsPrivateKey:false,assetExecutionAuthorized:false}));expect(first.unsignedTransaction).toEqual(expect.objectContaining({to:null,value:"0"}))});
  it("rejects role/registry collapse and invalid bytecode",()=>{expect(()=>buildTreasuryGuardDeploymentPlan({chainId:102031,governance,guardian:governance,policyRegistry,creationBytecode:"0x6000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"})).toThrow("ROLES_MUST_BE_SEPARATE");expect(()=>buildTreasuryGuardDeploymentPlan({chainId:102031,governance,guardian,policyRegistry:guardian,creationBytecode:"0x6000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"})).toThrow("ROLES_MUST_BE_SEPARATE");expect(()=>buildTreasuryGuardDeploymentPlan({chainId:102031,governance,guardian,policyRegistry,creationBytecode:"0x",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"})).toThrow("BYTECODE_INVALID")});
  it("fails deployment readback closed unless artifact, transaction, receipt, roles, registry, chain, and pause match",()=>{const plan=buildTreasuryGuardDeploymentPlan({chainId:102031,governance,guardian,policyRegistry,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"});const base={expectedChainId:102031,actualChainId:102031,expectedGovernance:governance,actualGovernance:governance,expectedGuardian:guardian,actualGuardian:guardian,expectedPolicyRegistry:policyRegistry,actualPolicyRegistry:policyRegistry,expectedRuntimeBytecodeHash:plan.artifact.runtimeBytecodeHash,expectedInitCodeHash:plan.unsignedTransaction.initCodeHash,deploymentTransactionData:plan.unsignedTransaction.data,deploymentTransactionTo:null,deploymentTransactionValue:"0",deploymentTransactionHash:`0x${"44".repeat(32)}`,receiptStatus:1,receiptTo:null,receiptContractAddress:"0x3333333333333333333333333333333333333333",receiptBlockNumber:10,latestBlockNumber:11,minimumConfirmations:2,address:"0x3333333333333333333333333333333333333333",code:"0x60016000",paused:true};expect(verifyTreasuryGuardReadback(base).status).toBe("VERIFIED");for(const changed of[{code:"0x60026000"},{actualPolicyRegistry:governance},{paused:false},{deploymentTransactionData:"0x6000"},{deploymentTransactionTo:governance},{deploymentTransactionValue:"1"},{receiptStatus:0},{latestBlockNumber:10}])expect(verifyTreasuryGuardReadback({...base,...changed} as any)).toEqual(expect.objectContaining({status:"REJECTED",assetExecutionAuthorized:false}))});
  const plan=()=>buildTreasuryGuardDeploymentPlan({chainId:102031,governance,guardian,policyRegistry,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"src/TreasuryGuard.sol"});
  it("builds a deterministic external signing request with no AEOS signing capability",()=>{const first=buildTreasuryGuardDeploymentManifest(plan());const second=buildTreasuryGuardDeploymentManifest(plan());expect(first).toEqual(second);expect(first.manifest.authority).toEqual({requiresUserWalletConfirmation:true,aeosSigningCapability:false,aeosBroadcastCapability:false,signed:false,submitted:false,containsPrivateKey:false,assetExecutionAuthorized:false});expect(first.signingRequest).toEqual(expect.objectContaining({algorithm:"Ed25519",acceptsOnlyExternalSignature:true,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false}));expect(Buffer.from(first.signingRequest.payloadBase64,"base64").length).toBeGreaterThan(0)});
  it("verifies an externally produced Ed25519 signature without receiving a private key",()=>{const deployment=buildTreasuryGuardDeploymentManifest(plan());const keys=generateKeyPairSync("ed25519");const signature=sign(null,Buffer.from(deployment.signingRequest.payloadBase64,"base64"),keys.privateKey);const result=verifyTreasuryGuardDeploymentManifestSignature({manifest:deployment.manifest,signerId:"test-kms-key-v1",publicKeySpkiBase64:keys.publicKey.export({format:"der",type:"spki"}).toString("base64"),signatureBase64:signature.toString("base64")});expect(result).toEqual(expect.objectContaining({status:"VERIFIED",externalSignatureVerified:true,manifestSignedExternally:true,aeosSigned:false,submitted:false,assetExecutionAuthorized:false}))});
  it("rejects a changed immutable manifest before signature verification",()=>{const deployment=buildTreasuryGuardDeploymentManifest(plan());const changed={...deployment.manifest,chainId:1};expect(()=>verifyTreasuryGuardDeploymentManifestSignature({manifest:changed,signerId:"test-kms-key-v1",publicKeySpkiBase64:"AA==",signatureBase64:Buffer.alloc(64).toString("base64")})).toThrow("DEPLOYMENT_MANIFEST_HASH_MISMATCH")});
  it("rejects invalid signatures and non-Ed25519 public keys",()=>{const deployment=buildTreasuryGuardDeploymentManifest(plan());const ed=generateKeyPairSync("ed25519");const rejected=verifyTreasuryGuardDeploymentManifestSignature({manifest:deployment.manifest,signerId:"test-kms-key-v1",publicKeySpkiBase64:ed.publicKey.export({format:"der",type:"spki"}).toString("base64"),signatureBase64:Buffer.alloc(64).toString("base64")});expect(rejected.status).toBe("REJECTED");const rsa=generateKeyPairSync("rsa",{modulusLength:2048});expect(()=>verifyTreasuryGuardDeploymentManifestSignature({manifest:deployment.manifest,signerId:"test-kms-key-v1",publicKeySpkiBase64:rsa.publicKey.export({format:"der",type:"spki"}).toString("base64"),signatureBase64:Buffer.alloc(64).toString("base64")})).toThrow("DEPLOYMENT_MANIFEST_SIGNATURE_ALGORITHM_INVALID")});
});

describe("EvidenceAnchorASC deployment artifacts",()=>{
  const verifier="0x0000000000000000000000000000000000000FD2";const base={chainId:102031,nativeQueryVerifier:verifier,sourceChainKey:1,creationBytecode:"0x60006000",runtimeBytecode:"0x60016000",artifactCompiler:"0.8.28",artifactSource:"contracts/src/EvidenceAnchorASC.sol"};
  it("builds deterministic zero-value unsigned init code bound to the official verifier",()=>{const first=buildEvidenceAnchorDeploymentPlan(base),second=buildEvidenceAnchorDeploymentPlan(base);expect(first).toEqual(second);expect(first.constructor).toEqual({nativeQueryVerifier:verifier.toLowerCase(),allowedSourceChainKey:1});expect(first.unsignedTransaction).toEqual(expect.objectContaining({to:null,value:"0"}));expect(first).toEqual(expect.objectContaining({chainId:102031,signed:false,submitted:false,containsPrivateKey:false,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false}))});
  it("rejects a substituted verifier, wrong chain/key, and malformed artifact",()=>{expect(()=>buildEvidenceAnchorDeploymentPlan({...base,nativeQueryVerifier:"0x1111111111111111111111111111111111111111"})).toThrow("VERIFIER_INVALID");expect(()=>buildEvidenceAnchorDeploymentPlan({...base,chainId:1})).toThrow("CHAIN_INVALID");expect(()=>buildEvidenceAnchorDeploymentPlan({...base,sourceChainKey:2})).toThrow("SOURCE_CHAIN_KEY_INVALID");expect(()=>buildEvidenceAnchorDeploymentPlan({...base,runtimeBytecode:"0x"})).toThrow("BYTECODE_INVALID")});
  it("fails readback closed on artifact, value, config, receipt, contract-creation, or finality mismatch",()=>{const plan=buildEvidenceAnchorDeploymentPlan(base);const readback={expectedChainId:102031,actualChainId:102031,expectedNativeQueryVerifier:verifier,actualNativeQueryVerifier:verifier,expectedSourceChainKey:1,actualSourceChainKey:1,expectedInitCodeHash:plan.unsignedTransaction.initCodeHash,deploymentTransactionData:plan.unsignedTransaction.data,deploymentTransactionTo:null,deploymentTransactionValue:"0",address:"0x3333333333333333333333333333333333333333",code:"0x6000",deploymentTransactionHash:`0x${"44".repeat(32)}`,receiptStatus:1,receiptTo:null,receiptContractAddress:"0x3333333333333333333333333333333333333333",receiptBlockNumber:10,latestBlockNumber:11,minimumConfirmations:2};expect(verifyEvidenceAnchorReadback(readback).status).toBe("VERIFIED");for(const changed of[{deploymentTransactionData:"0x6000"},{deploymentTransactionTo:"0x1111111111111111111111111111111111111111"},{deploymentTransactionValue:"1"},{actualNativeQueryVerifier:"0x1111111111111111111111111111111111111111"},{receiptStatus:0},{receiptTo:"0x1111111111111111111111111111111111111111"},{latestBlockNumber:10}])expect(verifyEvidenceAnchorReadback({...readback,...changed} as any).status).toBe("REJECTED")});
});
