import{deriveEvidenceObservedState,OBSERVED_STATE_PREDICATES,ObservedStateEvidence}from"./evidence-observed-state-engine";
const now=new Date("2026-08-15T00:00:00.000Z"),treasuryId="treasury_core";
const rows=Object.entries(OBSERVED_STATE_PREDICATES).map(([metric,predicate],index)=>({id:`ev_${index}`,contentHash:`0x${String(index+1).repeat(64)}`.slice(0,66),predicate,subject:{type:"treasury",id:treasuryId},value:metric==="criticalIncident"?{active:false,scope:"configured chains and assets"}:{bps:[4000,250,100,5][index]},source:{provider:"mock-observed-state-v1"},verificationStatus:"VERIFIED",freshnessExpiresAt:"2026-08-16T00:00:00.000Z",qualityScore:95,conflictGroupId:null,observedAt:`2026-08-15T00:0${index}:00.000Z`}))as ObservedStateEvidence[];const manifest=rows.map(row=>({evidenceId:row.id,contentHash:row.contentHash}));
describe("Evidence observed-state derivation",()=>{
  it("derives bounded metrics and preserves Mock provenance without causal claims",()=>{const result=deriveEvidenceObservedState({manifest,evidence:rows,treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000});expect(result.observedAllocationBps).toBe(4000);expect(result.mockEvidenceUsed).toBe(true);expect(result.allMetricsAttestcoinUscVerified).toBe(false);expect(result.causalImpactClaimed).toBe(false);expect(result.assetExecutionAuthorized).toBe(false)});
  it("does not allow a transaction fact to substitute for a required metric",()=>{const changed=rows.filter(row=>row.predicate!==OBSERVED_STATE_PREDICATES.volatility);changed.push({...rows[1],id:"ev_tx",predicate:"blockchain.transaction.included"});expect(()=>deriveEvidenceObservedState({manifest:changed.map(row=>({evidenceId:row.id,contentHash:row.contentHash})),evidence:changed,treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000})).toThrow(`OBSERVED_STATE_METRIC_MISSING:${OBSERVED_STATE_PREDICATES.volatility}`)});
  it("does not promote source JSON into Attestcoin provenance without a verified proof-job relation",()=>{const forged=rows.map(row=>({...row,source:{provider:"usc-readonly",proofSnapshotHash:"0xproof",verificationRequestHash:"0xrequest"}}));const result=deriveEvidenceObservedState({manifest,evidence:forged,treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000});expect(result.allMetricsAttestcoinUscVerified).toBe(false);expect(result.metricEvidenceRefs.every(ref=>ref.provenance==="VERIFIED_EVIDENCE")).toBe(true)});
  it("rejects conflicts, stale data, duplicate metrics, treasury mismatch and skew",()=>{expect(()=>deriveEvidenceObservedState({manifest,evidence:rows.map((row,index)=>index?row:{...row,conflictGroupId:"conflict"}),treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000})).toThrow("OBSERVED_STATE_EVIDENCE_CONFLICT");expect(()=>deriveEvidenceObservedState({manifest,evidence:rows.map((row,index)=>index?row:{...row,freshnessExpiresAt:now}),treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000})).toThrow("OBSERVED_STATE_EVIDENCE_STALE");expect(()=>deriveEvidenceObservedState({manifest:[...manifest,{...manifest[0],evidenceId:"duplicate"}],evidence:[...rows,{...rows[0],id:"duplicate"}],treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000})).toThrow("OBSERVED_STATE_DUPLICATE_METRIC");expect(()=>deriveEvidenceObservedState({manifest,evidence:rows.map((row,index)=>index?row:{...row,subject:{type:"treasury",id:"other"}}),treasuryId,minimumQuality:80,now,maxMetricSkewMs:300000})).toThrow("OBSERVED_STATE_TREASURY_MISMATCH");expect(()=>deriveEvidenceObservedState({manifest,evidence:rows,treasuryId,minimumQuality:80,now,maxMetricSkewMs:1})).toThrow("OBSERVED_STATE_METRIC_SKEW_EXCEEDED")});
});
