import { buildProjectReportedControlObservation,buildTreasuryObservationCommitRequest } from "./evidence-source-engine";

const base={chainId:11155111,sourceContract:"0x2222222222222222222222222222222222222222",reporter:"0x444D510728FB8072351cB5d0E88432e6a8501DFA",organizationId:"org_alpha",treasuryId:"treasury_core",observationKey:"evidence_snapshot_1",evidencePayloadHash:`0x${"ab".repeat(32)}`,observedAt:1_787_333_400};

describe("Sepolia treasury observation commit request",()=>{
  it("deterministically binds tenant, treasury, Evidence hash and external reporter",()=>{const first=buildTreasuryObservationCommitRequest(base),second=buildTreasuryObservationCommitRequest(base);expect(first).toEqual(second);expect(first).toEqual(expect.objectContaining({chainId:11155111,sourceContract:base.sourceContract,reporter:base.reporter.toLowerCase(),requiresUserWalletConfirmation:true,signed:false,submitted:false,containsPrivateKey:false,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false}));expect(first.unsignedTransaction).toEqual(expect.objectContaining({from:base.reporter.toLowerCase(),to:base.sourceContract,value:"0"}));expect(first.observation.evidencePayloadHash).toBe(base.evidencePayloadHash)});
  it("domain-separates organizations, treasuries, and observation keys",()=>{const first=buildTreasuryObservationCommitRequest(base);expect(buildTreasuryObservationCommitRequest({...base,organizationId:"org_beta"}).observation.organizationCommitment).not.toBe(first.observation.organizationCommitment);expect(buildTreasuryObservationCommitRequest({...base,treasuryId:"treasury_beta"}).observation.treasuryCommitment).not.toBe(first.observation.treasuryCommitment);expect(buildTreasuryObservationCommitRequest({...base,observationKey:"evidence_snapshot_2"}).observation.observationId).not.toBe(first.observation.observationId)});
  it("fails closed on wrong chain, zero addresses, malformed hashes, timestamps, and tenant identifiers",()=>{expect(()=>buildTreasuryObservationCommitRequest({...base,chainId:1})).toThrow("CHAIN_INVALID");expect(()=>buildTreasuryObservationCommitRequest({...base,sourceContract:"0x0000000000000000000000000000000000000000"})).toThrow("ADDRESS_INVALID");expect(()=>buildTreasuryObservationCommitRequest({...base,evidencePayloadHash:"0x12"})).toThrow("HASH_INVALID");expect(()=>buildTreasuryObservationCommitRequest({...base,observedAt:0})).toThrow("OBSERVED_AT_INVALID");expect(()=>buildTreasuryObservationCommitRequest({...base,organizationId:" "})).toThrow("ORGANIZATION_ID_INVALID")});
});

describe("project-reported control observation",()=>{
  it("freezes an honest transaction-inclusion claim without leaking tenant identifiers",()=>{const result=buildProjectReportedControlObservation(base);expect(result.payload).toEqual(expect.objectContaining({sourceKind:"PROJECT_REPORTED",verificationScope:"TRANSACTION_INCLUSION_ONLY",treasuryRegistryStatus:"UNREGISTERED_LOGICAL_IDENTITY",controlState:expect.objectContaining({daoInControl:true,advisoryOnly:true,assetExecutionAuthorized:false}),truthBoundary:{payloadEconomicTruthVerified:false,attestcoinRequestedToVerifyTransactionInclusion:true}}));expect(result.commitRequest.observation.evidencePayloadHash).toBe(result.evidencePayloadHash);const serialized=JSON.stringify(result);expect(serialized).not.toContain(base.organizationId);expect(serialized).not.toContain(base.treasuryId);expect(serialized).not.toContain(base.observationKey)});
  it("is deterministic and fails closed on invalid chain or timestamp",()=>{expect(buildProjectReportedControlObservation(base)).toEqual(buildProjectReportedControlObservation(base));expect(()=>buildProjectReportedControlObservation({...base,chainId:1})).toThrow("CHAIN_INVALID");expect(()=>buildProjectReportedControlObservation({...base,observedAt:0})).toThrow("OBSERVED_AT_INVALID")});
});
