import {BadRequestException,forwardRef,Inject,Injectable,NotFoundException,Optional} from "@nestjs/common";
import {randomUUID} from "node:crypto";
import {PoolClient} from "pg";
import {DatabaseService} from "./database.service";
import {CreateEvidenceRequestDto} from "./evidence-request.dto";
import {DeterministicMockEvidenceRequestBroker,EvidenceRequestValidationError,freezeEvidenceRequest} from "./evidence-request-engine";
import {hashValue} from "./decision-engine";
import {persistEvidenceClassification} from "./evidence-classification";
import {CommitteeGap} from "./committee-evidence-gap";
import {DecisionService} from "./decision.service";
const id=(p:string)=>`${p}_${randomUUID().replaceAll("-","")}`;

@Injectable()
export class EvidenceRequestService{
  private readonly broker=new DeterministicMockEvidenceRequestBroker();
  constructor(private readonly db:DatabaseService,@Optional() @Inject(forwardRef(()=>DecisionService)) private readonly decisions?:DecisionService){}

  async propose(org:string,decisionId:string,input:CreateEvidenceRequestDto){
    const decision=await this.db.query<any>("SELECT d.id,r.role FROM decisions d JOIN agent_runs r ON r.organization_id=d.organization_id AND r.decision_id=d.id AND r.id=$3 WHERE d.organization_id=$1 AND d.id=$2",[org,decisionId,input.agentRunId]);
    if(!decision.rowCount)throw new NotFoundException("Decision Agent run not found");
    const requestingRole=decision.rows[0].role;const supporting=[...new Set(input.supportingEvidenceIds)].sort();
    if(supporting.length){const found=await this.db.query("SELECT id FROM evidence WHERE organization_id=$1 AND id=ANY($2::text[])",[org,supporting]);if(found.rowCount!==supporting.length)throw new NotFoundException("One or more supporting Evidence items were not found")}
    let request;try{request=freezeEvidenceRequest({...input,decisionId,requestingRole,supportingEvidenceIds:supporting} as any)}catch(error){if(error instanceof EvidenceRequestValidationError)throw new BadRequestException(error.message);throw error}
    return this.db.transaction(async client=>{
      const existing=await client.query<any>("SELECT * FROM evidence_requests WHERE organization_id=$1 AND decision_id=$2 AND request_hash=$3",[org,decisionId,request.requestHash]);if(existing.rowCount)return this.getWithClient(client,org,existing.rows[0].id);
      const requestId=id("evreq");
      await client.query("INSERT INTO evidence_requests(id,organization_id,decision_id,agent_run_id,schema_version,requesting_role,gap_code,gap_type,source_chain_id,subject,transaction_hash,event_type,from_block,to_block,required_fields,required_confirmations,max_freshness_seconds,priority,rationale,supporting_evidence_ids,budget,broker_version,request_hash,asset_execution_authorized) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,false)",[requestId,org,decisionId,request.agentRunId,request.schemaVersion,request.requestingRole,request.gapCode,request.gapType,request.sourceChainId,request.subject,request.transactionHash??null,request.eventType??null,request.fromBlock??null,request.toBlock??null,request.requiredFields,request.requiredConfirmations,request.maxFreshnessSeconds,request.priority,request.rationale,request.supportingEvidenceIds,request.budget,request.brokerVersion,request.requestHash]);
      let ordinal=0;const event=async(status:string,reasonCode:string|null=null,evidenceId:string|null=null,details:any={})=>{ordinal++;const payload={requestId,status,reasonCode,evidenceId,details,ordinal};await client.query("INSERT INTO evidence_request_events(id,organization_id,request_id,ordinal,status,reason_code,evidence_id,details,payload_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id("evreqevt"),org,requestId,ordinal,status,reasonCode,evidenceId,details,hashValue(payload)])};
      await event("PROPOSED");await event("VALIDATED");await event("QUEUED");await event("DISCOVERING",null,null,{brokerMode:this.broker.mode,networkAuthority:false});
      const result=this.broker.run(request);if(result.status==="UNSATISFIED")await event("UNSATISFIED",result.reasonCode,null,{mockOnly:true});else{const evidenceId=await this.persistMockEvidence(client,org,requestId,result.mockFact);await event("NORMALIZED",null,evidenceId,{provider:result.mockFact.source.provider});await event("INDEXED",null,evidenceId,{classificationVersion:"deterministic-evidence-classifier-v1"});await event("SATISFIED",null,evidenceId,{mockOnly:true})}
      await this.audit(client,org,"evidence.request_completed",requestId,{decisionId,requestHash:request.requestHash,terminalStatus:result.status,brokerMode:this.broker.mode,networkAuthority:false,assetExecutionAuthorized:false});return this.getWithClient(client,org,requestId);
    });
  }

  async fulfillCommitteeGaps(org:string,decisionId:string,gaps:CommitteeGap[],agentRunIds:Map<string,string>){
    for(const gap of gaps.filter(item=>item.status==="REQUESTABLE").sort((a,b)=>a.gapHash.localeCompare(b.gapHash)).slice(0,1)){
      const runId=agentRunIds.get(gap.requestingRole);if(!runId)continue;
      const completed:any=await this.propose(org,decisionId,{agentRunId:runId,gapCode:gap.code,gapType:gap.gapType!,sourceChainId:gap.sourceChainId!,subject:gap.subject!,requiredFields:["amount","symbol"],requiredConfirmations:12,maxFreshnessSeconds:3600,priority:"HIGH",rationale:gap.rationale,supportingEvidenceIds:gap.supportingEvidenceIds,budget:{maxAttempts:1,maxResults:1}});
      const gapRow=await this.db.query<any>("SELECT id FROM decision_evidence_gaps WHERE organization_id=$1 AND decision_id=$2 AND gap_hash=$3",[org,decisionId,gap.gapHash]);if(!gapRow.rowCount)throw new NotFoundException("Decision Evidence gap not found");
      let childDecisionId:string|null=null;if(completed.status==="SATISFIED"&&completed.evidenceId&&this.decisions){const child=await this.decisions.createChildRevision(org,decisionId,completed.evidenceId);childDecisionId=child.id}
      await this.db.transaction(async client=>{const ordinal=Number((await client.query<any>("SELECT COALESCE(max(ordinal),-1)+1 ordinal FROM agent_messages WHERE organization_id=$1 AND decision_id=$2",[org,decisionId])).rows[0].ordinal);const messageId=id("message");const message={ordinal,round:4,senderRole:gap.requestingRole,recipientRole:"Governor",messageType:"REQUEST",code:gap.code,content:gap.rationale,evidenceIds:gap.supportingEvidenceIds,evidenceRequestId:completed.id};await client.query("INSERT INTO agent_messages(id,organization_id,decision_id,ordinal,round,sender_role,recipient_role,message_type,code,content,evidence_ids,input_hash,content_hash,evidence_request_id)VALUES($1,$2,$3,$4,4,$5,'Governor','REQUEST',$6,$7,$8,$9,$10,$11)",[messageId,org,decisionId,ordinal,gap.requestingRole,gap.code,gap.rationale,gap.supportingEvidenceIds,gap.gapHash,hashValue(message),completed.id]);const link={decisionId,gapId:gapRow.rows[0].id,evidenceRequestId:completed.id,agentMessageId:messageId,childDecisionId,assetExecutionAuthorized:false};await client.query("INSERT INTO decision_evidence_gap_links(id,organization_id,decision_id,gap_id,evidence_request_id,agent_message_id,child_decision_id,link_hash,asset_execution_authorized)VALUES($1,$2,$3,$4,$5,$6,$7,$8,false)",[id("gaplink"),org,decisionId,gapRow.rows[0].id,completed.id,messageId,childDecisionId,hashValue(link)]);await this.audit(client,org,"decision.evidence_gap_linked",decisionId,{...link,networkAuthority:false,assetExecutionAuthorized:false})});
    }
  }

  async list(org:string,decisionId?:string){const result=await this.db.query<any>("SELECT r.*,e.status,e.reason_code,e.evidence_id,e.created_at status_at FROM evidence_requests r JOIN LATERAL(SELECT status,reason_code,evidence_id,created_at FROM evidence_request_events WHERE request_id=r.id ORDER BY ordinal DESC LIMIT 1)e ON true WHERE r.organization_id=$1 AND($2::text IS NULL OR r.decision_id=$2) ORDER BY r.created_at DESC,r.id DESC LIMIT 100",[org,decisionId??null]);return{items:result.rows.map(this.map)}}
  async get(org:string,requestId:string){return this.db.transaction(client=>this.getWithClient(client,org,requestId))}
  private async getWithClient(client:PoolClient,org:string,requestId:string){const [request,events]=await Promise.all([client.query<any>("SELECT * FROM evidence_requests WHERE organization_id=$1 AND id=$2",[org,requestId]),client.query("SELECT ordinal,status,reason_code,evidence_id,details,payload_hash,created_at FROM evidence_request_events WHERE organization_id=$1 AND request_id=$2 ORDER BY ordinal",[org,requestId])]);if(!request.rowCount)throw new NotFoundException("Evidence request not found");return{...this.map(request.rows[0]),status:(events.rows.at(-1) as any)?.status,events:events.rows}}
  private async persistMockEvidence(client:PoolClient,org:string,requestId:string,fact:any){const rawPayload={schemaVersion:"mock.evidence-demand.v1",requestId,fact,mockOnly:true};const rawHash=hashValue(rawPayload);const raw=await client.query<any>("INSERT INTO raw_attestations(id,organization_id,provider,chain_id,payload,content_hash) VALUES($1,$2,'mock-attestcoin-demand-v1',$3,$4,$5) ON CONFLICT(organization_id,content_hash) DO UPDATE SET content_hash=EXCLUDED.content_hash RETURNING id",[id("raw"),org,fact.chain.id,rawPayload,rawHash]);const factHash=hashValue(fact);const expiresAt=new Date(new Date(fact.observedAt).getTime()+3600000);const evidence=await client.query<any>("INSERT INTO evidence(id,organization_id,raw_attestation_id,subject,predicate,value,chain,source,verification_status,freshness_status,freshness_expires_at,quality_score,quality_components,observed_at,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'VERIFIED','STALE',$9,80,$10,$11,$12) ON CONFLICT(organization_id,content_hash) DO UPDATE SET content_hash=EXCLUDED.content_hash RETURNING id",[id("ev"),org,raw.rows[0].id,fact.subject,fact.predicate,fact.value,fact.chain,fact.source,expiresAt.toISOString(),{proofStrength:15,sourceReliability:20,freshness:20,completeness:15,consistency:10},fact.observedAt,factHash]);await persistEvidenceClassification(client,org,{id:evidence.rows[0].id,contentHash:factHash,subject:fact.subject,predicate:fact.predicate,value:fact.value,source:fact.source,verificationStatus:"VERIFIED"});return evidence.rows[0].id}
  private map=(row:any)=>({id:row.id,organizationId:row.organization_id,decisionId:row.decision_id,agentRunId:row.agent_run_id,schemaVersion:row.schema_version,requestingRole:row.requesting_role,gapCode:row.gap_code,gapType:row.gap_type,sourceChainId:row.source_chain_id,subject:row.subject,transactionHash:row.transaction_hash??null,eventType:row.event_type??null,fromBlock:row.from_block==null?null:Number(row.from_block),toBlock:row.to_block==null?null:Number(row.to_block),requiredFields:row.required_fields,requiredConfirmations:row.required_confirmations,maxFreshnessSeconds:row.max_freshness_seconds,priority:row.priority,rationale:row.rationale,supportingEvidenceIds:row.supporting_evidence_ids,budget:row.budget,requestHash:row.request_hash,status:row.status,reasonCode:row.reason_code,evidenceId:row.evidence_id,brokerVersion:row.broker_version,networkAuthority:false,signerCapability:false,broadcastCapability:false,assetExecutionAuthorized:false,createdAt:row.created_at?new Date(row.created_at).toISOString():undefined});
  private async audit(client:PoolClient,org:string,eventType:string,objectId:string,data:any){const payload={eventType,organizationId:org,objectType:"evidence_request",objectId,data};await client.query("INSERT INTO audit_events(id,organization_id,event_type,actor,action,object_type,object_id,data,payload_hash)VALUES($1,$2,$3,$4,$5,'evidence_request',$6,$7,$8)",[id("audit"),org,eventType,{type:"system",id:"evidence-request-broker"},eventType,objectId,data,hashValue(payload)])}
}
