export const OBSERVED_STATE_PREDICATES={allocation:"treasury.allocation.bps",volatility:"market.volatility.bps",liquidityDrop:"market.liquidity_drop.bps",pegDeviation:"asset.peg_deviation.bps",criticalIncident:"security.critical_incident"}as const;
type ManifestItem={evidenceId:string;contentHash:string};
export type ObservedStateEvidence={id:string;contentHash:string;predicate:string;subject:unknown;value:unknown;source:unknown;verificationStatus:string;freshnessExpiresAt:string|Date;qualityScore:number;conflictGroupId:string|null;observedAt:string|Date;attestcoinUscVerified?:boolean};
type MetricRef={metric:keyof typeof OBSERVED_STATE_PREDICATES;evidenceId:string;contentHash:string;predicate:string;provider:string;provenance:"ATTESTCOIN_USC_VERIFIED"|"MOCK_FIXTURE"|"VERIFIED_EVIDENCE";observedAt:string};
const object=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("OBSERVED_STATE_VALUE_INVALID");return value as Record<string,unknown>};
const integer=(value:unknown,min:number,max:number,code:string)=>{if(!Number.isInteger(value)||Number(value)<min||Number(value)>max)throw new Error(code);return Number(value)};
const providerOf=(source:unknown)=>{const value=object(source).provider;if(typeof value!=="string"||value.length<1||value.length>100)throw new Error("OBSERVED_STATE_PROVIDER_INVALID");return value};
const provenanceOf=(row:ObservedStateEvidence):MetricRef["provenance"]=>{const value=object(row.source),provider=providerOf(row.source).toLowerCase();if(provider.startsWith("mock"))return"MOCK_FIXTURE";if(row.attestcoinUscVerified===true&&typeof value.proofSnapshotHash==="string"&&typeof value.verificationRequestHash==="string")return"ATTESTCOIN_USC_VERIFIED";return"VERIFIED_EVIDENCE"};
const subjectMatches=(subject:unknown,treasuryId:string)=>{const value=object(subject);return value.type==="treasury"&&value.id===treasuryId};
export function deriveEvidenceObservedState(args:{manifest:ManifestItem[];evidence:ObservedStateEvidence[];treasuryId:string;minimumQuality:number;now?:Date;maxMetricSkewMs:number}){
  const now=args.now??new Date();if(!Array.isArray(args.manifest)||args.manifest.length===0)throw new Error("OBSERVED_STATE_EVIDENCE_EMPTY");integer(args.minimumQuality,0,100,"OBSERVED_STATE_MINIMUM_QUALITY_INVALID");integer(args.maxMetricSkewMs,1,86_400_000,"OBSERVED_STATE_MAX_SKEW_INVALID");
  const byId=new Map(args.evidence.map(row=>[row.id,row]));const selected=new Map<string,ObservedStateEvidence>();
  for(const item of args.manifest){const row=byId.get(item.evidenceId);if(!row||row.contentHash!==item.contentHash)throw new Error("OBSERVED_STATE_MANIFEST_MISMATCH");if(row.verificationStatus!=="VERIFIED")throw new Error("OBSERVED_STATE_EVIDENCE_NOT_VERIFIED");if(new Date(row.freshnessExpiresAt).getTime()<=now.getTime())throw new Error("OBSERVED_STATE_EVIDENCE_STALE");if(row.qualityScore<args.minimumQuality)throw new Error("OBSERVED_STATE_EVIDENCE_QUALITY_LOW");if(row.conflictGroupId)throw new Error("OBSERVED_STATE_EVIDENCE_CONFLICT");if(Object.values(OBSERVED_STATE_PREDICATES).includes(row.predicate as any)){if(!subjectMatches(row.subject,args.treasuryId))throw new Error("OBSERVED_STATE_TREASURY_MISMATCH");if(selected.has(row.predicate))throw new Error("OBSERVED_STATE_DUPLICATE_METRIC");selected.set(row.predicate,row)}}
  const required=Object.entries(OBSERVED_STATE_PREDICATES)as[keyof typeof OBSERVED_STATE_PREDICATES,string][];for(const[,predicate]of required)if(!selected.has(predicate))throw new Error(`OBSERVED_STATE_METRIC_MISSING:${predicate}`);
  const refs:MetricRef[]=required.map(([metric,predicate])=>{const row=selected.get(predicate)!;return{metric,evidenceId:row.id,contentHash:row.contentHash,predicate,provider:providerOf(row.source),provenance:provenanceOf(row),observedAt:new Date(row.observedAt).toISOString()}});const times=refs.map(ref=>new Date(ref.observedAt).getTime()),observationAt=new Date(Math.max(...times)).toISOString(),skewMs=Math.max(...times)-Math.min(...times);if(skewMs>args.maxMetricSkewMs)throw new Error("OBSERVED_STATE_METRIC_SKEW_EXCEEDED");
  const bps=(predicate:string,max:number,code:string)=>integer(object(selected.get(predicate)!.value).bps,0,max,code);const incidentValue=object(selected.get(OBSERVED_STATE_PREDICATES.criticalIncident)!.value);if(typeof incidentValue.active!=="boolean"||typeof incidentValue.scope!=="string"||incidentValue.scope.length<1||incidentValue.scope.length>200)throw new Error("OBSERVED_STATE_INCIDENT_VALUE_INVALID");
  return{schemaVersion:"treasury.observed-state.v1",treasuryId:args.treasuryId,observationAt,metricSkewMs:skewMs,observedAllocationBps:bps(OBSERVED_STATE_PREDICATES.allocation,10_000,"OBSERVED_ALLOCATION_INVALID"),volatilityBps:bps(OBSERVED_STATE_PREDICATES.volatility,100_000,"OBSERVED_VOLATILITY_INVALID"),liquidityDropBps:bps(OBSERVED_STATE_PREDICATES.liquidityDrop,10_000,"OBSERVED_LIQUIDITY_DROP_INVALID"),pegDeviationBps:bps(OBSERVED_STATE_PREDICATES.pegDeviation,10_000,"OBSERVED_PEG_DEVIATION_INVALID"),criticalIncident:incidentValue.active,criticalIncidentScope:incidentValue.scope,metricEvidenceRefs:refs,mockEvidenceUsed:refs.some(ref=>ref.provenance==="MOCK_FIXTURE"),allMetricsAttestcoinUscVerified:refs.every(ref=>ref.provenance==="ATTESTCOIN_USC_VERIFIED"),historicalPerformanceClaimed:false,causalImpactClaimed:false,advisoryOnly:true,assetExecutionAuthorized:false}as const;
}
