import { applyGovernedSkills,runGovernedSkillBacktest,validateGovernedSkillRule } from "./governed-skill-engine";

const rule={riskRegimes:["VOLATILE","LIQUIDITY_STRESS"] as const,minimumVolatilityBps:300,minimumLiquidityDropBps:0,minimumPegDeviationBps:0,criticalIncidentOnly:false,maxAbsoluteAdjustmentBps:75,forceHold:false};
const advisory={riskRegime:"VOLATILE",safetyState:"DEFENSIVE",suggestedAdjustmentBps:220,blockers:[] as string[],advisoryOnly:true,assetExecutionAuthorized:false};
describe("governed Skill engine",()=>{
  it("deterministically tightens but never increases an advisory",()=>{const skill={id:"skillv_1",contentHash:"0x"+"1".repeat(64),rule:{...rule,riskRegimes:[...rule.riskRegimes]}};const input={volatilityBps:500,liquidityDropBps:100,pegDeviationBps:5,criticalIncident:false};const first=applyGovernedSkills(advisory,input,[skill]),second=applyGovernedSkills(structuredClone(advisory),structuredClone(input),[structuredClone(skill)]);expect(first).toEqual(second);expect(first.suggestedAdjustmentBps).toBe(75);expect(first.skillOverlay.canOnlyTighten).toBe(true);expect(first.assetExecutionAuthorized).toBe(false)});
  it("can force HOLD without granting execution authority",()=>{const output=applyGovernedSkills(advisory,{volatilityBps:500,liquidityDropBps:100,pegDeviationBps:5,criticalIncident:false},[{id:"skillv_hold",contentHash:"0x"+"2".repeat(64),rule:{...rule,riskRegimes:[...rule.riskRegimes],maxAbsoluteAdjustmentBps:0,forceHold:true}}]);expect(output.safetyState).toBe("SKILL_HOLD");expect(output.suggestedAdjustmentBps).toBe(0);expect(output.blockers).toContain("GOVERNED_SKILL_HOLD:skillv_hold")});
  it("requires a zero cap for HOLD and rejects unbounded rules",()=>{expect(()=>validateGovernedSkillRule({...rule,riskRegimes:[...rule.riskRegimes],maxAbsoluteAdjustmentBps:1,forceHold:true})).toThrow("SKILL_HOLD_MUST_HAVE_ZERO_CAP");expect(()=>validateGovernedSkillRule({...rule,riskRegimes:[...rule.riskRegimes],maxAbsoluteAdjustmentBps:10001})).toThrow("INVALID_SKILLMAXABSOLUTEADJUSTMENTBPS")});
  it("passes a fixed no-amplification backtest without historical claims",()=>{const result=runGovernedSkillBacktest({...rule,riskRegimes:[...rule.riskRegimes]});expect(result.passed).toBe(true);expect(result.historicalPerformanceClaimed).toBe(false);expect(result.cases.every(item=>item.neverIncreased)).toBe(true)});
});
