import { BadRequestException,ConflictException,Injectable,NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { PoolClient } from "pg";
import { DatabaseService } from "./database.service";
import { ApproveKnowledgeSourceDto,CreateKnowledgeSourceDto,CreateMemoryCandidateDto,SearchKnowledgeDto,TransitionKnowledgeSourceDto,TransitionMemoryDto } from "./knowledge.dto";
import { chunkKnowledgeDocument,deterministicMockEmbedding,hashText,MOCK_EMBEDDING_MODEL,previewKnowledgeDocument,redactSensitiveContent,retrieveKnowledge,RetrievalCandidate,scanKnowledgeContent } from "./knowledge-engine";

const id=(prefix:string)=>`${prefix}_${randomUUID().replaceAll("-","")}`;
const vector=(values:number[])=>`[${values.join(",")}]`;
const parseVector=(value:string|number[])=>Array.isArray(value)?value:String(value).slice(1,-1).split(",").map(Number);
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`:JSON.stringify(value);
const hash=(value:unknown)=>hashText(canonical(value));

@Injectable()
export class KnowledgeService{
  constructor(private readonly db:DatabaseService){}
  async createSource(org:string,actorId:string,input:CreateKnowledgeSourceDto){
    const scan=scanKnowledgeContent(input.content);if(scan.codes.includes("SECRET_MATERIAL_DETECTED"))throw new BadRequestException("Knowledge content contains prohibited secret material");
    const draftPreview=previewKnowledgeDocument(input.content);
    const redacted=redactSensitiveContent(input.content);const now=new Date();const validFrom=input.validFrom?new Date(input.validFrom):now;const validUntil=input.validUntil?new Date(input.validUntil):null;
    if(validUntil&&validUntil<=validFrom)throw new BadRequestException("Knowledge validity interval is invalid");
    return this.db.transaction(async client=>{
      const prior=await client.query<any>("SELECT id,version FROM knowledge_sources WHERE organization_id=$1 AND source_key=$2 ORDER BY version DESC LIMIT 1 FOR UPDATE",[org,input.sourceKey]);
      if(input.supersedesSourceId&&(!prior.rowCount||prior.rows[0].id!==input.supersedesSourceId))throw new ConflictException("supersedesSourceId must reference the latest source version");
      const sourceId=id("ksource");const versionNumber=(prior.rows[0]?.version??0)+1;const status=scan.codes.includes("PROMPT_INJECTION_DETECTED")?"QUARANTINED":"DRAFT";
      const storedContent=status==="QUARANTINED"?null:redacted;const contentHash=hash({title:input.title,content:storedContent,partition:input.partition,aclRoles:[...new Set(input.aclRoles)].sort(),validFrom:validFrom.toISOString(),validUntil:validUntil?.toISOString()??null});
      await client.query("INSERT INTO knowledge_sources(id,organization_id,source_key,partition,version,title,redacted_content,acl_roles,valid_from,valid_until,supersedes_source_id,conflict_group_id,created_by,scan_result,original_content_hash,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)",[sourceId,org,input.sourceKey,input.partition,versionNumber,input.title,storedContent,JSON.stringify([...new Set(input.aclRoles)].sort()),validFrom,validUntil,input.supersedesSourceId??null,input.conflictGroupId??null,actorId,scan,scan.contentHash,contentHash]);
      await this.sourceEvent(client,org,sourceId,0,status,actorId,status==="QUARANTINED"?"Content quarantined before parsing":"Awaiting human approval");
      await this.audit(client,org,status==="QUARANTINED"?"knowledge.source_quarantined":"knowledge.source_created",sourceId,{version:versionNumber,partition:input.partition,contentHash,scanCodes:scan.codes},actorId);
      return {id:sourceId,organizationId:org,sourceKey:input.sourceKey,version:versionNumber,status,partition:input.partition,contentHash,originalContentHash:scan.contentHash,redactionApplied:redacted!==input.content,embeddingModel:MOCK_EMBEDDING_MODEL,...draftPreview,assetExecutionAuthorized:false};
    });
  }
  async approveSource(org:string,sourceId:string,input:ApproveKnowledgeSourceDto){
    return this.db.transaction(async client=>{
      const source=await this.lockSource(client,org,sourceId);const latest=await this.latestSourceEvent(client,org,sourceId);
      if(latest.status!=="DRAFT")throw new ConflictException("Only a DRAFT knowledge source can be approved");
      const chunks=chunkKnowledgeDocument(source.redacted_content);if(!chunks.length)throw new BadRequestException("Knowledge source produced no chunks");
      for(const chunk of chunks)await client.query("INSERT INTO knowledge_chunks(id,organization_id,source_id,source_version,chunk_index,heading,content,embedding,embedding_model,acl_roles,valid_from,valid_until,conflict_group_id,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8::vector,$9,$10,$11,$12,$13,$14)",[id("kchunk"),org,sourceId,source.version,chunk.index,chunk.heading,chunk.content,vector(chunk.embedding),MOCK_EMBEDDING_MODEL,source.acl_roles,source.valid_from,source.valid_until,source.conflict_group_id,chunk.contentHash]);
      await this.sourceEvent(client,org,sourceId,latest.ordinal+1,"APPROVED",input.actorId,input.rationale);
      if(source.supersedes_source_id){const priorLatest=await this.latestSourceEvent(client,org,source.supersedes_source_id);if(priorLatest.status==="APPROVED")await this.sourceEvent(client,org,source.supersedes_source_id,priorLatest.ordinal+1,"RETIRED",input.actorId,`Superseded by ${sourceId}`)}
      await this.audit(client,org,"knowledge.source_approved",sourceId,{contentHash:source.content_hash,chunkCount:chunks.length,embeddingModel:MOCK_EMBEDDING_MODEL},input.actorId);
      return {id:sourceId,status:"APPROVED",chunkCount:chunks.length,embeddingModel:MOCK_EMBEDDING_MODEL,assetExecutionAuthorized:false};
    });
  }
  async transitionSource(org:string,sourceId:string,input:TransitionKnowledgeSourceDto){return this.db.transaction(async client=>{await this.lockSource(client,org,sourceId);const latest=await this.latestSourceEvent(client,org,sourceId);const allowed:Record<string,string[]>={APPROVED:["RETIRED","DELETION_REQUESTED"],DRAFT:["RETIRED","DELETION_REQUESTED"],RETIRED:["DELETION_REQUESTED"],DELETION_REQUESTED:["DELETED"]};if(!allowed[latest.status]?.includes(input.status))throw new ConflictException(`Knowledge source transition ${latest.status} -> ${input.status} is invalid`);await this.sourceEvent(client,org,sourceId,latest.ordinal+1,input.status,input.actorId,input.rationale);await this.audit(client,org,`knowledge.source_${input.status.toLowerCase()}`,sourceId,{previousStatus:latest.status,indexExcluded:input.status!=="RETIRED"?true:true},input.actorId);return {id:sourceId,status:input.status,indexExcluded:true,physicalBackupDeletionPending:input.status==="DELETED",assetExecutionAuthorized:false}})}
  async search(org:string,role:string,input:SearchKnowledgeDto){
    const chunks=await this.db.query<any>(`SELECT c.*,c.embedding::text AS embedding_text,s.partition FROM knowledge_chunks c JOIN knowledge_sources s ON s.id=c.source_id WHERE c.organization_id=$1 AND c.acl_roles ? $2 AND c.valid_from<=now() AND (c.valid_until IS NULL OR c.valid_until>now()) AND (SELECT e.status FROM knowledge_source_events e WHERE e.organization_id=c.organization_id AND e.source_id=c.source_id ORDER BY e.ordinal DESC LIMIT 1)='APPROVED'`,[org,role]);
    const memories=await this.db.query<any>(`SELECT m.*,m.embedding::text AS embedding_text FROM organization_memories m WHERE m.organization_id=$1 AND m.acl_roles ? $2 AND (m.valid_until IS NULL OR m.valid_until>now()) AND (SELECT e.status FROM memory_events e WHERE e.organization_id=m.organization_id AND e.memory_id=m.id ORDER BY e.ordinal DESC LIMIT 1)='APPROVED'`,[org,role]);
    const candidates:RetrievalCandidate[]=[...chunks.rows.map(row=>({id:row.id,sourceId:row.source_id,sourceVersion:row.source_version,partition:row.partition,heading:row.heading,content:row.content,contentHash:row.content_hash,embedding:parseVector(row.embedding_text),validUntil:row.valid_until?new Date(row.valid_until).toISOString():null,conflictGroupId:row.conflict_group_id})),...memories.rows.map(row=>({id:row.id,sourceId:row.id,sourceVersion:1,partition:"ORGANIZATION_MEMORY" as const,heading:`${row.memory_type} memory`,content:row.content,contentHash:row.content_hash,embedding:parseVector(row.embedding_text),validUntil:row.valid_until?new Date(row.valid_until).toISOString():null,conflictGroupId:null}))];
    const result=retrieveKnowledge(input.query,candidates,input.limit);return {...result,organizationId:org,role,candidateCount:candidates.length};
  }
  async createMemory(org:string,actorId:string,input:CreateMemoryCandidateDto){
    const scan=scanKnowledgeContent(input.content);if(!scan.safe)throw new BadRequestException(`Memory content rejected: ${scan.codes.join(",")}`);
    const references=await this.db.query<any>("SELECT id FROM evidence WHERE organization_id=$1 AND id=ANY($2::text[]) UNION SELECT id FROM decisions WHERE organization_id=$1 AND id=ANY($2::text[]) UNION SELECT id FROM knowledge_sources WHERE organization_id=$1 AND id=ANY($2::text[])",[org,input.sourceRefs]);
    if(new Set(references.rows.map(row=>row.id)).size!==new Set(input.sourceRefs).size)throw new NotFoundException("One or more memory source references were not found in this organization");
    const content=redactSensitiveContent(input.content);const memoryId=id("memory");const contentHash=hash({content,sourceRefs:[...new Set(input.sourceRefs)].sort(),memoryType:input.memoryType});
    await this.db.transaction(async client=>{await client.query("INSERT INTO organization_memories(id,organization_id,memory_type,content,source_refs,acl_roles,valid_until,supersedes_memory_id,author_id,content_hash,embedding,embedding_model) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::vector,$12)",[memoryId,org,input.memoryType,content,JSON.stringify([...new Set(input.sourceRefs)].sort()),JSON.stringify([...new Set(input.aclRoles)].sort()),input.validUntil??null,input.supersedesMemoryId??null,actorId,contentHash,vector(deterministicMockEmbedding(content)),MOCK_EMBEDDING_MODEL]);await this.memoryEvent(client,org,memoryId,0,"CANDIDATE",actorId,"Automatically or manually extracted memory awaits approval");await this.audit(client,org,"memory.candidate_created",memoryId,{memoryType:input.memoryType,contentHash,sourceRefs:input.sourceRefs},actorId)});
    return {id:memoryId,status:"CANDIDATE",contentHash,embeddingModel:MOCK_EMBEDDING_MODEL,canInfluenceHighRiskDecision:false,assetExecutionAuthorized:false};
  }
  async transitionMemory(org:string,memoryId:string,input:TransitionMemoryDto){return this.db.transaction(async client=>{const found=await client.query<any>("SELECT * FROM organization_memories WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,memoryId]);if(!found.rowCount)throw new NotFoundException("Memory not found");const latest=await this.latestMemoryEvent(client,org,memoryId);const allowed:Record<string,string[]>={CANDIDATE:["APPROVED","REJECTED","DELETION_REQUESTED"],APPROVED:["EXPIRED","SUPERSEDED","DELETION_REQUESTED"],DELETION_REQUESTED:["DELETED"]};if(!allowed[latest.status]?.includes(input.status))throw new ConflictException(`Memory transition ${latest.status} -> ${input.status} is invalid`);if(input.status==="APPROVED"&&found.rows[0].valid_until&&new Date(found.rows[0].valid_until)<=new Date())throw new ConflictException("Expired memory cannot be approved");await this.memoryEvent(client,org,memoryId,latest.ordinal+1,input.status,input.actorId,input.rationale);if(input.status==="APPROVED"&&found.rows[0].supersedes_memory_id){const prior=await this.latestMemoryEvent(client,org,found.rows[0].supersedes_memory_id);if(prior.status==="APPROVED")await this.memoryEvent(client,org,found.rows[0].supersedes_memory_id,prior.ordinal+1,"SUPERSEDED",input.actorId,`Superseded by ${memoryId}`)}await this.audit(client,org,`memory.${input.status.toLowerCase()}`,memoryId,{previousStatus:latest.status,indexExcluded:input.status!=="APPROVED"},input.actorId);return {id:memoryId,status:input.status,canInfluenceHighRiskDecision:input.status==="APPROVED",indexExcluded:input.status!=="APPROVED",assetExecutionAuthorized:false}})}
  private async lockSource(client:PoolClient,org:string,sourceId:string){const found=await client.query<any>("SELECT * FROM knowledge_sources WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,sourceId]);if(!found.rowCount)throw new NotFoundException("Knowledge source not found");return found.rows[0]}
  private async latestSourceEvent(client:PoolClient,org:string,sourceId:string){const found=await client.query<any>("SELECT ordinal,status FROM knowledge_source_events WHERE organization_id=$1 AND source_id=$2 ORDER BY ordinal DESC LIMIT 1 FOR UPDATE",[org,sourceId]);if(!found.rowCount)throw new NotFoundException("Knowledge source status not found");return found.rows[0]}
  private async latestMemoryEvent(client:PoolClient,org:string,memoryId:string){const found=await client.query<any>("SELECT ordinal,status FROM memory_events WHERE organization_id=$1 AND memory_id=$2 ORDER BY ordinal DESC LIMIT 1 FOR UPDATE",[org,memoryId]);if(!found.rowCount)throw new NotFoundException("Memory status not found");return found.rows[0]}
  private sourceEvent(client:PoolClient,org:string,sourceId:string,ordinal:number,status:string,actorId:string,rationale:string){const payload={sourceId,ordinal,status,actorId,rationale};return client.query("INSERT INTO knowledge_source_events(id,organization_id,source_id,ordinal,status,actor_id,rationale,payload_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id("ksevent"),org,sourceId,ordinal,status,actorId,rationale,hash(payload)])}
  private memoryEvent(client:PoolClient,org:string,memoryId:string,ordinal:number,status:string,actorId:string,rationale:string){const payload={memoryId,ordinal,status,actorId,rationale};return client.query("INSERT INTO memory_events(id,organization_id,memory_id,ordinal,status,actor_id,rationale,payload_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id("mevent"),org,memoryId,ordinal,status,actorId,rationale,hash(payload)])}
  private audit(client:PoolClient,org:string,eventType:string,objectId:string,data:unknown,actorId:string){const payload={eventType,organizationId:org,objectId,data};return client.query("INSERT INTO audit_events(id,organization_id,event_type,actor,action,object_type,object_id,data,payload_hash) VALUES($1,$2,$3,$4,$5,'knowledge',$6,$7,$8)",[id("audit"),org,eventType,{type:"human",id:actorId},eventType,objectId,data,hash(payload)])}
}
