import { Interface, ZeroHash, getAddress, keccak256 } from "ethers";
import { hashValue } from "./decision-engine";

const governorInterface = new Interface(["function execute(address[] targets,uint256[] values,bytes[] calldatas,bytes32 descriptionHash) payable returns(uint256)"]);
const fail = (code: string): never => { throw new Error(code); };
const lower = (value: string) => value.toLowerCase();
type Tx = { chainId:number; from:string; to:string; value:"0x0"; data:string; dataHash:string };
export type HoldQueueArtifact = { artifactHash:string; lineage:{ proposalArtifactHash:string; voteFinalityStatus:string; proposalId:string; attemptNumber:number; voteTransactionHash:string }; proposal:{ targets:string[]; values:string[]; calldatas:string[]; descriptionHash:string; action:{ function:string; paused:boolean; target:string; value:string } }; unsignedTransaction:Tx };
export type HoldQueueObservation = { chainId:number; latestBlock:number; latestTimestamp:number; transaction:{ hash:string; from:string; to:string; value:string; data:string; status:number; blockNumber:number; blockHash:string; canonicalBlockHash:string; canonicalTransactionHashes:string[] }; proposalQueued:{ address:string; proposalId:string; etaSeconds:string }; callScheduled:{ address:string; operationId:string; index:string; target:string; value:string; data:string; predecessor:string; delay:string }; governance:{ state:number; proposalEta:string }; timelock:{ address:string; minimumDelay:string; timestamp:string; pending:boolean; ready:boolean; done:boolean } };

export function verifyDecisionBoundHoldQueueFinality(frozen: HoldQueueArtifact, observed: HoldQueueObservation) {
  const tx=frozen.unsignedTransaction,o=observed.transaction;
  if(frozen.lineage.voteFinalityStatus!=="HOLD_VOTE_SUCCEEDED"||frozen.lineage.attemptNumber!==3||frozen.proposal.action.function!=="setPaused(bool)"||frozen.proposal.action.paused!==true)fail("GOVERNANCE_HOLD_QUEUE_LINEAGE_INVALID");
  if(observed.chainId!==tx.chainId||o.status!==1||getAddress(o.from).toLowerCase()!==getAddress(tx.from).toLowerCase()||getAddress(o.to).toLowerCase()!==getAddress(tx.to).toLowerCase()||BigInt(o.value)!==0n||lower(o.data)!==lower(tx.data)||lower(keccak256(o.data))!==lower(tx.dataHash))fail("GOVERNANCE_HOLD_QUEUE_TRANSACTION_MISMATCH");
  if(lower(o.blockHash)!==lower(o.canonicalBlockHash)||!o.canonicalTransactionHashes.some((hash)=>lower(hash)===lower(o.hash))||observed.latestBlock<o.blockNumber)fail("GOVERNANCE_HOLD_QUEUE_NON_CANONICAL");
  const pq=observed.proposalQueued,cs=observed.callScheduled;
  if(getAddress(pq.address).toLowerCase()!==getAddress(tx.to).toLowerCase()||pq.proposalId!==frozen.lineage.proposalId)fail("GOVERNANCE_HOLD_QUEUE_PROPOSAL_EVENT_INVALID");
  if(getAddress(cs.address).toLowerCase()!==getAddress(observed.timelock.address).toLowerCase()||cs.index!=="0"||getAddress(cs.target).toLowerCase()!==getAddress(frozen.proposal.targets[0]).toLowerCase()||cs.value!==frozen.proposal.values[0]||lower(cs.data)!==lower(frozen.proposal.calldatas[0])||lower(cs.predecessor)!==lower(ZeroHash)||cs.delay!=="60")fail("GOVERNANCE_HOLD_QUEUE_TIMELOCK_EVENT_INVALID");
  if(observed.governance.state!==5||observed.governance.proposalEta!==pq.etaSeconds||observed.timelock.minimumDelay!=="60"||observed.timelock.timestamp!==pq.etaSeconds||observed.timelock.done||(!observed.timelock.pending&&!observed.timelock.ready))fail("GOVERNANCE_HOLD_QUEUE_STATE_INVALID");
  return { schemaVersion:"aeos.live-governance-hold-queue-finality.v1", status:observed.timelock.ready?"HOLD_TIMELOCK_READY":"HOLD_QUEUED_WAITING", queueArtifactHash:frozen.artifactHash, proposalArtifactHash:frozen.lineage.proposalArtifactHash, proposalId:frozen.lineage.proposalId, attemptNumber:3, chainId:observed.chainId, transaction:{hash:o.hash,blockNumber:o.blockNumber,blockHash:o.blockHash,confirmations:observed.latestBlock-o.blockNumber+1}, governance:{state:"Queued",proposalEta:pq.etaSeconds}, timelock:{address:getAddress(observed.timelock.address).toLowerCase(),operationId:cs.operationId,minimumDelaySeconds:60,timestamp:observed.timelock.timestamp,ready:observed.timelock.ready,pending:observed.timelock.pending,done:false,observedTimestamp:observed.latestTimestamp}, checks:{exactQueueTransaction:true,canonicalInclusion:true,exactProposalQueuedEvent:true,exactCallScheduledEvent:true,minimumDelay:true}, controls:{privateKeyReceived:false,signerCustody:false,broadcastCapability:false,assetExecutionAuthorized:false} } as const;
}

export function buildDecisionBoundHoldExecute(frozen:HoldQueueArtifact,finality:ReturnType<typeof verifyDecisionBoundHoldQueueFinality>,recordedAt:string){
  if(!Number.isFinite(Date.parse(recordedAt))||finality.status!=="HOLD_TIMELOCK_READY"||!finality.timelock.ready||finality.timelock.done||finality.queueArtifactHash!==frozen.artifactHash||finality.proposalId!==frozen.lineage.proposalId)fail("GOVERNANCE_HOLD_EXECUTE_TIMELOCK_NOT_READY");
  const data=governorInterface.encodeFunctionData("execute",[frozen.proposal.targets,frozen.proposal.values.map(BigInt),frozen.proposal.calldatas,frozen.proposal.descriptionHash]),tx=frozen.unsignedTransaction,core={schemaVersion:"aeos.live-governance-hold-execute.v1",status:"HOLD_EXECUTE_REQUEST_PREPARED",recordedAt:new Date(recordedAt).toISOString(),lineage:{queueArtifactHash:frozen.artifactHash,queueTransactionHash:finality.transaction.hash,proposalArtifactHash:frozen.lineage.proposalArtifactHash,proposalId:frozen.lineage.proposalId,attemptNumber:3,timelockOperationId:finality.timelock.operationId,timelockTimestamp:finality.timelock.timestamp},proposal:{...frozen.proposal},unsignedTransaction:{chainId:tx.chainId,from:tx.from,to:tx.to,value:"0x0" as const,data,dataHash:keccak256(data)},controls:{requiresUserWalletConfirmation:true,signed:false,submitted:false,privateKeyReceived:false,signerCustody:false,broadcastCapability:false,treasuryAssetMovement:false,assetExecutionAuthorized:false}};
  return {...core,artifactHash:hashValue(core)};
}
