import { Interface } from "ethers";
import { buildVotingPeriodRecoveryQueue, RecoveryArtifact, RecoveryChainObservation, verifyVotingPeriodRecoveryFinality } from "./live-governance-recovery-finality";
const h=(c:string)=>`0x${c.repeat(64)}`,governor="0x1111111111111111111111111111111111111111",voter="0x2222222222222222222222222222222222222222",target=governor;
const request=(data:string,hash:string)=>({chainId:102031,from:voter,to:governor,value:"0x0" as const,data,dataHash:hash});
const frozen:RecoveryArtifact={artifactHash:h("a"),proposal:{proposalId:"123",description:"recover",descriptionHash:h("b"),targets:[target],values:["0"],calldatas:["0x1234"],action:{previousVotingPeriodBlocks:8,newVotingPeriodBlocks:240}},votingCapacity:{quorumVotes:"40000",voterVotes:"1000000",voterDelegate:voter,singleWalletMeetsQuorum:true},unsignedRequests:{propose:request("0x1234","0x56570de287d73cd1cb6092bb8fdee6173974955fdef345ae579ee9f475ea7432"),voteFor:{...request("0xabcd","0xdbe576b4818846aa77e82f4ed5fa78f92766b141f282d36703886d196df39322"),support:1}}};
const tx=(hash:string,data:string,block:number):any=>({hash,from:voter,to:governor,value:"0",data,status:1,blockNumber:block,blockHash:h("c"),canonicalBlockHash:h("c"),canonicalTransactionHashes:[hash]});
const observation=():RecoveryChainObservation=>({chainId:102031,latestBlock:120,proposalTransaction:tx(h("d"),"0x1234",100),voteTransaction:tx(h("e"),"0xabcd",104),proposalEvent:{address:governor,proposalId:"123",proposer:voter,targets:[target],values:["0"],signatures:[""],calldatas:["0x1234"],voteStart:"101",voteEnd:"109",description:"recover"},voteEvent:{address:governor,voter,proposalId:"123",support:1,weight:"1000000",reason:""},governance:{state:4,snapshot:"101",deadline:"109",quorum:"40000",againstVotes:"0",forVotes:"1000000",abstainVotes:"0",proposalNeedsQueuing:true,currentVotingPeriodBlocks:"8"}});
describe("governance recovery finality and queue",()=>{
  it("verifies exact successful proposal, vote and quorum",()=>expect(verifyVotingPeriodRecoveryFinality(frozen,observation())).toMatchObject({status:"RECOVERY_VOTE_SUCCEEDED",governance:{state:"Succeeded",quorumMet:true},controls:{assetExecutionAuthorized:false}}));
  it("fails closed on under-quorum or wrong vote support",()=>{expect(()=>verifyVotingPeriodRecoveryFinality(frozen,{...observation(),governance:{...observation().governance,forVotes:"1"}})).toThrow("GOVERNANCE_RECOVERY_NOT_SUCCEEDED");expect(()=>verifyVotingPeriodRecoveryFinality(frozen,{...observation(),voteEvent:{...observation().voteEvent,support:0}})).toThrow("GOVERNANCE_RECOVERY_VOTE_EVENT_INVALID")});
  it("builds only an unsigned zero-value queue request after verified success",()=>{const finality=verifyVotingPeriodRecoveryFinality(frozen,observation()),queue=buildVotingPeriodRecoveryQueue(frozen,finality,"2026-08-23T00:00:00Z"),iface=new Interface(["function queue(address[],uint256[],bytes[],bytes32)"]);expect(iface.parseTransaction({data:queue.unsignedTransaction.data})?.name).toBe("queue");expect(queue).toMatchObject({status:"RECOVERY_QUEUE_REQUEST_PREPARED",unsignedTransaction:{value:"0x0"},controls:{signed:false,broadcastCapability:false,assetExecutionAuthorized:false}})});
});
