import { buildLiveBalanceObserverChildDecisionArtifact } from "./live-balance-observer-child-decision";
import { decisionRoles } from "./decision-engine";
import { buildRoleRetrievalManifestBundle } from "./retrieval-manifest";

const bundle = buildRoleRetrievalManifestBundle(Object.fromEntries(decisionRoles.map((role) => [role,{query:`${role} query`,result:{status:"AVAILABLE",reasonCode:null,hasConflicts:false,embeddingModel:"deterministic",rerankerVersion:"v1",items:[{citation:`rag:${role}`,sourceId:`source-${role}`,sourceVersion:1,chunkId:`chunk-${role}`,chunkOrdinal:0,contentHash:`hash-${role}`,scoreComponents:{keyword:1,vector:0,trust:1,freshness:1},score:3,excerpt:`${role} context`}],assetExecutionAuthorized:false}}])) as any);
const rows = bundle.manifests.map((item:any) => ({role:item.role,query_hash:item.queryHash,manifest_hash:item.manifestHash,items:item.items}));
const positions = decisionRoles.map((role) => ({role,position:`${role} HOLD`,citations:["old"],knowledgeCitations:[`rag:${role}`]}));
const parent:any = {id:"parent",revisionNumber:1,evidenceSnapshotId:"parent-snap",evidenceManifestHash:"parent-hash",retrievalBundleHash:bundle.bundleHash,retrievalManifests:rows,recommendation:{recommendation:"INSUFFICIENT_EVIDENCE",actions:[],agentPositions:positions,challenges:[],assetExecutionAuthorized:false,humanApprovalRequired:true},agentRuns:Array(8).fill({}),agentMessages:[]};
const child:any = {...parent,id:"child",parentDecisionId:"parent",revisionNumber:2,evidenceSnapshotId:"child-snap",evidenceManifestHash:"child-hash",retrievalManifests:rows.map((row:any) => ({...row,items:row.items.map((item:any) => ({...item}))})),recommendation:{...parent.recommendation,agentPositions:positions.map((position) => ({...position,citations:["old","new"]}))}};
const input:any = {recordedAt:"2026-08-26T00:00:00.000Z",parent,child,parentSnapshot:{id:"parent-snap",manifestHash:"parent-hash",evidenceIds:["old"]},childSnapshot:{id:"child-snap",manifestHash:"child-hash",evidenceIds:["new","old"]},newEvidence:{id:"new",contentHash:"hash",predicate:"asset.balance",freshnessStatus:"STALE",verificationStatus:"VERIFIED"}};

describe("live balance child Decision", () => {
  it("freezes inherited RAG and adds the balance citation to exactly eight roles", () => { const result:any = buildLiveBalanceObserverChildDecisionArtifact(input); expect(result.retrieval.roleComparisons).toHaveLength(8); expect(result.retrieval.roleComparisons.every((item:any) => item.evidenceCitations.added[0] === "new")).toBe(true); expect(result.controls.assetExecutionAuthorized).toBe(false); });
  it("accepts the first-create camelCase Manifest representation without weakening hash equality", () => { const firstCreate = structuredClone(input); firstCreate.child.retrievalManifests = firstCreate.child.retrievalManifests.map((item:any) => ({...item,manifestHash:item.manifest_hash,queryHash:item.query_hash,manifest_hash:undefined,query_hash:undefined})); expect(() => buildLiveBalanceObserverChildDecisionArtifact(firstCreate)).not.toThrow(); });
  it("rejects RAG mutation and predicate promotion", () => { const changed = structuredClone(input); changed.child.retrievalManifests[0].manifest_hash = "forged"; expect(() => buildLiveBalanceObserverChildDecisionArtifact(changed)).toThrow("BALANCE_CHILD_RAG_MUTATED_Governor"); const wrong = structuredClone(input); wrong.newEvidence.predicate = "asset.price"; expect(() => buildLiveBalanceObserverChildDecisionArtifact(wrong)).toThrow("BALANCE_CHILD_EVIDENCE_BOUNDARY_INVALID"); });
});
