import { buildLiveEvidenceAnchorConfirmationArtifact } from "./live-evidence-anchor-confirmation";

const step9: any = { schemaVersion: "aeos.live-attestcoin-step.v1", step: 9, status: "ANCHOR_REQUEST_PREPARED", artifactHash: `0x${"11".repeat(32)}`, lineage: { attestcoinProofJobId: "job_live", decisionId: "decision_live", decisionOutputHash: `0x${"22".repeat(32)}`, evidenceSnapshotId: "snap_live", evidenceSnapshotHash: `0x${"33".repeat(32)}` }, handoff: { id: "handoff_live", manifestHash: `0x${"44".repeat(32)}`, commitmentId: `0x${"55".repeat(32)}`, decisionKey: `0x${"66".repeat(32)}` }, unsignedTransaction: { chainId: 102031, from: "0x444d510728fb8072351cb5d0e88432e6a8501dfa", to: "0x5de85313c5622e3707c3fed8932f51e5991e62c2", value: "0x0", dataHash: `0x${"77".repeat(32)}` } };
const step10: any = { schemaVersion: "aeos.live-attestcoin-step.v1", step: 10, status: "ANCHOR_WALLET_SUBMITTED", step9ArtifactHash: step9.artifactHash, handoffId: step9.handoff.id, commitmentId: step9.handoff.commitmentId, calldataHash: step9.unsignedTransaction.dataHash, chainId: 102031, from: step9.unsignedTransaction.from, to: step9.unsignedTransaction.to, value: "0x0", transactionHash: `0x${"88".repeat(32)}` };
const confirmation: any = { id: "confirmation_live", handoffId: step9.handoff.id, decisionId: step9.lineage.decisionId, evidenceSnapshotId: step9.lineage.evidenceSnapshotId, commitmentId: step9.handoff.commitmentId, transactionHash: step10.transactionHash, snapshotHash: `0x${"99".repeat(32)}`, snapshot: { schemaVersion: "evidence.anchor.confirmation.v1", chainId: 102031, transactionHash: step10.transactionHash, blockNumber: 10, blockHash: `0x${"aa".repeat(32)}`, from: step10.from, to: step10.to, status: 1, confirmations: 3, minimumConfirmations: 2, observedAt: "2026-08-23T00:00:00.000Z", commitmentId: step9.handoff.commitmentId, decisionKey: step9.handoff.decisionKey, snapshotHash: step9.lineage.evidenceSnapshotHash, eventVerified: true, calldataVerified: true, zeroValueVerified: true, signerCustody: false, broadcastCapability: false, assetExecutionAuthorized: false } };

describe("live Step 11 Evidence Anchor confirmation", () => {
  it("freezes a canonical exact event while withholding authority", () => expect(buildLiveEvidenceAnchorConfirmationArtifact({ recordedAt: "2026-08-23T00:00:00.000Z", step9, step10, confirmation })).toMatchObject({ step: 11, status: "EVIDENCE_ANCHORED", chainReceipt: { transactionHash: step10.transactionHash, eventVerified: true, zeroValueVerified: true }, controls: { canonicalReceiptVerified: true, assetExecutionAuthorized: false }, truthBoundary: { decisionOutputHashDirectlyAnchoredOnChain: false, payloadEconomicTruthVerified: false } }));
  it("rejects a substituted wallet transaction", () => expect(() => buildLiveEvidenceAnchorConfirmationArtifact({ recordedAt: "2026-08-23T00:00:00.000Z", step9, step10: { ...step10, to: "0x1111111111111111111111111111111111111111" }, confirmation })).toThrow("LIVE_STEP_11_SUBMISSION_TRANSACTION_MISMATCH"));
  it("rejects a missing or under-final event", () => expect(() => buildLiveEvidenceAnchorConfirmationArtifact({ recordedAt: "2026-08-23T00:00:00.000Z", step9, step10, confirmation: { ...confirmation, snapshot: { ...confirmation.snapshot, confirmations: 1 } } })).toThrow("LIVE_STEP_11_RECEIPT_NOT_FINAL"));
});
