import { Interface, keccak256 } from "ethers";
import { buildDecisionBoundHoldQueue, HoldProposalForQueue, HoldVoteArtifactForFinality, HoldVoteChainObservation, verifyDecisionBoundHoldVoteFinality } from "./live-governance-hold-vote-finality";

const h=(c:string)=>`0x${c.repeat(64)}`, governor="0x1111111111111111111111111111111111111111", voter="0x2222222222222222222222222222222222222222", guard="0x3333333333333333333333333333333333333333";
const voteData=new Interface(["function castVote(uint256,uint8)"]).encodeFunctionData("castVote",[123n,1]);
const proposal:HoldProposalForQueue={artifactHash:h("a"),lineage:{attempt:{attemptNumber:3,attemptIdentity:h("b")}},proposal:{proposalId:"123",descriptionHash:h("c"),targets:[guard],values:["0"],calldatas:["0x1234"],action:{function:"setPaused(bool)",paused:true,target:guard,value:"0"}},unsignedTransaction:{chainId:102031,from:voter,to:governor,value:"0x0",data:"0xabcd",dataHash:keccak256("0xabcd")}};
const vote:HoldVoteArtifactForFinality={artifactHash:h("d"),lineage:{proposalArtifactHash:h("a"),proposalId:"123",attemptNumber:3,attemptIdentity:h("b")},votingCapacity:{voterVotes:"1000000",quorumVotes:"40000",voter},unsignedTransaction:{chainId:102031,from:voter,to:governor,value:"0x0",data:voteData,dataHash:keccak256(voteData),support:1}};
const observation=(state=1):HoldVoteChainObservation=>({chainId:102031,latestBlock:120,voteTransaction:{hash:h("e"),from:voter,to:governor,value:"0",data:voteData,status:1,blockNumber:110,blockHash:h("f"),canonicalBlockHash:h("f"),canonicalTransactionHashes:[h("e")]},voteEvent:{address:governor,voter,proposalId:"123",support:1,weight:"1000000",reason:""},governance:{state,snapshot:"101",deadline:"341",quorum:"40000",againstVotes:"0",forVotes:"1000000",abstainVotes:"0",proposalNeedsQueuing:true,hasVoted:true,currentVotingPeriodBlocks:"240"}});

describe("Decision-bound HOLD vote finality",()=>{
  it("verifies VoteCast and quorum while keeping an active window distinct",()=>expect(verifyDecisionBoundHoldVoteFinality(proposal,vote,observation())).toMatchObject({status:"HOLD_VOTE_CAST_QUORUM_MET_WINDOW_ACTIVE",governance:{state:"Active",quorumMet:true,proposalNeedsQueuing:true},controls:{assetExecutionAuthorized:false}}));
  it("rejects wrong support, under-quorum and non-canonical observations",()=>{expect(()=>verifyDecisionBoundHoldVoteFinality(proposal,vote,{...observation(),voteEvent:{...observation().voteEvent,support:0}})).toThrow("GOVERNANCE_HOLD_VOTE_EVENT_INVALID");expect(()=>verifyDecisionBoundHoldVoteFinality(proposal,vote,{...observation(),governance:{...observation().governance,forVotes:"1"}})).toThrow("GOVERNANCE_HOLD_VOTE_OR_QUORUM_INVALID");expect(()=>verifyDecisionBoundHoldVoteFinality(proposal,vote,{...observation(),voteTransaction:{...observation().voteTransaction,canonicalBlockHash:h("1")}})).toThrow("GOVERNANCE_HOLD_VOTE_NON_CANONICAL")});
  it("builds Queue only after the voting window reaches Succeeded",()=>{const active=verifyDecisionBoundHoldVoteFinality(proposal,vote,observation());expect(()=>buildDecisionBoundHoldQueue(proposal,active,"2026-08-24T00:00:00Z")).toThrow("GOVERNANCE_HOLD_QUEUE_LINEAGE_INVALID");const succeeded=verifyDecisionBoundHoldVoteFinality(proposal,vote,observation(4)),queue=buildDecisionBoundHoldQueue(proposal,succeeded,"2026-08-24T00:00:00Z");expect(queue).toMatchObject({status:"HOLD_QUEUE_REQUEST_PREPARED",unsignedTransaction:{value:"0x0"},controls:{broadcastCapability:false,assetExecutionAuthorized:false}})});
});
