import { Injectable, Optional } from "@nestjs/common";
import { DatabaseService } from "./database.service";
import { CockpitProjectionService } from "./cockpit-projection.service";

const requiredMigration="043_cockpit_projection_notifications.sql";
@Injectable()
export class OperationalHealthService{
  constructor(private readonly db:DatabaseService,@Optional() private readonly cockpit?:CockpitProjectionService){}
  liveness(){return {service:"api",status:"live",version:"0.1.0",uptimeSeconds:Math.floor(process.uptime()),timestamp:new Date().toISOString()}}
  async readiness(){const started=Date.now();try{const result=await this.db.query("SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version=$1) AS migrated",[requiredMigration]);const migrated=result.rows[0]?.migrated===true;return {service:"api",status:migrated?"ready":"not_ready",checks:{database:true,requiredMigration,migrationsCurrent:migrated},latencyMs:Date.now()-started,timestamp:new Date().toISOString(),tenantDataExposed:false}}catch{return {service:"api",status:"not_ready",checks:{database:false,requiredMigration,migrationsCurrent:false},latencyMs:Date.now()-started,timestamp:new Date().toISOString(),tenantDataExposed:false}}}
  async metrics(){const started=Date.now();const result=await this.db.runAsSystem(()=>this.db.query(`SELECT
    (SELECT count(*)::int FROM decision_jobs WHERE status IN('QUEUED','RUNNING')) AS decision_jobs_active,
    (SELECT count(*)::int FROM evidence WHERE freshness_expires_at<=now()) AS evidence_stale,
    (SELECT count(*)::int FROM execution_reconciliation_attempts WHERE outcome='FAILED_RETRYABLE') AS reconciliation_retryable,
    (SELECT count(*)::int FROM execution_reconciliation_attempts WHERE outcome='FAILED_TERMINAL') AS reconciliation_terminal,
    (SELECT count(*)::int FROM outbox_deliveries WHERE status IN('PENDING','CLAIMED')) AS outbox_deliveries_active,
    (SELECT count(*)::int FROM outbox_deliveries WHERE status='FAILED') AS outbox_deliveries_failed,
    (SELECT count(*)::int FROM alerts WHERE severity='CRITICAL') AS alerts_critical,
    (SELECT count(*)::int FROM alerts a WHERE NOT EXISTS(SELECT 1 FROM alert_acknowledgements aa WHERE aa.organization_id=a.organization_id AND aa.alert_id=a.id)) AS alerts_unacknowledged,
    (SELECT count(*)::int FROM safe_transaction_observations WHERE state='EXECUTED' AND onchain_execution_confirmed=true) AS safe_executions_confirmed,
    (SELECT count(*)::int FROM provider_call_observations) AS provider_calls,
    (SELECT count(*)::int FROM provider_call_observations WHERE outcome IN('RETRYABLE_FAILURE','NON_RETRYABLE_FAILURE')) AS provider_failures,
    (SELECT count(*)::int FROM provider_call_observations WHERE outcome='CIRCUIT_OPEN') AS provider_circuit_rejections,
    (SELECT count(*)::int FROM advisory_provider_observations) AS advisory_provider_calls,
    (SELECT count(*)::int FROM advisory_provider_observations WHERE outcome<>'SUCCESS') AS advisory_provider_failures,
    (SELECT count(*)::int FROM advisory_provider_observations WHERE outcome='CIRCUIT_OPEN') AS advisory_provider_circuit_rejections,
    (SELECT count(*)::int FROM cockpit_stream_leases WHERE expires_at>now()) AS cockpit_sse_distributed_active`));
    const row=result.rows[0],streams=this.cockpit?.operationalMetrics()??{activeStreams:0,connectionsTotal:0,rejectionsTotal:0,maxConnectionsTotal:0,maxConnectionsPerOrganization:0,fanoutListenerConnected:0,fanoutNotificationsTotal:0,fanoutRejectedNotificationsTotal:0,fanoutReconnectsTotal:0};return {databaseLatencyMs:Date.now()-started,decisionJobsActive:Number(row.decision_jobs_active),evidenceStale:Number(row.evidence_stale),reconciliationRetryable:Number(row.reconciliation_retryable),reconciliationTerminal:Number(row.reconciliation_terminal),outboxDeliveriesActive:Number(row.outbox_deliveries_active),outboxDeliveriesFailed:Number(row.outbox_deliveries_failed),alertsCritical:Number(row.alerts_critical),alertsUnacknowledged:Number(row.alerts_unacknowledged),safeExecutionsConfirmed:Number(row.safe_executions_confirmed),providerCalls:Number(row.provider_calls),providerFailures:Number(row.provider_failures),providerCircuitRejections:Number(row.provider_circuit_rejections),advisoryProviderCalls:Number(row.advisory_provider_calls),advisoryProviderFailures:Number(row.advisory_provider_failures),advisoryProviderCircuitRejections:Number(row.advisory_provider_circuit_rejections),cockpitStreamsActive:streams.activeStreams,cockpitStreamsDistributedActive:Number(row.cockpit_sse_distributed_active),cockpitStreamConnectionsTotal:streams.connectionsTotal,cockpitStreamRejectionsTotal:streams.rejectionsTotal,cockpitStreamCapacityTotal:streams.maxConnectionsTotal,cockpitStreamCapacityPerOrganization:streams.maxConnectionsPerOrganization,cockpitFanoutListenerConnected:streams.fanoutListenerConnected,cockpitFanoutNotificationsTotal:streams.fanoutNotificationsTotal,cockpitFanoutRejectedNotificationsTotal:streams.fanoutRejectedNotificationsTotal,cockpitFanoutReconnectsTotal:streams.fanoutReconnectsTotal}
  }
  renderPrometheus(snapshot:Awaited<ReturnType<OperationalHealthService["metrics"]>>){const values:Record<string,number>={aeos_api_up:1,aeos_api_uptime_seconds:Math.floor(process.uptime()),aeos_database_query_duration_milliseconds:snapshot.databaseLatencyMs,aeos_decision_jobs_active:snapshot.decisionJobsActive,aeos_evidence_stale_total:snapshot.evidenceStale,aeos_execution_reconciliation_retryable_total:snapshot.reconciliationRetryable,aeos_execution_reconciliation_terminal_total:snapshot.reconciliationTerminal,aeos_outbox_deliveries_active:snapshot.outboxDeliveriesActive,aeos_outbox_deliveries_failed_total:snapshot.outboxDeliveriesFailed,aeos_alerts_critical_total:snapshot.alertsCritical,aeos_alerts_unacknowledged:snapshot.alertsUnacknowledged,aeos_safe_executions_confirmed_total:snapshot.safeExecutionsConfirmed,aeos_provider_calls_total:snapshot.providerCalls,aeos_provider_failures_total:snapshot.providerFailures,aeos_provider_circuit_rejections_total:snapshot.providerCircuitRejections,aeos_advisory_provider_calls_total:snapshot.advisoryProviderCalls,aeos_advisory_provider_failures_total:snapshot.advisoryProviderFailures,aeos_advisory_provider_circuit_rejections_total:snapshot.advisoryProviderCircuitRejections,aeos_cockpit_sse_streams_active:snapshot.cockpitStreamsActive,aeos_cockpit_sse_streams_distributed_active:snapshot.cockpitStreamsDistributedActive,aeos_cockpit_sse_connections_total:snapshot.cockpitStreamConnectionsTotal,aeos_cockpit_sse_rejections_total:snapshot.cockpitStreamRejectionsTotal,aeos_cockpit_sse_capacity_total:snapshot.cockpitStreamCapacityTotal,aeos_cockpit_sse_capacity_per_organization:snapshot.cockpitStreamCapacityPerOrganization,aeos_cockpit_fanout_listener_connected:snapshot.cockpitFanoutListenerConnected,aeos_cockpit_fanout_notifications_total:snapshot.cockpitFanoutNotificationsTotal,aeos_cockpit_fanout_rejected_notifications_total:snapshot.cockpitFanoutRejectedNotificationsTotal,aeos_cockpit_fanout_reconnects_total:snapshot.cockpitFanoutReconnectsTotal};return `${Object.entries(values).map(([name,value])=>`${name} ${Number.isFinite(value)?value:0}`).join("\n")}\n`}
}
