import { buildOrganizationConfigurationApprovalMessage, normalizeOrganizationConfiguration, organizationConfigurationHash } from "./organization-configuration-engine";
import { createOrganizationConfigurationAdapterFromEnvironment, EvmOrganizationConfigurationReadAdapter, MockOrganizationConfigurationAdapter } from "./organization-configuration-adapter";

const input={networkName:"Creditcoin Testnet",chainId:102031,governorAddress:"0x1111111111111111111111111111111111111111",timelockAddress:"0x2222222222222222222222222222222222222222",safeAddress:"0x3333333333333333333333333333333333333333",treasuryAddress:"0x3333333333333333333333333333333333333333",treasuryGuardAddress:"0x4444444444444444444444444444444444444444",blockExplorerUrl:"https://creditcoin-testnet.blockscout.com/"};

describe("organization configuration guardrails",()=>{
  it("normalizes a deterministic configuration while allowing Safe as Treasury",()=>{const config=normalizeOrganizationConfiguration(input);expect(config.blockExplorerUrl).toBe("https://creditcoin-testnet.blockscout.com");expect(config.treasuryAddress).toBe(config.safeAddress);expect(organizationConfigurationHash(config)).toBe(organizationConfigurationHash(config))});
  it("rejects duplicated control contracts and unsafe explorer URLs",()=>{expect(()=>normalizeOrganizationConfiguration({...input,timelockAddress:input.governorAddress})).toThrow("CONTROL_CONTRACT_ADDRESSES_MUST_BE_DISTINCT");expect(()=>normalizeOrganizationConfiguration({...input,blockExplorerUrl:"javascript:alert(1)"})).toThrow("INVALID_BLOCK_EXPLORER_URL")});
  it("builds an exact approval message with zero transaction authority",()=>{const message=buildOrganizationConfigurationApprovalMessage({organizationId:"org_1",walletAddress:"0x5555555555555555555555555555555555555555",contentHash:`0x${"aa".repeat(32)}`,nonce:"abcdef1234567890",issuedAt:new Date("2026-08-06T00:00:00Z"),expiresAt:new Date("2026-08-06T00:05:00Z")});expect(message).toContain("Organization: org_1");expect(message).toContain("does not authorize any transaction or asset action")});
  it("labels the default inspection as shape-only Mock",async()=>{const adapter=new MockOrganizationConfigurationAdapter();const inspected=await adapter.inspect(normalizeOrganizationConfiguration(input));expect(inspected).toEqual(expect.objectContaining({status:"MOCK_ONLY",mockOnly:true,onchainInterfacesVerified:false,signsTransactions:false,submitsTransactions:false,assetExecutionAuthorized:false}))});
  it("exposes no signing or broadcast method on the real read-only adapter",()=>{expect(Object.getOwnPropertyNames(EvmOrganizationConfigurationReadAdapter.prototype).sort()).toEqual(["configuration","constructor","inspect"].sort())});
  it("fails closed on an unsupported adapter mode",()=>{const previous=process.env.ORGANIZATION_CONFIG_ADAPTER;process.env.ORGANIZATION_CONFIG_ADAPTER="unsafe";try{expect(()=>createOrganizationConfigurationAdapterFromEnvironment()).toThrow("Unsupported ORGANIZATION_CONFIG_ADAPTER")}finally{if(previous===undefined)delete process.env.ORGANIZATION_CONFIG_ADAPTER;else process.env.ORGANIZATION_CONFIG_ADAPTER=previous}});
});
