import { Wallet } from "ethers";
import { ConflictException } from "@nestjs/common";
import { OrganizationConfigurationService } from "./organization-configuration.service";
import { MockOrganizationConfigurationAdapter } from "./organization-configuration-adapter";

const input={networkName:"Creditcoin Testnet",chainId:102031,governorAddress:"0x1111111111111111111111111111111111111111",timelockAddress:"0x2222222222222222222222222222222222222222",safeAddress:"0x3333333333333333333333333333333333333333",treasuryAddress:"0x3333333333333333333333333333333333333333",treasuryGuardAddress:"0x4444444444444444444444444444444444444444"};

describe("OrganizationConfigurationService",()=>{
  it("stores only the approval-message hash during preparation",async()=>{const wallet=Wallet.createRandom();const db={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{count:1}]}).mockResolvedValueOnce({rowCount:1,rows:[]})} as any;const auth={activeOrganizationId:"org_1",userId:"user_1",walletAddress:wallet.address} as any;const result=await new OrganizationConfigurationService(db,new MockOrganizationConfigurationAdapter()).prepare(auth,input);const values=db.query.mock.calls[1][1];expect(values).not.toContain(result.message);expect(values[6]).toMatch(/^0x[0-9a-f]{64}$/);expect(result.inspection.status).toBe("MOCK_ONLY");expect(result.signatureStored).toBe(false);expect(result.assetExecutionAuthorized).toBe(false)});
  it("requires the current administrator signature and creates an immutable version audit",async()=>{
    const wallet=Wallet.createRandom();const auth={activeOrganizationId:"org_1",userId:"user_1",walletAddress:wallet.address} as any;const setup={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[{count:1}]}).mockResolvedValueOnce({rowCount:1,rows:[]}).mockResolvedValueOnce({rowCount:1,rows:[{count:1}]})} as any;const service=new OrganizationConfigurationService(setup,new MockOrganizationConfigurationAdapter());const prepared=await service.prepare(auth,input);const values=setup.query.mock.calls[1][1];
    const request={id:prepared.requestId,organization_id:"org_1",requested_by:"user_1",config:prepared.config,content_hash:prepared.contentHash,inspection:prepared.inspection,message_hash:values[6],expires_at:new Date(Date.now()+60000),consumed_at:null};
    const saved={id:"orgconfig_1",organization_id:"org_1",version:1,schema_version:"organization.configuration.v1",config:prepared.config,content_hash:prepared.contentHash,inspection:prepared.inspection,activated_by:"user_1",activated_at:new Date("2026-08-06T00:00:00Z")};
    const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[request]}).mockResolvedValueOnce({rowCount:1,rows:[{id:request.id}]}).mockResolvedValueOnce({rowCount:1,rows:[{id:"org_1"}]}).mockResolvedValueOnce({rowCount:1,rows:[{version:1}]}).mockResolvedValueOnce({rowCount:0,rows:[]}).mockResolvedValueOnce({rowCount:1,rows:[saved]}).mockResolvedValueOnce({rowCount:1,rows:[]})};setup.transaction=(work:any)=>work(client);
    const signature=await wallet.signMessage(prepared.message);const result=await service.activate(auth,prepared.requestId,prepared.message,signature);expect(result.version).toBe(1);expect(result.inspection.status).toBe("MOCK_ONLY");expect(result.signatureStored).toBe(false);expect(client.query.mock.calls.flatMap((call:any)=>call[1]??[])).not.toContain(signature);expect(client.query.mock.calls[6][0]).toContain("audit_events");
  });
  it("rejects replay before checking another signature",async()=>{const db={query:jest.fn().mockResolvedValue({rowCount:1,rows:[{count:1}]}),transaction:(work:any)=>work({query:jest.fn().mockResolvedValue({rowCount:1,rows:[{requested_by:"user_1",consumed_at:new Date()}]})})} as any;await expect(new OrganizationConfigurationService(db,new MockOrganizationConfigurationAdapter()).activate({activeOrganizationId:"org_1",userId:"user_1",walletAddress:Wallet.createRandom().address} as any,"request_1","message","0x"+"00".repeat(65))).rejects.toBeInstanceOf(ConflictException)});
});
