import { MockOutboxPublisher,OutboxDispatcherService,OUTBOX_CONSUMER } from "./outbox-publisher";

const event={id:"evt_audit_1",organization_id:"org_1",type:"policy.activated",occurred_at:"2026-08-06T00:00:00Z",actor:{type:"human",id:"user_1"},object_ref:{type:"policy",id:"policy_1"},data:{version:1},schema_version:"1.0",request_id:"trace_1",content_hash:"0xcontent"};
describe("transactional outbox publisher",()=>{
  it("is deterministic, idempotency-bound, Mock-only, and has zero asset authority",async()=>{const publisher=new MockOutboxPublisher();const first=await publisher.publish(event,event.id);const replay=await publisher.publish(event,event.id);expect(replay).toEqual(first);expect(publisher.configuration()).toEqual(expect.objectContaining({mode:"mock",networkAccess:false,signerCapability:false,broadcastCapability:false,assetExecutionAuthorized:false}))});
  it("claims and records one immutable consumer receipt",async()=>{
    const claim={event_id:event.id,organization_id:event.organization_id,consumer:OUTBOX_CONSUMER,status:"CLAIMED",attempts:1,claim_token:expect.anything()};
    const firstClient={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[claim]}).mockResolvedValueOnce({rowCount:1,rows:[event]})};
    const secondClient={query:jest.fn()};
    const db={runAsSystem:(work:any)=>work(),transaction:jest.fn().mockImplementationOnce((work:any)=>work(firstClient)).mockImplementationOnce((work:any)=>{secondClient.query.mockReset().mockResolvedValueOnce({rowCount:1,rows:[{...claim,claim_token:(firstClient.query.mock.calls[0][1] as any[])[1]}]}).mockResolvedValue({rowCount:1,rows:[]});return work(secondClient)})} as any;
    const result=await new OutboxDispatcherService(db,new MockOutboxPublisher()).dispatchOnce();expect(result).toEqual(expect.objectContaining({status:"DELIVERED",eventId:event.id,assetExecutionAuthorized:false}));expect(secondClient.query.mock.calls[1][0]).toContain("outbox_consumer_receipts");expect(secondClient.query.mock.calls[2][0]).toContain("status='DELIVERED'");
  });
  it("returns IDLE when no durable event is claimable",async()=>{const client={query:jest.fn().mockResolvedValue({rowCount:0,rows:[]})};const db={runAsSystem:(work:any)=>work(),transaction:(work:any)=>work(client)} as any;await expect(new OutboxDispatcherService(db,new MockOutboxPublisher()).dispatchOnce()).resolves.toEqual({status:"IDLE"})});
  it("records only a bounded error class and stops retrying at the persisted budget",async()=>{const claim={event_id:event.id,organization_id:event.organization_id,consumer:OUTBOX_CONSUMER,status:"CLAIMED",attempts:3};const client={query:jest.fn().mockResolvedValueOnce({rowCount:1,rows:[claim]}).mockResolvedValueOnce({rowCount:1,rows:[event]})};const db={runAsSystem:(work:any)=>work(),transaction:(work:any)=>work(client),query:jest.fn().mockResolvedValue({rowCount:1,rows:[]})} as any;const publisher={consumer:OUTBOX_CONSUMER,configuration:()=>({}),publish:jest.fn().mockRejectedValue(new Error("credential=secret"))};const result=await new OutboxDispatcherService(db,publisher).dispatchOnce();expect(result).toEqual(expect.objectContaining({status:"FAILED",errorCode:"ERROR",retryable:false,assetExecutionAuthorized:false}));expect(JSON.stringify(result)).not.toContain("secret")});
});
