import{BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException}from"@nestjs/common";
import{randomUUID}from"node:crypto";
import{PoolClient}from"pg";
import{DatabaseService}from"./database.service";
import{ConfirmOutcomeMemoryDaoDto,CreateOutcomeMemoryCandidateDto,OutcomeMemoryReviewOutcome,PromoteOutcomeMemoryCandidateDto,SupersedeOutcomeMemoryCandidateDto}from"./outcome-memory-candidate.dto";
import{deterministicMockEmbedding,hashText,MOCK_EMBEDDING_MODEL,redactSensitiveContent,scanKnowledgeContent}from"./knowledge-engine";

const makeId=(prefix:string)=>`${prefix}_${randomUUID().replaceAll("-","")}`;
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`:JSON.stringify(value);
const hash=(value:unknown)=>hashText(canonical(value));
const vector=(values:number[])=>`[${values.join(",")}]`;
const cleanList=(values:string[])=>[...new Set(values.map(value=>value.trim()).filter(Boolean))].sort();

@Injectable()
export class OutcomeMemoryCandidateService{
 constructor(private readonly db:DatabaseService){}

 async create(org:string,actorId:string,input:CreateOutcomeMemoryCandidateDto){
  const scan=scanKnowledgeContent(input.lesson);if(!scan.safe)throw new BadRequestException(`Outcome lesson rejected: ${scan.codes.join(",")}`);
  const lesson=redactSensitiveContent(input.lesson).trim(),invalidationConditions=cleanList(input.invalidationConditions),aclRoles=cleanList(input.aclRoles);
  if(!invalidationConditions.length||!aclRoles.length)throw new BadRequestException("Invalidation conditions and ACL roles are required");
  const validUntil=input.validUntil?new Date(input.validUntil):null;if(validUntil&&validUntil<=new Date())throw new BadRequestException("Outcome memory validity must be in the future");
  const found=await this.db.query<any>(`SELECT o.id AS outcome_id,o.treasury_id,o.policy_version_id,o.proposal_id,o.assessment AS outcome_assessment,o.assessment_hash AS outcome_hash,o.classification AS outcome_classification,o.safe_observation_id,
    c.id AS counterfactual_id,c.assessment AS counterfactual_assessment,c.assessment_hash AS counterfactual_hash,c.classification AS counterfactual_classification,c.methodology_version_id,c.transaction_cost_assessment_id,c.evidence_snapshot_id
    FROM treasury_outcome_assessments o JOIN treasury_counterfactual_assessments c ON c.organization_id=o.organization_id AND c.treasury_outcome_id=o.id
    WHERE o.organization_id=$1 AND o.id=$2 AND c.id=$3 AND o.causal_attribution_established=false AND o.memory_promotion_authorized=false AND o.skill_promotion_authorized=false AND o.asset_execution_authorized=false
    AND c.causal_attribution_established=false AND c.causal_net_benefit_established=false AND c.memory_promotion_authorized=false AND c.skill_promotion_authorized=false AND c.asset_execution_authorized=false`,[org,input.treasuryOutcomeId,input.counterfactualAssessmentId]);
  if(!found.rowCount)throw new NotFoundException("Matching non-causal Outcome and counterfactual assessment were not found in this organization");
  const source=found.rows[0],sourceLineage={schemaVersion:"outcome.memory.lineage.v1",treasuryOutcomeId:source.outcome_id,treasuryOutcomeHash:source.outcome_hash,outcomeClassification:source.outcome_classification,counterfactualAssessmentId:source.counterfactual_id,counterfactualAssessmentHash:source.counterfactual_hash,counterfactualClassification:source.counterfactual_classification,treasuryId:source.treasury_id,policyVersionId:source.policy_version_id,proposalId:source.proposal_id??null,safeObservationId:source.safe_observation_id,methodologyVersionId:source.methodology_version_id,transactionCostAssessmentId:source.transaction_cost_assessment_id,evidenceSnapshotId:source.evidence_snapshot_id,causalAttributionEstablished:false,historicalPerformanceClaimed:false};
  const frozen={schemaVersion:"outcome.memory.candidate.v1",reviewMode:input.reviewMode,lesson,invalidationConditions,aclRoles,validUntil:validUntil?.toISOString()??null,sourceLineage,claimClassification:"NON_CAUSAL_OPERATING_LESSON",automaticPromotionAuthorized:false,skillPromotionAuthorized:false,assetExecutionAuthorized:false},contentHash=hash(frozen);
  return this.db.transaction(async client=>{
   const saved=await client.query<any>(`INSERT INTO outcome_memory_candidates(id,organization_id,treasury_outcome_id,counterfactual_assessment_id,review_mode,lesson,invalidation_conditions,acl_roles,valid_until,source_lineage,content_hash,created_by)
    VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(organization_id,treasury_outcome_id,counterfactual_assessment_id,content_hash) DO NOTHING RETURNING *`,[makeId("omc"),org,input.treasuryOutcomeId,input.counterfactualAssessmentId,input.reviewMode,lesson,JSON.stringify(invalidationConditions),JSON.stringify(aclRoles),validUntil,sourceLineage,contentHash,actorId]);
   const row=saved.rowCount?saved.rows[0]:(await client.query("SELECT * FROM outcome_memory_candidates WHERE organization_id=$1 AND treasury_outcome_id=$2 AND counterfactual_assessment_id=$3 AND content_hash=$4",[org,input.treasuryOutcomeId,input.counterfactualAssessmentId,contentHash])).rows[0];
   if(saved.rowCount){await this.event(client,row,0,"CANDIDATE",{type:"human",id:actorId},{reviewMode:input.reviewMode,sourceLineage,automaticPromotionAuthorized:false,skillPromotionAuthorized:false,assetExecutionAuthorized:false});await this.audit(client,org,"outcome_memory.candidate_created",row.id,actorId,{contentHash,reviewMode:input.reviewMode,sourceLineage,assetExecutionAuthorized:false})}
   return this.map(row,"CANDIDATE",[],null);
  });
 }

 async list(org:string){const rows=await this.db.query<any>(`SELECT c.*,(SELECT event_type FROM outcome_memory_candidate_events e WHERE e.organization_id=c.organization_id AND e.candidate_id=c.id ORDER BY ordinal DESC LIMIT 1) AS status FROM outcome_memory_candidates c WHERE c.organization_id=$1 ORDER BY c.created_at DESC,c.id DESC LIMIT 100`,[org]);return{items:rows.rows.map(row=>this.map(row,row.status,[],null)),assetExecutionAuthorized:false}}
 async get(org:string,id:string){const row=await this.load(org,id);return this.detail(org,row)}

 async review(org:string,id:string,actorId:string,actorRole:string,outcome:OutcomeMemoryReviewOutcome,rationale:string){
  if(!["REVIEWER","TREASURY_COMMITTEE"].includes(actorRole))throw new ForbiddenException("Independent Reviewer or Treasury Committee role is required");
  return this.db.transaction(async client=>{
   const candidate=await this.lock(client,org,id),latest=await this.latest(client,org,id);if(["PROMOTED","REJECTED"].includes(latest.event_type))throw new ConflictException("Outcome memory candidate review is closed");if(candidate.created_by===actorId)throw new ConflictException("Outcome memory candidate creator cannot review");
   const reviewPayload={candidateId:id,reviewerId:actorId,reviewerRole:actorRole,outcome,rationale:rationale.trim()};
   try{await client.query("INSERT INTO outcome_memory_candidate_reviews(id,organization_id,candidate_id,reviewer_id,reviewer_role,outcome,rationale,payload_hash)VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[makeId("omcr"),org,id,actorId,actorRole,outcome,rationale.trim(),hash(reviewPayload)])}catch(error:any){if(String(error?.message).includes("unique")||String(error?.message).includes("creator cannot review"))throw new ConflictException("Candidate reviewer and reviewer role must each be independent and unique");throw error}
   const reviews=await client.query<any>("SELECT * FROM outcome_memory_candidate_reviews WHERE organization_id=$1 AND candidate_id=$2 ORDER BY created_at,id",[org,id]);let eventType:string;
   if(outcome==="REJECT")eventType="REJECTED";else{const approved=new Set(reviews.rows.filter(row=>row.outcome==="APPROVE").map(row=>row.reviewer_role));eventType=approved.has("REVIEWER")&&approved.has("TREASURY_COMMITTEE")?"HUMAN_APPROVED":"REVIEW_RECORDED"}
   await this.event(client,candidate,latest.ordinal+1,eventType,{type:"human",id:actorId,role:actorRole},{reviewOutcome:outcome,rationale:rationale.trim(),distinctApprovedRoles:reviews.rows.filter(row=>row.outcome==="APPROVE").map(row=>row.reviewer_role).sort(),assetExecutionAuthorized:false});
   await this.audit(client,org,`outcome_memory.${eventType.toLowerCase()}`,id,actorId,{reviewerRole:actorRole,reviewOutcome:outcome,assetExecutionAuthorized:false});return this.map(candidate,eventType,reviews.rows,null);
  });
 }

 async confirmDao(org:string,id:string,actorId:string,input:ConfirmOutcomeMemoryDaoDto){return this.db.transaction(async client=>{
  const candidate=await this.lock(client,org,id),latest=await this.latest(client,org,id);if(candidate.review_mode!=="HUMAN_COMMITTEE_AND_DAO")throw new ConflictException("Candidate does not require DAO confirmation");if(latest.event_type!=="HUMAN_APPROVED")throw new ConflictException("Dual human approval is required before DAO confirmation");
  const outcome=await client.query<any>("SELECT proposal_id FROM treasury_outcome_assessments WHERE organization_id=$1 AND id=$2",[org,candidate.treasury_outcome_id]);if(!outcome.rowCount||!outcome.rows[0].proposal_id||outcome.rows[0].proposal_id!==input.proposalId)throw new BadRequestException("DAO proposal does not match the Treasury Outcome lineage");
  const observation=await client.query<any>(`SELECT * FROM proposal_state_observations WHERE organization_id=$1 AND proposal_id=$2 ORDER BY ordinal DESC LIMIT 1`,[org,input.proposalId]);const row=observation.rows[0];
  if(!row||!["SUCCEEDED","EXECUTED"].includes(row.state)||row.is_reorg||Number(row.confirmations)<=0||row.payload?.onchainFinalityVerified!==true||row.payload?.mockOnly===true||row.payload?.fixtureOnly===true||row.payload?.verificationMode==="TEST_FIXTURE"||/mock|fixture/i.test(String(row.adapter)))throw new ConflictException("A non-mock, confirmed SUCCEEDED or EXECUTED DAO observation is required");
  const data={proposalId:input.proposalId,observationId:row.id,observationPayloadHash:row.payload_hash,state:row.state,chainId:row.chain_id,blockNumber:String(row.block_number),blockHash:row.block_hash,confirmations:Number(row.confirmations),onchainFinalityVerified:true,assetExecutionAuthorized:false};await this.event(client,candidate,latest.ordinal+1,"DAO_CONFIRMED",{type:"human",id:actorId},data);await this.audit(client,org,"outcome_memory.dao_confirmed",id,actorId,data);return this.map(candidate,"DAO_CONFIRMED",await this.reviews(client,org,id),null);
 })}

 async promote(org:string,id:string,actorId:string,input:PromoteOutcomeMemoryCandidateDto){return this.db.transaction(async client=>{
  const candidate=await this.lock(client,org,id),latest=await this.latest(client,org,id),required=candidate.review_mode==="HUMAN_COMMITTEE_AND_DAO"?"DAO_CONFIRMED":"HUMAN_APPROVED";if(latest.event_type!==required)throw new ConflictException(`${required} is required before Enterprise Memory promotion`);if(candidate.valid_until&&new Date(candidate.valid_until)<=new Date())throw new ConflictException("Expired candidate cannot be promoted");
  const prior=await client.query("SELECT * FROM outcome_memory_promotions WHERE organization_id=$1 AND candidate_id=$2",[org,id]);if(prior.rowCount)throw new ConflictException("Outcome memory candidate is already promoted");
  const content=`NON-CAUSAL OPERATING LESSON\n${candidate.lesson}\n\nINVALIDATION CONDITIONS\n${(candidate.invalidation_conditions as string[]).map((item,index)=>`${index+1}. ${item}`).join("\n")}\n\nThis governed memory does not establish historical performance, causal attribution, asset execution authority, or automatic Skill promotion.`;
  const memoryHash=hash({content,sourceRefs:[id,candidate.treasury_outcome_id,candidate.counterfactual_assessment_id].sort(),memoryType:"ENTERPRISE",candidateContentHash:candidate.content_hash});const memoryId=makeId("memory");
  await client.query("INSERT INTO organization_memories(id,organization_id,memory_type,content,source_refs,acl_roles,valid_until,author_id,content_hash,embedding,embedding_model)VALUES($1,$2,'ENTERPRISE',$3,$4,$5,$6,$7,$8,$9::vector,$10)",[memoryId,org,content,JSON.stringify([id,candidate.treasury_outcome_id,candidate.counterfactual_assessment_id].sort()),JSON.stringify(candidate.acl_roles),candidate.valid_until,actorId,memoryHash,vector(deterministicMockEmbedding(content)),MOCK_EMBEDDING_MODEL]);
  await this.memoryEvent(client,org,memoryId,0,"CANDIDATE",actorId,"Governed Outcome lesson created by explicit promotion");await this.memoryEvent(client,org,memoryId,1,"APPROVED",actorId,input.rationale.trim());
  const promotionHash=hash({candidateId:id,memoryId,candidateContentHash:candidate.content_hash,memoryContentHash:memoryHash,promotedBy:actorId});await client.query("INSERT INTO outcome_memory_promotions(id,organization_id,candidate_id,memory_id,promoted_by,content_hash)VALUES($1,$2,$3,$4,$5,$6)",[makeId("omp"),org,id,memoryId,actorId,promotionHash]);
  await this.event(client,candidate,latest.ordinal+1,"PROMOTED",{type:"human",id:actorId},{memoryId,memoryContentHash:memoryHash,rationale:input.rationale.trim(),automaticPromotionAuthorized:false,skillPromotionAuthorized:false,assetExecutionAuthorized:false});await this.audit(client,org,"outcome_memory.promoted",id,actorId,{memoryId,memoryContentHash:memoryHash,candidateContentHash:candidate.content_hash,assetExecutionAuthorized:false});
  return this.map(candidate,"PROMOTED",await this.reviews(client,org,id),{memoryId,memoryContentHash:memoryHash,promotionHash,status:"APPROVED"});
 })}

 async supersede(org:string,id:string,actorId:string,input:SupersedeOutcomeMemoryCandidateDto){
  if(id===input.replacementCandidateId)throw new BadRequestException("Replacement Outcome Memory candidate must be different");
  return this.db.transaction(async client=>{
   const ids=[id,input.replacementCandidateId].sort();const locked=await client.query<any>("SELECT id FROM outcome_memory_candidates WHERE organization_id=$1 AND id=ANY($2::text[]) ORDER BY id FOR UPDATE",[org,ids]);if(locked.rowCount!==2)throw new NotFoundException("Outcome Memory candidate or replacement was not found in this organization");
   const old=await this.promotedLifecycle(client,org,id),replacement=await this.promotedLifecycle(client,org,input.replacementCandidateId);
   if(!old||!replacement)throw new ConflictException("Both Outcome Memory candidates must have explicit promotions");
   const existing=await client.query<any>("SELECT * FROM outcome_memory_retirements WHERE organization_id=$1 AND candidate_id=$2",[org,id]);if(existing.rowCount){if(existing.rows[0].retirement_type==="SUPERSEDED"&&existing.rows[0].replacement_candidate_id===input.replacementCandidateId)return this.retirementResult(existing.rows[0]);throw new ConflictException("Outcome Memory already has a different terminal retirement")}
   if(old.memory_status!=="APPROVED")throw new ConflictException("Only an Approved Outcome Memory can be superseded");
   if(replacement.memory_status!=="APPROVED")throw new ConflictException("Replacement Outcome Memory must be Approved");
   if(old.treasury_id!==replacement.treasury_id)throw new ConflictException("Replacement Outcome Memory must govern the same Treasury");
   if(old.valid_until&&new Date(old.valid_until)<=new Date())throw new ConflictException("Expired Outcome Memory must be reconciled as EXPIRED, not SUPERSEDED");
   if(replacement.valid_until&&new Date(replacement.valid_until)<=new Date())throw new ConflictException("Replacement Outcome Memory is expired");
   const rationale=input.rationale.trim(),eventResult=await this.memoryEvent(client,org,old.memory_id,Number(old.memory_event_ordinal)+1,"SUPERSEDED",actorId,rationale),memoryEventId=eventResult.rows[0].id;
   const basis={schemaVersion:"outcome.memory.retirement-basis.v1",retirementType:"SUPERSEDED",candidateId:id,promotionId:old.promotion_id,memoryId:old.memory_id,memoryContentHash:old.memory_content_hash,treasuryId:old.treasury_id,replacementCandidateId:replacement.candidate_id,replacementPromotionId:replacement.promotion_id,replacementMemoryId:replacement.memory_id,replacementMemoryContentHash:replacement.memory_content_hash,rationale,deterministicEligibility:{oldMemoryStatus:"APPROVED",replacementMemoryStatus:"APPROVED",sameOrganization:true,sameTreasury:true},historicalDecisionManifestsMutated:false,assetExecutionAuthorized:false};
   const saved=await client.query<any>(`INSERT INTO outcome_memory_retirements(id,organization_id,candidate_id,promotion_id,memory_id,retirement_type,replacement_candidate_id,replacement_promotion_id,replacement_memory_id,memory_event_id,basis,content_hash,retired_by) VALUES($1,$2,$3,$4,$5,'SUPERSEDED',$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[makeId("omret"),org,id,old.promotion_id,old.memory_id,replacement.candidate_id,replacement.promotion_id,replacement.memory_id,memoryEventId,basis,hash(basis),actorId]);
   await this.audit(client,org,"outcome_memory.superseded",id,actorId,{memoryId:old.memory_id,replacementCandidateId:replacement.candidate_id,replacementMemoryId:replacement.memory_id,retirementHash:saved.rows[0].content_hash,indexExcluded:true,historicalDecisionManifestsMutated:false,assetExecutionAuthorized:false});return this.retirementResult(saved.rows[0]);
  });
 }

 async reconcileExpired(org:string,actorId:string){return this.db.transaction(async client=>{
  const eligible=await client.query<any>(`SELECT c.id AS candidate_id,p.id AS promotion_id,m.id AS memory_id,m.content_hash AS memory_content_hash,m.valid_until,o.treasury_id,e.ordinal AS memory_event_ordinal
   FROM outcome_memory_candidates c JOIN outcome_memory_promotions p ON p.organization_id=c.organization_id AND p.candidate_id=c.id JOIN organization_memories m ON m.organization_id=c.organization_id AND m.id=p.memory_id JOIN treasury_outcome_assessments o ON o.organization_id=c.organization_id AND o.id=c.treasury_outcome_id
   JOIN LATERAL(SELECT ordinal,status FROM memory_events WHERE organization_id=m.organization_id AND memory_id=m.id ORDER BY ordinal DESC LIMIT 1)e ON e.status='APPROVED'
   LEFT JOIN outcome_memory_retirements r ON r.organization_id=c.organization_id AND r.candidate_id=c.id
   WHERE c.organization_id=$1 AND m.valid_until IS NOT NULL AND m.valid_until<=now() AND r.id IS NULL ORDER BY m.valid_until,c.id LIMIT 100 FOR UPDATE OF c,m SKIP LOCKED`,[org]);
  const retired=[] as any[];
  for(const row of eligible.rows){const rationale=`Deterministic validity expiry at ${new Date(row.valid_until).toISOString()}`,eventResult=await this.memoryEvent(client,org,row.memory_id,Number(row.memory_event_ordinal)+1,"EXPIRED",actorId,rationale),basis={schemaVersion:"outcome.memory.retirement-basis.v1",retirementType:"EXPIRED",candidateId:row.candidate_id,promotionId:row.promotion_id,memoryId:row.memory_id,memoryContentHash:row.memory_content_hash,treasuryId:row.treasury_id,validUntil:new Date(row.valid_until).toISOString(),clockAuthority:"POSTGRESQL_NOW",historicalDecisionManifestsMutated:false,assetExecutionAuthorized:false};const saved=await client.query<any>(`INSERT INTO outcome_memory_retirements(id,organization_id,candidate_id,promotion_id,memory_id,retirement_type,memory_event_id,basis,content_hash,retired_by) VALUES($1,$2,$3,$4,$5,'EXPIRED',$6,$7,$8,$9) RETURNING *`,[makeId("omret"),org,row.candidate_id,row.promotion_id,row.memory_id,eventResult.rows[0].id,basis,hash(basis),actorId]);await this.audit(client,org,"outcome_memory.expired",row.candidate_id,actorId,{memoryId:row.memory_id,validUntil:basis.validUntil,retirementHash:saved.rows[0].content_hash,indexExcluded:true,historicalDecisionManifestsMutated:false,assetExecutionAuthorized:false});retired.push(this.retirementResult(saved.rows[0]))}
  return{organizationId:org,processed:retired.length,retirements:retired,clockAuthority:"POSTGRESQL_NOW",boundedBatchSize:100,indexExcluded:true,historicalDecisionManifestsMutated:false,assetExecutionAuthorized:false};
 })}

 private async load(org:string,id:string){const found=await this.db.query<any>("SELECT * FROM outcome_memory_candidates WHERE organization_id=$1 AND id=$2",[org,id]);if(!found.rowCount)throw new NotFoundException("Outcome memory candidate not found");return found.rows[0]}
 private async detail(org:string,row:any){const events=await this.db.query<any>("SELECT * FROM outcome_memory_candidate_events WHERE organization_id=$1 AND candidate_id=$2 ORDER BY ordinal",[org,row.id]),reviews=await this.db.query<any>("SELECT * FROM outcome_memory_candidate_reviews WHERE organization_id=$1 AND candidate_id=$2 ORDER BY created_at,id",[org,row.id]),promotion=await this.db.query<any>("SELECT * FROM outcome_memory_promotions WHERE organization_id=$1 AND candidate_id=$2",[org,row.id]),retirement=await this.db.query<any>("SELECT * FROM outcome_memory_retirements WHERE organization_id=$1 AND candidate_id=$2",[org,row.id]);return{...this.map(row,events.rows.at(-1)?.event_type??"CANDIDATE",reviews.rows,promotion.rows[0]??null),retirement:retirement.rowCount?this.retirementResult(retirement.rows[0]):null,events:events.rows.map(event=>({ordinal:event.ordinal,eventType:event.event_type,actor:event.actor,data:event.data,payloadHash:event.payload_hash,createdAt:new Date(event.created_at).toISOString()}))}}
 private async lock(client:PoolClient,org:string,id:string){const found=await client.query<any>("SELECT * FROM outcome_memory_candidates WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,id]);if(!found.rowCount)throw new NotFoundException("Outcome memory candidate not found");return found.rows[0]}
 private async latest(client:PoolClient,org:string,id:string){const found=await client.query<any>("SELECT ordinal,event_type FROM outcome_memory_candidate_events WHERE organization_id=$1 AND candidate_id=$2 ORDER BY ordinal DESC LIMIT 1 FOR UPDATE",[org,id]);if(!found.rowCount)throw new NotFoundException("Outcome memory candidate state not found");return found.rows[0]}
 private async reviews(client:PoolClient,org:string,id:string){return(await client.query<any>("SELECT * FROM outcome_memory_candidate_reviews WHERE organization_id=$1 AND candidate_id=$2 ORDER BY created_at,id",[org,id])).rows}
 private async promotedLifecycle(client:PoolClient,org:string,id:string){const found=await client.query<any>(`SELECT c.id AS candidate_id,p.id AS promotion_id,p.memory_id,m.content_hash AS memory_content_hash,m.valid_until,o.treasury_id,e.ordinal AS memory_event_ordinal,e.status AS memory_status FROM outcome_memory_candidates c JOIN outcome_memory_promotions p ON p.organization_id=c.organization_id AND p.candidate_id=c.id JOIN organization_memories m ON m.organization_id=c.organization_id AND m.id=p.memory_id JOIN treasury_outcome_assessments o ON o.organization_id=c.organization_id AND o.id=c.treasury_outcome_id JOIN LATERAL(SELECT ordinal,status FROM memory_events WHERE organization_id=m.organization_id AND memory_id=m.id ORDER BY ordinal DESC LIMIT 1)e ON true WHERE c.organization_id=$1 AND c.id=$2`,[org,id]);return found.rows[0]??null}
 private retirementResult(row:any){return{id:row.id,organizationId:row.organization_id,candidateId:row.candidate_id,promotionId:row.promotion_id,memoryId:row.memory_id,retirementType:row.retirement_type,replacementCandidateId:row.replacement_candidate_id??null,replacementPromotionId:row.replacement_promotion_id??null,replacementMemoryId:row.replacement_memory_id??null,memoryEventId:row.memory_event_id,basis:row.basis,contentHash:row.content_hash,retiredBy:row.retired_by,indexExcluded:true,historicalDecisionManifestsMutated:false,advisoryOnly:true,assetExecutionAuthorized:false,createdAt:new Date(row.created_at).toISOString()}}
 private map(row:any,status:string,reviews:any[],promotion:any){return{id:row.id,organizationId:row.organization_id,treasuryOutcomeId:row.treasury_outcome_id,counterfactualAssessmentId:row.counterfactual_assessment_id,reviewMode:row.review_mode,lesson:row.lesson,invalidationConditions:row.invalidation_conditions,aclRoles:row.acl_roles,validUntil:row.valid_until?new Date(row.valid_until).toISOString():null,sourceLineage:row.source_lineage,contentHash:row.content_hash,createdBy:row.created_by,status,reviews:reviews.map(review=>({reviewerId:review.reviewer_id,reviewerRole:review.reviewer_role,outcome:review.outcome,rationale:review.rationale,payloadHash:review.payload_hash,createdAt:new Date(review.created_at).toISOString()})),promotion:promotion?{memoryId:promotion.memory_id??promotion.memoryId,memoryContentHash:promotion.memoryContentHash??null,promotionHash:promotion.content_hash??promotion.promotionHash,status:promotion.status??"APPROVED"}:null,claimClassification:"NON_CAUSAL_OPERATING_LESSON",historicalPerformanceClaimed:false,causalAttributionEstablished:false,automaticPromotionAuthorized:false,skillPromotionAuthorized:false,advisoryOnly:true,assetExecutionAuthorized:false,createdAt:new Date(row.created_at).toISOString()}}
 private event(client:PoolClient,row:any,ordinal:number,eventType:string,actor:unknown,data:unknown){const payload={candidateId:row.id,ordinal,eventType,actor,data};return client.query("INSERT INTO outcome_memory_candidate_events(id,organization_id,candidate_id,ordinal,event_type,actor,data,payload_hash)VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[makeId("omce"),row.organization_id,row.id,ordinal,eventType,actor,data,hash(payload)])}
 private memoryEvent(client:PoolClient,org:string,memoryId:string,ordinal:number,status:string,actorId:string,rationale:string){const payload={memoryId,ordinal,status,actorId,rationale};return client.query<any>("INSERT INTO memory_events(id,organization_id,memory_id,ordinal,status,actor_id,rationale,payload_hash)VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id",[makeId("mevent"),org,memoryId,ordinal,status,actorId,rationale,hash(payload)])}
 private audit(client:PoolClient,org:string,eventType:string,objectId:string,actorId:string,data:unknown){const payload={eventType,organizationId:org,objectType:"outcome_memory_candidate",objectId,data};return client.query("INSERT INTO audit_events(id,organization_id,event_type,actor,action,object_type,object_id,data,payload_hash)VALUES($1,$2,$3,$4,$3,'outcome_memory_candidate',$5,$6,$7)",[makeId("audit"),org,eventType,{type:"human",id:actorId},objectId,data,hash(payload)])}
}
