import { buildPolicyUnpauseHandoff, PolicyActivationReadback } from "./policy-unpause-handoff-engine";

describe("DAO policy unpause handoff",()=>{
  const activation={chainId:102031,governance:"0x1111111111111111111111111111111111111111",policyRegistry:"0x2222222222222222222222222222222222222222",treasuryGuard:"0x3333333333333333333333333333333333333333",guardPaused:true,registryLatestVersion:1,guardPolicyVersion:1,policyHash:`0x${"44".repeat(32)}`,policyVersion:2,validFrom:100,validUntil:200,maxNativeValue:"10",allowedTargets:["0x5555555555555555555555555555555555555555"],allowedSelectors:["0xa9059cbb"]};
  const observed:PolicyActivationReadback={chainId:102031,blockNumber:1000,blockHash:`0x${"aa".repeat(32)}`,confirmations:2,observedTimestamp:150,guardAddress:activation.treasuryGuard,guardRegistry:activation.policyRegistry,guardPaused:true,guardPolicyHash:activation.policyHash,guardPolicyVersion:2,guardValidFrom:100,guardValidUntil:200,guardMaxNativeValue:"10",registryAddress:activation.policyRegistry,registryLatestVersion:2,registryPolicyHash:activation.policyHash,registryPolicyVersion:2,registryValidFrom:100,registryValidUntil:200,allowedTargets:[{target:activation.allowedTargets[0],allowed:true}],allowedSelectors:[{selector:activation.allowedSelectors[0],allowed:true}]};
  it("emits a separate deterministic unsigned unpause handoff only after complete readback",()=>{const first=buildPolicyUnpauseHandoff(activation,observed),second=buildPolicyUnpauseHandoff(activation,observed);expect(first).toEqual(second);expect(first.status).toBe("VERIFIED");expect(first.allowlistReadbackScope).toBe("EXPECTED_BATCH_ENTRIES");expect(first.checks).toHaveLength(12);expect(first.unpauseHandoff).toEqual(expect.objectContaining({to:activation.treasuryGuard,value:"0",data:"0x16c38b3c"+"0".repeat(64),requiresDaoApproval:true,signed:false,submitted:false,assetExecutionAuthorized:false}));expect(first.aeosSigningCapability).toBe(false)});
  it("rejects incomplete or false target and selector readback without creating calldata",()=>{for(const changed of[{allowedTargets:[]},{allowedTargets:[{target:activation.allowedTargets[0],allowed:false}]},{allowedSelectors:[]},{allowedSelectors:[{selector:activation.allowedSelectors[0],allowed:false}]}]){const result=buildPolicyUnpauseHandoff(activation,{...observed,...changed} as PolicyActivationReadback);expect(result.status).toBe("REJECTED");expect(result.unpauseHandoff).toBeNull()}});
  it("rejects policy, value, Registry and confirmation drift",()=>{for(const changed of[{guardPolicyHash:`0x${"55".repeat(32)}`},{guardMaxNativeValue:"11"},{registryLatestVersion:3},{guardRegistry:"0x6666666666666666666666666666666666666666"},{confirmations:0}])expect(buildPolicyUnpauseHandoff(activation,{...observed,...changed} as PolicyActivationReadback).status).toBe("REJECTED")});
  it("requires the policy to be active at the observed confirmed block",()=>{expect(buildPolicyUnpauseHandoff(activation,{...observed,observedTimestamp:99}).unpauseHandoff).toBeNull();expect(buildPolicyUnpauseHandoff(activation,{...observed,observedTimestamp:201}).unpauseHandoff).toBeNull()});
});
