import { createHash,randomUUID } from "node:crypto";
import { BadRequestException,Inject,Injectable,NotFoundException,ServiceUnavailableException } from "@nestjs/common";
import { PoolClient } from "pg";
import { DatabaseService } from "./database.service";
import { classifySafeReadFailure,recoverySummary,ReconciliationOutcome } from "./execution-recovery-engine";
import { ObserveSafeTransactionDto } from "./safe-transaction.dto";
import { SAFE_TRANSACTION_ADAPTER,SafeTransactionReadAdapter } from "./safe-transaction-adapter";
import { reconcileTerminalSafeObservation,SafeObservationState,validateSafeObservationTransition } from "./safe-observation-engine";

const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`:JSON.stringify(value);
const hash=(value:unknown)=>`0x${createHash("sha256").update(canonical(value)).digest("hex")}`;const makeId=(prefix:string)=>`${prefix}_${randomUUID().replaceAll("-","")}`;

@Injectable()
export class SafeTransactionService{
  constructor(private readonly db:DatabaseService,@Inject(SAFE_TRANSACTION_ADAPTER)private readonly adapter:SafeTransactionReadAdapter){}
  configuration(){return this.adapter.configuration()}

  async observe(org:string,preflightId:string,input:ObserveSafeTransactionDto){
    const safeTxHash=input.safeTxHash.toLowerCase();
    const found=await this.db.query("SELECT * FROM execution_preflights WHERE organization_id=$1 AND id=$2",[org,preflightId]);if(!found.rowCount)throw new NotFoundException("Execution preflight not found");const preflight=found.rows[0];
    if(preflight.status!=="READY_FOR_SAFE_REVIEW"||!preflight.result?.safeHandoff){await this.recordFailure(org,preflight,safeTxHash,"REJECTED","PREFLIGHT_NOT_READY",0);throw new BadRequestException("Only a ready execution preflight can be observed")}
    let normalized;
    try{normalized=await this.adapter.read({safeTxHash,actionId:preflight.action_id,handoff:preflight.result.safeHandoff,guardAddress:preflight.result.guardSnapshot.address,expiresAt:new Date(preflight.expires_at).toISOString()})}
    catch(error){const attempt=await this.recordClassifiedFailure(org,preflight,safeTxHash,error);throw new ServiceUnavailableException({message:"Safe transaction read failed",code:attempt.errorCode,retryable:attempt.outcome==="FAILED_RETRYABLE",retryAfterSeconds:attempt.retryAfterSeconds,reconciliationAttemptId:attempt.id})}
    try{
      return await this.db.transaction(async(client)=>{
        const locked=await client.query("SELECT * FROM execution_preflights WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,preflightId]);if(!locked.rowCount)throw new NotFoundException("Execution preflight not found");
        const latestResult=await client.query("SELECT * FROM safe_transaction_observations WHERE organization_id=$1 AND preflight_id=$2 ORDER BY ordinal DESC LIMIT 1",[org,preflightId]);const latest=latestResult.rows[0]??null;
        const payload={...normalized,preflightId,proposalId:preflight.proposal_id,preflightResultHash:preflight.result_hash,actionId:preflight.action_id};const payloadHash=hash(payload);
        const duplicate=await client.query("SELECT * FROM safe_transaction_observations WHERE organization_id=$1 AND preflight_id=$2 AND payload_hash=$3",[org,preflightId,payloadHash]);let row;
        if(duplicate.rowCount)row=duplicate.rows[0];
        else{
          if(latest&&latest.safe_tx_hash!==normalized.safeTxHash)throw new BadRequestException("SAFE_TRANSACTION_IDENTITY_CANNOT_CHANGE");
          let terminal;try{terminal=reconcileTerminalSafeObservation(latest,normalized)}catch(error){throw new BadRequestException(error instanceof Error?error.message:"SAFE_EXECUTION_REORG_DETECTED")}
          if(terminal.reusePrevious)row=latest;
          else{try{validateSafeObservationTransition(latest?.state as SafeObservationState|undefined,normalized.state)}catch(error){throw new BadRequestException(error instanceof Error?error.message:"INVALID_SAFE_OBSERVATION_TRANSITION")}
            const ordinal=latest?Number(latest.ordinal)+1:1;const saved=await client.query("INSERT INTO safe_transaction_observations(id,organization_id,preflight_id,proposal_id,ordinal,previous_observation_id,adapter,safe_address,safe_tx_hash,state,confirmations,confirmations_required,execution_tx_hash,execution_block_number,execution_block_hash,onchain_execution_confirmed,payload,payload_hash,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *",[makeId("safeobs"),org,preflightId,preflight.proposal_id,ordinal,latest?.id??null,this.adapter.provider,normalized.safeAddress,normalized.safeTxHash,normalized.state,normalized.confirmations,normalized.confirmationsRequired,normalized.executionTxHash,normalized.executionBlockNumber,normalized.executionBlockHash,normalized.onchainExecutionConfirmed,payload,payloadHash,normalized.executionObservedAt??new Date().toISOString()]);row=saved.rows[0];await this.auditObservation(client,org,row);}
        }
        const attempt=await this.insertAttempt(client,org,preflight,safeTxHash,"SUCCEEDED",null,0,row.id);return {...this.map(row),reconciliationAttempt:this.mapAttempt(attempt)};
      });
    }catch(error){
      if(error instanceof BadRequestException){const code=typeof error.message==="string"?error.message:"INVALID_SAFE_OBSERVATION_TRANSITION";await this.recordFailure(org,preflight,safeTxHash,"FAILED_TERMINAL",code,0)}
      throw error;
    }
  }

  async list(org:string,preflightId:string){const preflight=await this.db.query("SELECT 1 FROM execution_preflights WHERE organization_id=$1 AND id=$2",[org,preflightId]);if(!preflight.rowCount)throw new NotFoundException("Execution preflight not found");const [result,attempts]=await Promise.all([this.db.query("SELECT * FROM safe_transaction_observations WHERE organization_id=$1 AND preflight_id=$2 ORDER BY ordinal",[org,preflightId]),this.db.query("SELECT * FROM execution_reconciliation_attempts WHERE organization_id=$1 AND preflight_id=$2 ORDER BY ordinal DESC LIMIT 1",[org,preflightId])]);return {items:result.rows.map(row=>this.map(row)),reconciliation:recoverySummary(attempts.rows[0]??null),assetExecutionAuthorized:false}}
  async get(org:string,id:string){const result=await this.db.query("SELECT * FROM safe_transaction_observations WHERE organization_id=$1 AND id=$2",[org,id]);if(!result.rowCount)throw new NotFoundException("Safe transaction observation not found");return this.map(result.rows[0])}
  async reconciliationAttempts(org:string,preflightId:string){const preflight=await this.db.query("SELECT 1 FROM execution_preflights WHERE organization_id=$1 AND id=$2",[org,preflightId]);if(!preflight.rowCount)throw new NotFoundException("Execution preflight not found");const result=await this.db.query("SELECT * FROM execution_reconciliation_attempts WHERE organization_id=$1 AND preflight_id=$2 ORDER BY ordinal",[org,preflightId]);const latest=result.rows.at(-1)??null;return {items:result.rows.map(row=>this.mapAttempt(row)),summary:recoverySummary(latest)}}

  private async recordClassifiedFailure(org:string,preflight:any,safeTxHash:string,error:unknown){return this.db.transaction(async(client)=>{await client.query("SELECT 1 FROM execution_preflights WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,preflight.id]);const count=await client.query("SELECT count(*)::int AS count FROM execution_reconciliation_attempts WHERE organization_id=$1 AND preflight_id=$2",[org,preflight.id]);const classified=classifySafeReadFailure(error,Number(count.rows[0].count)+1);const row=await this.insertAttempt(client,org,preflight,safeTxHash,classified.outcome,classified.errorCode,classified.retryAfterSeconds,null);return this.mapAttempt(row)})}
  private async recordFailure(org:string,preflight:any,safeTxHash:string,outcome:ReconciliationOutcome,errorCode:string,retryAfterSeconds:number){return this.db.transaction(async(client)=>{await client.query("SELECT 1 FROM execution_preflights WHERE organization_id=$1 AND id=$2 FOR UPDATE",[org,preflight.id]);return this.mapAttempt(await this.insertAttempt(client,org,preflight,safeTxHash,outcome,errorCode,retryAfterSeconds,null))})}
  private async insertAttempt(client:PoolClient,org:string,preflight:any,safeTxHash:string,outcome:ReconciliationOutcome,errorCode:string|null,retryAfterSeconds:number,observationId:string|null){
    const latest=await client.query("SELECT ordinal FROM execution_reconciliation_attempts WHERE organization_id=$1 AND preflight_id=$2 ORDER BY ordinal DESC LIMIT 1",[org,preflight.id]);const ordinal=latest.rowCount?Number(latest.rows[0].ordinal)+1:1;const attemptedAt=new Date();
    const payload={schemaVersion:"execution.reconciliation.attempt.v1",preflightId:preflight.id,proposalId:preflight.proposal_id,safeTxHash,adapter:this.adapter.provider,ordinal,outcome,errorCode,retryAfterSeconds,observationId,attemptedAt:attemptedAt.toISOString(),manualRetryOnly:true,automaticSubmission:false,signaturesStored:false,assetExecutionAuthorized:false};const payloadHash=hash(payload);
    const saved=await client.query("INSERT INTO execution_reconciliation_attempts(id,organization_id,preflight_id,proposal_id,ordinal,safe_tx_hash,adapter,outcome,error_code,retry_after_seconds,observation_id,payload,payload_hash,attempted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *",[makeId("recon"),org,preflight.id,preflight.proposal_id,ordinal,safeTxHash,this.adapter.provider,outcome,errorCode,retryAfterSeconds,observationId,payload,payloadHash,attemptedAt.toISOString()]);await this.auditAttempt(client,org,saved.rows[0]);return saved.rows[0];
  }
  private async auditObservation(client:PoolClient,org:string,row:any){const configured=this.adapter.configuration();const data={chainId:typeof configured.chainId==="number"?configured.chainId:null,safeAddress:row.safe_address,executionTxHash:row.execution_tx_hash,executionBlockNumber:row.execution_block_number===null?null:Number(row.execution_block_number),executionBlockHash:row.execution_block_hash,observationId:row.id,preflightId:row.preflight_id,state:row.state,payloadHash:row.payload_hash,onchainExecutionConfirmed:row.onchain_execution_confirmed,authorizationRecorded:row.onchain_execution_confirmed,signaturesStored:false,assetExecutionAuthorized:false};const payload={eventType:"safe.transaction_observed",organizationId:org,objectType:"execution_preflight",objectId:row.preflight_id,data};await client.query("INSERT INTO audit_events(id,organization_id,event_type,actor,action,object_type,object_id,data,payload_hash) VALUES($1,$2,'safe.transaction_observed',$3,'safe.transaction_observed','execution_preflight',$4,$5,$6)",[makeId("audit"),org,{type:"adapter",id:this.adapter.provider},row.preflight_id,data,hash(payload)])}
  private async auditAttempt(client:PoolClient,org:string,row:any){const data={attemptId:row.id,ordinal:row.ordinal,outcome:row.outcome,errorCode:row.error_code,retryAfterSeconds:row.retry_after_seconds,manualRetryOnly:true,automaticSubmission:false,assetExecutionAuthorized:false};const payload={eventType:"execution.reconciliation_attempted",organizationId:org,objectType:"execution_preflight",objectId:row.preflight_id,data};await client.query("INSERT INTO audit_events(id,organization_id,event_type,actor,action,object_type,object_id,data,payload_hash) VALUES($1,$2,'execution.reconciliation_attempted',$3,'execution.reconciliation_attempted','execution_preflight',$4,$5,$6)",[makeId("audit"),org,{type:"adapter",id:this.adapter.provider},row.preflight_id,data,hash(payload)])}
  private map(row:any){return {id:row.id,organizationId:row.organization_id,preflightId:row.preflight_id,proposalId:row.proposal_id,ordinal:row.ordinal,previousObservationId:row.previous_observation_id,adapter:row.adapter,safeAddress:row.safe_address,safeTxHash:row.safe_tx_hash,state:row.state,confirmations:row.confirmations,confirmationsRequired:row.confirmations_required,executionTxHash:row.execution_tx_hash,executionBlockNumber:row.execution_block_number===null?null:Number(row.execution_block_number),executionBlockHash:row.execution_block_hash,onchainExecutionConfirmed:row.onchain_execution_confirmed,payload:row.payload,payloadHash:row.payload_hash,observedAt:new Date(row.observed_at).toISOString(),createdAt:new Date(row.created_at).toISOString(),signaturesStored:false,assetExecutionAuthorized:false}}
  private mapAttempt(row:any){return {id:row.id,organizationId:row.organization_id,preflightId:row.preflight_id,proposalId:row.proposal_id,ordinal:row.ordinal,safeTxHash:row.safe_tx_hash,adapter:row.adapter,outcome:row.outcome,errorCode:row.error_code,retryAfterSeconds:row.retry_after_seconds,observationId:row.observation_id,payload:row.payload,payloadHash:row.payload_hash,attemptedAt:new Date(row.attempted_at).toISOString(),createdAt:new Date(row.created_at).toISOString(),manualRetryOnly:true,automaticSubmission:false,assetExecutionAuthorized:false}}
}
