export const TRANSACTION_COST_PREDICATES={networkFee:"treasury.execution.network_fee_cost",protocolFee:"treasury.execution.protocol_fee_cost",executionShortfall:"treasury.execution.execution_shortfall_cost",slippage:"treasury.execution.slippage_bps",priceImpact:"treasury.execution.price_impact_bps"}as const;
type ManifestItem={evidenceId:string;contentHash:string};
export type CostEvidence={id:string;contentHash:string;predicate:string;subject:unknown;value:unknown;source:unknown;verificationStatus:string;qualityScore:number;conflictGroupId:string|null;observedAt:string|Date};
const object=(value:unknown,code:string):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(code);return value as Record<string,unknown>};
const hash=(value:unknown,code:string)=>{if(typeof value!=="string"||!/^0x[0-9a-f]{64}$/.test(value))throw new Error(code);return value};
const integer=(value:unknown,min:number,max:number,code:string)=>{if(!Number.isInteger(value)||Number(value)<min||Number(value)>max)throw new Error(code);return Number(value)};
const atomic=(value:unknown,code:string)=>{if(typeof value!=="string"||!/^\d{1,78}$/.test(value))throw new Error(code);return BigInt(value)};
const subjectMatches=(subject:unknown,input:{treasuryId:string;transactionHash:string;blockNumber:number;blockHash:string})=>{const value=object(subject,"TRANSACTION_COST_SUBJECT_INVALID");return value.type==="treasury_execution"&&value.treasuryId===input.treasuryId&&typeof value.transactionHash==="string"&&value.transactionHash.toLowerCase()===input.transactionHash.toLowerCase()&&Number(value.blockNumber)===input.blockNumber&&typeof value.blockHash==="string"&&value.blockHash.toLowerCase()===input.blockHash.toLowerCase()};
export function assessTransactionCosts(args:{manifest:ManifestItem[];evidence:CostEvidence[];treasuryId:string;transactionHash:string;blockNumber:number;blockHash:string;minimumQuality:number}){
  if(!Array.isArray(args.manifest)||args.manifest.length===0)throw new Error("TRANSACTION_COST_EVIDENCE_EMPTY");integer(args.blockNumber,0,Number.MAX_SAFE_INTEGER,"TRANSACTION_COST_BLOCK_INVALID");integer(args.minimumQuality,0,100,"TRANSACTION_COST_MINIMUM_QUALITY_INVALID");if(!/^0x[0-9a-fA-F]{64}$/.test(args.transactionHash)||!/^0x[0-9a-fA-F]{64}$/.test(args.blockHash))throw new Error("TRANSACTION_COST_CHAIN_IDENTITY_INVALID");
  const byId=new Map(args.evidence.map(row=>[row.id,row])),selected=new Map<string,CostEvidence>();
  for(const item of args.manifest){const row=byId.get(item.evidenceId);if(!row||row.contentHash!==item.contentHash)throw new Error("TRANSACTION_COST_MANIFEST_MISMATCH");if(row.verificationStatus!=="VERIFIED")throw new Error("TRANSACTION_COST_EVIDENCE_NOT_VERIFIED");if(row.qualityScore<args.minimumQuality)throw new Error("TRANSACTION_COST_EVIDENCE_QUALITY_LOW");if(row.conflictGroupId)throw new Error("TRANSACTION_COST_EVIDENCE_CONFLICT");if(Object.values(TRANSACTION_COST_PREDICATES).includes(row.predicate as any)){if(!subjectMatches(row.subject,args))throw new Error("TRANSACTION_COST_EXECUTION_MISMATCH");if(selected.has(row.predicate))throw new Error("TRANSACTION_COST_DUPLICATE_COMPONENT");selected.set(row.predicate,row)}}
  for(const predicate of Object.values(TRANSACTION_COST_PREDICATES))if(!selected.has(predicate))throw new Error(`TRANSACTION_COST_COMPONENT_MISSING:${predicate}`);
  const amount=(predicate:string,requireExclusion=false)=>{const row=selected.get(predicate)!,value=object(row.value,"TRANSACTION_COST_AMOUNT_INVALID"),source=object(row.source,"TRANSACTION_COST_SOURCE_INVALID");const symbol=value.symbol,decimals=integer(value.decimals,0,36,"TRANSACTION_COST_DECIMALS_INVALID"),methodologyHash=hash(value.methodologyHash,"TRANSACTION_COST_METHODOLOGY_HASH_INVALID");if(typeof symbol!=="string"||!/^[A-Z0-9]{2,16}$/.test(symbol))throw new Error("TRANSACTION_COST_SYMBOL_INVALID");if(value.measurement!=="OBSERVED")throw new Error("TRANSACTION_COST_NOT_OBSERVED");if(requireExclusion&&value.excludesNetworkAndProtocolFees!==true)throw new Error("TRANSACTION_COST_SHORTFALL_OVERLAP_UNSAFE");if(typeof source.provider!=="string"||source.provider.length<1||source.provider.length>100)throw new Error("TRANSACTION_COST_PROVIDER_INVALID");return{evidenceId:row.id,contentHash:row.contentHash,predicate,amountAtomic:atomic(value.amountAtomic,"TRANSACTION_COST_AMOUNT_INVALID"),symbol,decimals,methodologyHash,provider:source.provider,observedAt:new Date(row.observedAt).toISOString()}};
  const network=amount(TRANSACTION_COST_PREDICATES.networkFee),protocol=amount(TRANSACTION_COST_PREDICATES.protocolFee),shortfall=amount(TRANSACTION_COST_PREDICATES.executionShortfall,true),amounts=[network,protocol,shortfall];if(amounts.some(item=>item.symbol!==network.symbol||item.decimals!==network.decimals))throw new Error("TRANSACTION_COST_NUMERAIRE_MISMATCH");
  const diagnostic=(predicate:string)=>{const row=selected.get(predicate)!,value=object(row.value,"TRANSACTION_COST_BPS_INVALID");if(value.measurement!=="OBSERVED")throw new Error("TRANSACTION_COST_NOT_OBSERVED");return{evidenceId:row.id,contentHash:row.contentHash,predicate,bps:integer(value.bps,0,10_000,"TRANSACTION_COST_BPS_INVALID"),methodologyHash:hash(value.methodologyHash,"TRANSACTION_COST_METHODOLOGY_HASH_INVALID"),observedAt:new Date(row.observedAt).toISOString()}};
  const refs=[...amounts.map(item=>({...item,amountAtomic:item.amountAtomic.toString()})),diagnostic(TRANSACTION_COST_PREDICATES.slippage),diagnostic(TRANSACTION_COST_PREDICATES.priceImpact)];
  return{schemaVersion:"treasury.transaction-cost-assessment.v1",treasuryId:args.treasuryId,execution:{transactionHash:args.transactionHash.toLowerCase(),blockNumber:args.blockNumber,blockHash:args.blockHash.toLowerCase()},numeraire:{symbol:network.symbol,decimals:network.decimals},components:{networkFeeAtomic:network.amountAtomic.toString(),protocolFeeAtomic:protocol.amountAtomic.toString(),executionShortfallAtomic:shortfall.amountAtomic.toString(),totalObservedCostAtomic:(network.amountAtomic+protocol.amountAtomic+shortfall.amountAtomic).toString()},diagnostics:{slippageBps:(refs[3]as any).bps,priceImpactBps:(refs[4]as any).bps,diagnosticsNotAddedToTotal:true},evidenceRefs:refs,transactionCostKnown:true,transactionCostObservedNotCausal:true,counterfactualAvailable:false,netBenefitCalculated:false,causalAttribution:"NOT_ESTABLISHED",historicalPerformanceClaimed:false,memoryPromotionAuthorized:false,skillPromotionAuthorized:false,advisoryOnly:true,assetExecutionAuthorized:false}as const;
}
