type EvidenceBoundPid={id:string;treasuryId:string;policyVersionId:string;input:any;result:any;createdAt:string};
const integer=(value:unknown,min:number,max:number,code:string)=>{if(!Number.isInteger(value)||Number(value)<min||Number(value)>max)throw new Error(code);return Number(value)};
export function assessTreasuryOutcome(before:EvidenceBoundPid,after:EvidenceBoundPid,execution:{id:string;proposalId:string;transactionHash:string;observedAt:string}|null){
  if(before.treasuryId!==after.treasuryId)throw new Error("OUTCOME_TREASURY_MISMATCH");if(before.policyVersionId!==after.policyVersionId)throw new Error("OUTCOME_POLICY_MISMATCH");if(before.input?.sourceMode!=="EVIDENCE_DERIVED_OBSERVED_STATE"||after.input?.sourceMode!=="EVIDENCE_DERIVED_OBSERVED_STATE")throw new Error("OUTCOME_REQUIRES_EVIDENCE_BOUND_PID");
  const beforeAt=new Date(before.input.observedState?.observationAt).getTime(),afterAt=new Date(after.input.observedState?.observationAt).getTime();if(!Number.isFinite(beforeAt)||!Number.isFinite(afterAt)||afterAt<=beforeAt)throw new Error("OUTCOME_OBSERVATION_ORDER_INVALID");if(execution){const executionAt=new Date(execution.observedAt).getTime();if(!Number.isFinite(executionAt)||executionAt<beforeAt||executionAt>afterAt)throw new Error("OUTCOME_EXECUTION_OUTSIDE_OBSERVATION_WINDOW")}
  const beforeError=Math.abs(integer(before.result?.errorBps,-10_000,10_000,"OUTCOME_BEFORE_ERROR_INVALID")),afterError=Math.abs(integer(after.result?.errorBps,-10_000,10_000,"OUTCOME_AFTER_ERROR_INVALID"));const errorChangeBps=afterError-beforeError;
  const read=(snapshot:EvidenceBoundPid,key:string,max:number)=>integer(snapshot.input.observedState?.[key],0,max,`OUTCOME_${key.toUpperCase()}_INVALID`);const beforeAllocation=read(before,"observedAllocationBps",10_000),afterAllocation=read(after,"observedAllocationBps",10_000),beforeVolatility=read(before,"volatilityBps",100_000),afterVolatility=read(after,"volatilityBps",100_000),beforeLiquidityDrop=read(before,"liquidityDropBps",10_000),afterLiquidityDrop=read(after,"liquidityDropBps",10_000),beforePegDeviation=read(before,"pegDeviationBps",10_000),afterPegDeviation=read(after,"pegDeviationBps",10_000);
  return{schemaVersion:"treasury.outcome-assessment.v1",treasuryId:before.treasuryId,policyVersionId:before.policyVersionId,observationWindow:{before:new Date(beforeAt).toISOString(),after:new Date(afterAt).toISOString()},before:{adaptivePidSnapshotId:before.id,allocationBps:beforeAllocation,absoluteTargetErrorBps:beforeError,volatilityBps:beforeVolatility,liquidityDropBps:beforeLiquidityDrop,pegDeviationBps:beforePegDeviation,evidenceSnapshotId:before.input.evidenceSnapshotId},after:{adaptivePidSnapshotId:after.id,allocationBps:afterAllocation,absoluteTargetErrorBps:afterError,volatilityBps:afterVolatility,liquidityDropBps:afterLiquidityDrop,pegDeviationBps:afterPegDeviation,evidenceSnapshotId:after.input.evidenceSnapshotId},descriptiveChanges:{allocationBps:afterAllocation-beforeAllocation,absoluteTargetErrorBps:errorChangeBps,volatilityBps:afterVolatility-beforeVolatility,liquidityDropBps:afterLiquidityDrop-beforeLiquidityDrop,pegDeviationBps:afterPegDeviation-beforePegDeviation},classification:errorChangeBps<0?"IMPROVED_DESCRIPTIVE":errorChangeBps>0?"WORSENED_DESCRIPTIVE":"UNCHANGED_DESCRIPTIVE",executionLink:execution?{status:"CONFIRMED_EXECUTION",safeObservationId:execution.id,proposalId:execution.proposalId,transactionHash:execution.transactionHash,observedAt:new Date(execution.observedAt).toISOString()}:{status:"NOT_LINKED"},causalAttribution:"NOT_ESTABLISHED",counterfactualAvailable:false,transactionCostKnown:false,netBenefitCalculated:false,historicalPerformanceClaimed:false,memoryPromotionAuthorized:false,skillPromotionAuthorized:false,advisoryOnly:true,assetExecutionAuthorized:false}as const;
}
