const assert = require("node:assert/strict");
const { mkdtempSync, readFileSync, rmSync } = require("node:fs");
const { tmpdir } = require("node:os");
const { join } = require("node:path");
const test = require("node:test");
const { validatePlan } = require("./governance-stack-wallet-handoff-server.cjs");

const hash = (character) => `0x${character.repeat(64)}`;
function fixture() {
  const deployer="0x1111111111111111111111111111111111111111";const timelock="0x2222222222222222222222222222222222222222";
  const deployments=Array.from({length:5},(_,index)=>({sequence:index+1,nonce:7+index,contract:`Contract${index+1}`,predictedAddress:`0x${String(index+3).repeat(40)}`,to:null,value:"0x0",data:"0x6000",dataHash:hash("a"),requestHash:hash(String(index+1)),initCodeHash:hash("b"),requiresUserWalletConfirmation:true,signed:false,submitted:false}));
  const roles=Array.from({length:3},(_,index)=>({sequence:index+6,nonce:12+index,operation:`ROLE_${index+1}`,to:timelock,value:"0x0",data:"0x1234",dataHash:hash("c"),requestHash:hash(String(index+6)),requiresUserWalletConfirmation:true,signed:false,submitted:false}));
  return {schemaVersion:"aeos.governance-stack.deployment-plan.v1",chainId:102031,deployer,guardian:deployer,observedPendingNonce:7,planHash:hash("f"),addresses:{timelock},deploymentTransactions:deployments,roleTransactions:roles,safe:{status:"EXTERNAL_PENDING"},signed:false,submitted:false,containsPrivateKey:false,aeosSigningCapability:false,aeosBroadcastCapability:false,assetExecutionAuthorized:false};
}

test("page requires eight separate wallet requests and forbids signing/batching",()=>{const source=readFileSync(join(__dirname,"governance-stack-wallet-handoff.js"),"utf8");assert.match(source,/eth_requestAccounts/);assert.match(source,/eth_getTransactionCount/);assert.match(source,/web3_sha3/);assert.match(source,/crypto\.subtle\.digest/);assert.match(source,/eth_sendTransaction/);assert.match(source,/receipt\.status!=="0x1"/);assert.match(source,/No later transaction will be requested automatically/);assert.doesNotMatch(source,/privateKey|eth_signTransaction|wallet_sendCalls/);});
test("wallet RPC quantities accept canonical hex and defensive decimal strings",()=>{const source=readFileSync(join(__dirname,"governance-stack-wallet-handoff.js"),"utf8"),definition=source.match(/function parseRpcQuantity\(value\)\{[^}]+\}/)?.[0];assert.ok(definition);const parseRpcQuantity=Function(`"use strict";${definition};return parseRpcQuantity;`)();assert.equal(parseRpcQuantity("0xa"),10);assert.equal(parseRpcQuantity("10"),10);assert.equal(parseRpcQuantity(10),10);assert.throws(()=>parseRpcQuantity("0xzz"),/invalid RPC quantity/);assert.doesNotMatch(source,/Number\.parseInt\(nonceHex,16\)/);});
test("server rejects authority, count, nonce and value drift",()=>{const plan=fixture();assert.equal(validatePlan(plan),plan);assert.throws(()=>validatePlan({...plan,aeosBroadcastCapability:true}),/authority boundary/);assert.throws(()=>validatePlan({...plan,roleTransactions:plan.roleTransactions.slice(1)}),/exactly eight/);const nonce=fixture();nonce.roleTransactions[0].nonce+=1;assert.throws(()=>validatePlan(nonce),/nonce\/value/);const value=fixture();value.deploymentTransactions[0].value="0x1";assert.throws(()=>validatePlan(value),/nonce\/value/);});
test("submission and receipt ledgers are ordered, recoverable and immutable",()=>{const directory=mkdtempSync(join(tmpdir(),"aeos-governance-wallet-"));const original=process.env.GOVERNANCE_STACK_SUBMISSION_DIRECTORY;process.env.GOVERNANCE_STACK_SUBMISSION_DIRECTORY=directory;const modulePath=require.resolve("./governance-stack-wallet-handoff-server.cjs");delete require.cache[modulePath];const {readProgress,recordReceipt,recordSubmission}=require(modulePath);const plan=fixture();const first=plan.deploymentTransactions[0];assert.throws(()=>recordSubmission({sequence:2},plan),/Earlier/);const submitted=recordSubmission({sequence:1,from:plan.deployer,requestHash:first.requestHash,transactionHash:hash("d")},plan);assert.equal(submitted.walletRpcReceiptObserved,false);assert.equal(readProgress(plan).submissions.length,1);assert.throws(()=>recordSubmission({sequence:1},plan),/already exists/);const receipt=recordReceipt({sequence:1,transactionHash:hash("d"),receiptStatus:"0x1",blockNumber:"0x10",blockHash:hash("e"),contractAddress:first.predictedAddress},plan);assert.equal(receipt.independentCanonicalFinalityVerified,false);assert.equal(receipt.assetExecutionAuthorized,false);assert.equal(readProgress(plan).receipts.length,1);assert.throws(()=>recordReceipt({sequence:1},plan));if(original===undefined)delete process.env.GOVERNANCE_STACK_SUBMISSION_DIRECTORY;else process.env.GOVERNANCE_STACK_SUBMISSION_DIRECTORY=original;rmSync(directory,{recursive:true,force:true});});
