const assert = require("node:assert/strict");
const { mkdtempSync, readFileSync, writeFileSync } = require("node:fs");
const { tmpdir } = require("node:os");
const { join } = require("node:path");
const test = require("node:test");

const hash = (value) => `0x${value.repeat(64)}`;
const from = "0x444d510728fb8072351cb5d0e88432e6a8501dfa",governor="0xfe90b087fae789e043514b6ac3dbd7fd2d970268",guard="0x3c0cb960f32e6a222149a664a552ffc23e92c628";
const handoff={schemaVersion:"aeos.live-governance-hold-proposal.v1",status:"PROPOSAL_REQUEST_PREPARED",artifactHash:hash("1"),lineage:{decisionId:"decision_test",decisionOutputHash:hash("2"),decisionReviewOutcome:"APPROVED"},contracts:{treasuryGuard:guard},simulation:{callSucceeded:true,assetDelta:"NONE",assetExecutionAuthorized:false},proposal:{proposalType:"SECURITY_HOLD",proposalId:"123",proposalIdHex:hash("3"),semanticConsistencyVerified:true,action:{target:guard,paused:true,value:"0"}},unsignedTransaction:{chainId:102031,from,to:governor,value:"0x0",data:"0x7d5e81e200",dataHash:hash("4")},controls:{signed:false,submitted:false,signerCustody:false,broadcastCapability:false,assetExecutionAuthorized:false},truthBoundary:{decisionRecommendation:"HOLD",guardAlreadyPaused:true,proposedEffect:"MAINTAIN_PAUSE",treasuryAssetMovement:false,onchainProposalCreated:false}};

function loadWithPaths(value=handoff){const directory=mkdtempSync(join(tmpdir(),"aeos-governance-proposal-")),input=join(directory,"handoff.json"),output=join(directory,"submission.json");writeFileSync(input,JSON.stringify(value));process.env.AEOS_GOVERNANCE_PROPOSAL_HANDOFF_PATH=input;process.env.AEOS_GOVERNANCE_PROPOSAL_SUBMISSION_PATH=output;delete require.cache[require.resolve("./live-governance-proposal-wallet-handoff-server.cjs")];return{...require("./live-governance-proposal-wallet-handoff-server.cjs"),output}}

test("accepts only the exact approved zero-value SECURITY_HOLD Proposal",()=>{assert.deepEqual(loadWithPaths().readHandoff(),handoff);assert.throws(()=>loadWithPaths({...handoff,lineage:{...handoff.lineage,decisionReviewOutcome:"REJECTED"}}).readHandoff(),/lineage/);assert.throws(()=>loadWithPaths({...handoff,unsignedTransaction:{...handoff.unsignedTransaction,to:guard}}).readHandoff(),/transaction invalid/);assert.throws(()=>loadWithPaths({...handoff,truthBoundary:{...handoff.truthBoundary,treasuryAssetMovement:true}}).readHandoff(),/truth boundary/);assert.throws(()=>loadWithPaths({...handoff,controls:{...handoff.controls,broadcastCapability:true}}).readHandoff(),/authority boundary/)});

test("wallet page rechecks chain, account, deployed code, pause, calldata and simulation",()=>{const source=readFileSync(join(__dirname,"live-governance-proposal-wallet-handoff.js"),"utf8");for(const method of ["wallet_switchEthereumChain","eth_getCode","web3_sha3","eth_call","eth_estimateGas","eth_sendTransaction"])assert.match(source,new RegExp(method));assert.match(source,/pausedSelector/);assert.match(source,/from: tx\.from, to: tx\.to, data: tx\.data, value: "0x0"/);assert.doesNotMatch(source,/privateKey|eth_signTransaction|wallet_sendCalls/)});

test("records one immutable wallet submission without finality or authority claims",()=>{const loaded=loadWithPaths(),transactionHash=hash("5"),record=loaded.recordSubmission({transactionHash,from},handoff);assert.equal(record.status,"PROPOSAL_WALLET_SUBMITTED");assert.equal(record.receiptVerified,false);assert.equal(record.proposalCreatedEventObserved,false);assert.equal(record.privateKeyReceived,false);assert.equal(record.assetExecutionAuthorized,false);assert.deepEqual(JSON.parse(readFileSync(loaded.output,"utf8")),record);assert.throws(()=>loaded.recordSubmission({transactionHash:hash("6"),from},handoff),/different identity/)});
