CREATE TABLE IF NOT EXISTS evidence_anchor_confirmations(
 id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),handoff_id text NOT NULL REFERENCES evidence_anchor_handoffs(id),attestcoin_proof_job_id text NOT NULL REFERENCES attestcoin_proof_jobs(id),decision_id text NOT NULL REFERENCES decisions(id),evidence_snapshot_id text NOT NULL REFERENCES evidence_snapshots(id),commitment_id text NOT NULL,transaction_hash text NOT NULL CHECK(transaction_hash~'^0x[0-9a-f]{64}$'),block_number bigint NOT NULL CHECK(block_number>0),block_hash text NOT NULL CHECK(block_hash~'^0x[0-9a-f]{64}$'),snapshot jsonb NOT NULL,snapshot_hash text NOT NULL CHECK(snapshot_hash~'^0x[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,handoff_id),UNIQUE(organization_id,transaction_hash),UNIQUE(organization_id,commitment_id)
);
CREATE TABLE IF NOT EXISTS evidence_anchor_confirmation_attempts(
 id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),handoff_id text NOT NULL REFERENCES evidence_anchor_handoffs(id),ordinal integer NOT NULL CHECK(ordinal>0),transaction_hash text NOT NULL CHECK(transaction_hash~'^0x[0-9a-f]{64}$'),adapter text NOT NULL,outcome text NOT NULL CHECK(outcome IN('CONFIRMED','RETRYABLE','REJECTED')),error_code text,confirmation_id text REFERENCES evidence_anchor_confirmations(id),payload jsonb NOT NULL,payload_hash text NOT NULL CHECK(payload_hash~'^0x[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,handoff_id,ordinal),CHECK((outcome='CONFIRMED')=(confirmation_id IS NOT NULL)),CHECK((outcome='CONFIRMED')=(error_code IS NULL))
);
CREATE INDEX IF NOT EXISTS evidence_anchor_confirmations_org_created_idx ON evidence_anchor_confirmations(organization_id,created_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS evidence_anchor_attempts_org_handoff_idx ON evidence_anchor_confirmation_attempts(organization_id,handoff_id,ordinal);
CREATE OR REPLACE FUNCTION validate_evidence_anchor_confirmation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM evidence_anchor_handoffs h WHERE h.id=NEW.handoff_id AND h.organization_id=NEW.organization_id AND h.attestcoin_proof_job_id=NEW.attestcoin_proof_job_id AND h.decision_id=NEW.decision_id AND h.evidence_snapshot_id=NEW.evidence_snapshot_id AND h.commitment_id=NEW.commitment_id)THEN RAISE EXCEPTION 'Evidence Anchor confirmation lineage mismatch';END IF;RETURN NEW;END $$;
CREATE TRIGGER evidence_anchor_confirmation_guard BEFORE INSERT ON evidence_anchor_confirmations FOR EACH ROW EXECUTE FUNCTION validate_evidence_anchor_confirmation();
CREATE OR REPLACE FUNCTION validate_evidence_anchor_confirmation_attempt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM evidence_anchor_handoffs h WHERE h.id=NEW.handoff_id AND h.organization_id=NEW.organization_id)OR(NEW.confirmation_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM evidence_anchor_confirmations c WHERE c.id=NEW.confirmation_id AND c.organization_id=NEW.organization_id AND c.handoff_id=NEW.handoff_id))THEN RAISE EXCEPTION 'Evidence Anchor confirmation attempt lineage mismatch';END IF;RETURN NEW;END $$;
CREATE TRIGGER evidence_anchor_attempt_guard BEFORE INSERT ON evidence_anchor_confirmation_attempts FOR EACH ROW EXECUTE FUNCTION validate_evidence_anchor_confirmation_attempt();
CREATE TRIGGER evidence_anchor_confirmation_no_update BEFORE UPDATE OR DELETE ON evidence_anchor_confirmations FOR EACH ROW EXECUTE FUNCTION evidence_anchor_handoff_immutable();
CREATE TRIGGER evidence_anchor_attempt_no_update BEFORE UPDATE OR DELETE ON evidence_anchor_confirmation_attempts FOR EACH ROW EXECUTE FUNCTION evidence_anchor_handoff_immutable();
ALTER TABLE evidence_anchor_confirmations ENABLE ROW LEVEL SECURITY;ALTER TABLE evidence_anchor_confirmation_attempts ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_organization_isolation ON evidence_anchor_confirmations USING(aeos_is_system_worker() OR organization_id=aeos_current_organization_id())WITH CHECK(aeos_is_system_worker() OR organization_id=aeos_current_organization_id());
CREATE POLICY tenant_organization_isolation ON evidence_anchor_confirmation_attempts USING(aeos_is_system_worker() OR organization_id=aeos_current_organization_id())WITH CHECK(aeos_is_system_worker() OR organization_id=aeos_current_organization_id());
GRANT SELECT,INSERT,UPDATE,DELETE ON evidence_anchor_confirmations,evidence_anchor_confirmation_attempts TO aeos_app;
