CREATE TABLE treasury_transaction_cost_assessments(
 id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),treasury_outcome_id text NOT NULL REFERENCES treasury_outcome_assessments(id),treasury_id text NOT NULL,policy_version_id text NOT NULL REFERENCES policy_versions(id),safe_observation_id text NOT NULL REFERENCES safe_transaction_observations(id),evidence_snapshot_id text NOT NULL REFERENCES evidence_snapshots(id),assessment jsonb NOT NULL,assessment_hash text NOT NULL CHECK(assessment_hash~'^0x[0-9a-f]{64}$'),created_by text NOT NULL,
 transaction_cost_known boolean NOT NULL DEFAULT true CHECK(transaction_cost_known=true),counterfactual_available boolean NOT NULL DEFAULT false CHECK(counterfactual_available=false),net_benefit_calculated boolean NOT NULL DEFAULT false CHECK(net_benefit_calculated=false),causal_attribution_established boolean NOT NULL DEFAULT false CHECK(causal_attribution_established=false),memory_promotion_authorized boolean NOT NULL DEFAULT false CHECK(memory_promotion_authorized=false),skill_promotion_authorized boolean NOT NULL DEFAULT false CHECK(skill_promotion_authorized=false),advisory_only boolean NOT NULL DEFAULT true CHECK(advisory_only=true),asset_execution_authorized boolean NOT NULL DEFAULT false CHECK(asset_execution_authorized=false),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,treasury_outcome_id,evidence_snapshot_id));
CREATE INDEX treasury_transaction_cost_org_outcome_idx ON treasury_transaction_cost_assessments(organization_id,treasury_outcome_id,created_at DESC,id DESC);
CREATE OR REPLACE FUNCTION guard_treasury_transaction_cost_assessment() RETURNS trigger AS $$ DECLARE o treasury_outcome_assessments%ROWTYPE;s safe_transaction_observations%ROWTYPE;es evidence_snapshots%ROWTYPE;BEGIN SELECT * INTO o FROM treasury_outcome_assessments WHERE id=NEW.treasury_outcome_id;SELECT * INTO s FROM safe_transaction_observations WHERE id=NEW.safe_observation_id;SELECT * INTO es FROM evidence_snapshots WHERE id=NEW.evidence_snapshot_id;IF o.organization_id IS DISTINCT FROM NEW.organization_id OR o.treasury_id IS DISTINCT FROM NEW.treasury_id OR o.policy_version_id IS DISTINCT FROM NEW.policy_version_id OR o.safe_observation_id IS NULL OR o.safe_observation_id IS DISTINCT FROM NEW.safe_observation_id OR s.organization_id IS DISTINCT FROM NEW.organization_id OR s.state<>'EXECUTED' OR s.onchain_execution_confirmed<>true OR s.execution_tx_hash IS NULL OR s.execution_block_number IS NULL OR s.execution_block_hash IS NULL OR es.organization_id IS DISTINCT FROM NEW.organization_id THEN RAISE EXCEPTION 'treasury transaction cost lineage mismatch';END IF;RETURN NEW;END;$$ LANGUAGE plpgsql;
CREATE TRIGGER treasury_transaction_cost_lineage_guard BEFORE INSERT ON treasury_transaction_cost_assessments FOR EACH ROW EXECUTE FUNCTION guard_treasury_transaction_cost_assessment();
CREATE OR REPLACE FUNCTION prevent_treasury_transaction_cost_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'treasury transaction cost assessments are immutable';END;$$ LANGUAGE plpgsql;
CREATE TRIGGER treasury_transaction_cost_immutable BEFORE UPDATE OR DELETE ON treasury_transaction_cost_assessments FOR EACH ROW EXECUTE FUNCTION prevent_treasury_transaction_cost_mutation();
ALTER TABLE treasury_transaction_cost_assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_organization_isolation ON treasury_transaction_cost_assessments USING(aeos_is_system_worker() OR organization_id=aeos_current_organization_id()) WITH CHECK(aeos_is_system_worker() OR organization_id=aeos_current_organization_id());
GRANT SELECT,INSERT,UPDATE,DELETE ON treasury_transaction_cost_assessments TO aeos_app;
