ALTER TABLE treasury_workflows DROP CONSTRAINT treasury_workflows_workload_type_check;
ALTER TABLE treasury_workflows ADD CONSTRAINT treasury_workflows_workload_type_check CHECK(workload_type IN('EVIDENCE_REFRESH','DECISION_ANALYSIS','POLICY_SIMULATION','EVIDENCE_BOUND_ADAPTIVE_PID','MONITORING_SCAN','GOVERNANCE_PREPARATION','EXECUTION_PREFLIGHT','EXECUTION_RECONCILIATION'));
