"use client";

import {useCallback,useEffect,useState} from "react";
import {ApiError,useSession} from "../ui/session-context";
import {DEMO_ADVISORY_RUBRIC_V1} from "./demo-advisory-rubric-v1";

type PreviewChunk={index:number;heading:string;contentHash:string;characterCount:number;preview:string};
type DraftResult={id:string;sourceKey:string;version:number;status:string;partition:string;contentHash:string;originalContentHash:string;redactionApplied:boolean;scanResult:{safe:boolean;codes:string[];contentHash:string};persistedChunkCount:number;prospectiveChunks:PreviewChunk[];previewOnly:boolean;assetExecutionAuthorized:boolean};
type SourceInventory={id:string;sourceKey:string;partition:string;version:number;title:string;status:string;contentHash:string;originalContentHash:string;scanResult:{safe:boolean;codes:string[]};chunkCount:number;retrievalStatus:string;createdAt:string;assetExecutionAuthorized:boolean};
type ApprovalResult={id:string;status:string;chunkCount:number;retrievalStatus:string;assetExecutionAuthorized:boolean};

export function DraftSourcePanel(){
  const auth=useSession();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[results,setResults]=useState<DraftResult[]>([]);const[inventory,setInventory]=useState<SourceInventory[]>([]);const[approvals,setApprovals]=useState<ApprovalResult[]>([]);
  const eligible=Boolean(auth.session?.activeOrganizationId&&["ADMIN","REVIEWER"].includes(auth.session.role??"")&&auth.canMutate);
  const loadSources=useCallback(async()=>{if(!auth.session?.activeOrganizationId){setInventory([]);return}try{const response=await auth.request<{items:SourceInventory[]}>("/knowledge/sources");setInventory(response.items.filter(item=>DEMO_ADVISORY_RUBRIC_V1.some(source=>source.sourceKey===item.sourceKey)))}catch(cause){setError(cause instanceof ApiError?`${cause.code}: ${cause.message}`:cause instanceof Error?cause.message:"Unable to read Knowledge Sources.")}},[auth]);
  useEffect(()=>{void loadSources()},[loadSources]);
  const createDrafts=async()=>{setBusy(true);setError("");const created:DraftResult[]=[];try{for(const source of DEMO_ADVISORY_RUBRIC_V1){const result=await auth.request<DraftResult>("/knowledge/sources",{method:"POST",csrf:true,headers:{"idempotency-key":`demo-advisory-rubric-v1-draft-${source.sourceKey}`},body:JSON.stringify(source)});if(result.status!=="DRAFT"||result.assetExecutionAuthorized!==false||result.persistedChunkCount!==0)throw new Error(`Draft boundary failed for ${source.sourceKey}`);created.push(result);setResults([...created])}await loadSources()}catch(cause){setError(cause instanceof ApiError?`${cause.code}: ${cause.message}`:cause instanceof Error?cause.message:"Draft creation failed.")}finally{setBusy(false)}};
  const rubricInventory=DEMO_ADVISORY_RUBRIC_V1.map(source=>inventory.find(item=>item.sourceKey===source.sourceKey)).filter((item):item is SourceInventory=>Boolean(item));
  const corpusReady=rubricInventory.length===5&&rubricInventory.every(item=>item.version===1&&["DRAFT","APPROVED"].includes(item.status));
  const approvedCount=rubricInventory.filter(item=>item.status==="APPROVED").length;
  const approveAll=async()=>{setBusy(true);setError("");const confirmed:ApprovalResult[]=[];try{if(!corpusReady)throw new Error("The exact five-source V1 corpus is not available for approval.");for(const source of DEMO_ADVISORY_RUBRIC_V1){const current=rubricInventory.find(item=>item.sourceKey===source.sourceKey);if(!current)throw new Error(`Missing ${source.sourceKey}`);if(current.status==="APPROVED")continue;const result=await auth.request<ApprovalResult>(`/knowledge/sources/${encodeURIComponent(current.id)}/approve`,{method:"POST",csrf:true,headers:{"idempotency-key":`demo-advisory-rubric-v1-approve-${current.id}`},body:JSON.stringify({rationale:`Human owner approved ${source.sourceKey} under DEMO_ADVISORY_RUBRIC_V1 for role-scoped advisory retrieval. This approval grants no PolicyRegistry, wallet, broadcast, governance, or asset authority.`})});if(result.status!=="APPROVED"||result.retrievalStatus!=="AVAILABLE"||result.chunkCount<1||result.assetExecutionAuthorized!==false)throw new Error(`Approval boundary failed for ${source.sourceKey}`);confirmed.push(result);setApprovals([...confirmed]);await loadSources()}}catch(cause){setError(cause instanceof ApiError?`${cause.code}: ${cause.message}`:cause instanceof Error?cause.message:"Approval failed.")}finally{setBusy(false)}};
  return <section className="terminal-panel" aria-labelledby="draft-corpus-title" style={{marginTop:"16px"}}><header><div><span className="terminal-kicker">HUMAN-CONFIRMED INPUT</span><h2 id="draft-corpus-title">DEMO_ADVISORY_RUBRIC_V1 Corpus</h2></div><span className={approvedCount===5?"verified-chip":"advisory-chip"}>{approvedCount===5?"5 APPROVED":`${approvedCount}/5 APPROVED`}</span></header>
    <p>Each approval is a separate append-only human record. It persists deterministic chunks for advisory retrieval only; Agent execution and asset authority remain withheld.</p>
    <div className="mvp-heading-actions"><button type="button" onClick={createDrafts} disabled={!eligible||busy||inventory.length>0}>{busy?"PROCESSING":results.length===5?"5 DRAFTS CREATED":"CREATE 5 DRAFT SOURCES"}</button><button type="button" onClick={approveAll} disabled={!eligible||busy||!corpusReady||approvedCount===5}>{busy?`APPROVING ${approvedCount+approvals.length}/5`:approvedCount===5?"ALL 5 SOURCES APPROVED":"APPROVE ALL 5 SOURCES"}</button></div>
    {!auth.session?.activeOrganizationId&&<p className="warning-banner">Select AEOS Hackathon Demo DAO in the workspace control first.</p>}
    {auth.session?.activeOrganizationId&&!auth.canMutate&&<p className="warning-banner">Re-authenticate SIWE to restore the in-memory CSRF token before this write.</p>}
    {error&&<p className="error-banner" role="alert">{error}</p>}
    {rubricInventory.map(result=><article key={result.id} style={{borderTop:"1px solid var(--line, #16445b)",marginTop:"14px",paddingTop:"12px"}}><h3>{result.sourceKey}</h3><dl><dt>Source ID</dt><dd>{result.id}</dd><dt>Status</dt><dd>{result.status}</dd><dt>Content hash</dt><dd>{result.contentHash}</dd><dt>Scan</dt><dd>{result.scanResult.safe?"SAFE":"BLOCKED"} / {result.scanResult.codes.length?result.scanResult.codes.join(", "):"NO FINDINGS"}</dd><dt>Persisted chunks</dt><dd>{result.chunkCount}</dd><dt>Retrieval status</dt><dd>{result.retrievalStatus}</dd></dl>{results.find(item=>item.id===result.id)&&<details><summary>Prospective deterministic chunk preview ({results.find(item=>item.id===result.id)?.prospectiveChunks.length})</summary>{results.find(item=>item.id===result.id)?.prospectiveChunks.map(chunk=><div key={chunk.contentHash}><b>{chunk.index+1}. {chunk.heading}</b><code>{chunk.contentHash}</code><p>{chunk.preview}</p></div>)}</details>}</article>)}
    <footer><strong>ASSET EXECUTION AUTHORIZED / false</strong><span> Approval permits advisory retrieval only · no Agent run · no signature · no broadcast</span></footer>
  </section>;
}
